"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowRight, Clock3, Search, Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { ECONOMIC_CASES } from "@/lib/cases/definitions";
import type { CaseCategory, CaseDifficulty } from "@/lib/cases/types";

const categories: Array<"All" | CaseCategory> = ["All", "macroeconomics", "environment", "housing", "labour", "trade", "business-decision"];
const difficulties: Array<"All" | CaseDifficulty> = ["All", "Beginner", "Intermediate", "Advanced"];
export default function CasesPage() {
  const [query, setQuery] = useState(""); const [category, setCategory] = useState<"All" | CaseCategory>("All"); const [difficulty, setDifficulty] = useState<"All" | CaseDifficulty>("All");
  const items = useMemo(() => { const needle = query.trim().toLowerCase(); return ECONOMIC_CASES.filter((item) => (category === "All" || item.category === category) && (difficulty === "All" || item.difficulty === difficulty) && (!needle || [item.title, item.subtitle, item.category, ...item.realWorldContext.actors].join(" ").toLowerCase().includes(needle))); }, [query, category, difficulty]);
  return <main className="min-h-screen p-5 sm:p-8 lg:p-10"><div className="mx-auto max-w-6xl"><header className="max-w-3xl"><p className="text-[10px] font-extrabold uppercase tracking-[.18em] text-[var(--accent)]">Real-world cases</p><h1 className="mt-3 text-4xl font-bold tracking-[-.05em] sm:text-5xl">Make an economic decision, then inspect its assumptions.</h1><p className="mt-5 text-base leading-7 text-[var(--ink-muted)]">Six structured cases connect real-world context to transparent classroom models. Work locally as a guest; sign in only when you want to save a private case record.</p></header><section className="mt-9 rounded-xl border border-[var(--line)] bg-[var(--surface)] p-4"><label className="relative block"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--ink-faint)]" size={16} /><span className="sr-only">Search cases</span><input value={query} onChange={(event) => setQuery(event.target.value)} className="h-11 w-full rounded-lg border border-[var(--line)] bg-[var(--canvas)] pl-10 pr-3 text-sm outline-none focus:border-[var(--accent)]" placeholder="Search cases, actors, or concepts" /></label><div className="mt-4 grid gap-4 md:grid-cols-2"><Filter label="Category" values={categories} value={category} onChange={(value) => setCategory(value as typeof category)} /><Filter label="Difficulty" values={difficulties} value={difficulty} onChange={(value) => setDifficulty(value as typeof difficulty)} /></div></section><div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => <Link key={item.slug} href={`/cases/${item.slug}`} className="group rounded-xl border border-[var(--line)] bg-[var(--surface)] p-5 shadow-[var(--shadow)] transition-transform hover:-translate-y-0.5"><div className="flex items-start justify-between gap-3"><span className="grid size-10 place-items-center rounded-lg bg-[var(--accent-soft)] text-[var(--accent)]"><Sparkles size={18} /></span>{item.featured && <Badge className="bg-[var(--amber-soft)] text-[var(--amber)]">Featured</Badge>}</div><h2 className="mt-5 text-xl font-bold">{item.title}</h2><p className="mt-2 text-sm leading-6 text-[var(--ink-muted)]">{item.subtitle}</p><div className="mt-4 flex flex-wrap gap-2 text-[10px] font-bold uppercase tracking-wider text-[var(--ink-faint)]"><span>{item.category.replace("-", " ")}</span><span>·</span><span>{item.difficulty}</span><span>·</span><span className="inline-flex items-center gap-1"><Clock3 size={11} />{item.estimatedMinutes} min</span></div><div className="mt-5 flex items-center gap-2 text-xs font-bold text-[var(--accent)]">Open case <ArrowRight size={14} /></div></Link>)}</div>{items.length === 0 && <p className="mt-16 text-center text-sm text-[var(--ink-muted)]">No cases match those filters.</p>}<p className="mt-8 text-center text-xs text-[var(--ink-faint)]"><Link className="font-bold text-[var(--accent)]" href="/cases/history">View my saved case history</Link></p></div></main>;
}
function Filter({ label, values, value, onChange }: { label: string; values: readonly string[]; value: string; onChange: (value: string) => void }) { return <div><p className="mb-2 text-[9px] font-bold uppercase tracking-wider text-[var(--ink-faint)]">{label}</p><div className="flex flex-wrap gap-1.5">{values.map((item) => <button key={item} type="button" onClick={() => onChange(item)} className={`rounded-md px-2.5 py-1.5 text-[10px] font-bold ${value === item ? "bg-[var(--accent)] text-white" : "bg-[var(--surface-subtle)] text-[var(--ink-muted)]"}`}>{item.replace("-", " ")}</button>)}</div></div>; }
