import { DEFAULT_FOOD_WASTE } from "@/lib/economics/food-waste";
import type { CasePolicyControl, EconomicCaseDefinition } from "@/lib/cases/types";

const official = (label: string, url: string, note: string) => ({ label, url, note, sourceType: "official" as const });
const calibrated = (key: string, label: string, defaultValue: number, min: number, max: number, step: number, unit: string, description: string): CasePolicyControl => ({ key, label, defaultValue, min, max, step, unit, description });

const commonEvaluation = {
  objectives: [
    { key: "efficiency", label: "Efficiency", defaultWeight: 40 },
    { key: "equity", label: "Equity", defaultWeight: 35 },
    { key: "fiscal", label: "Fiscal sustainability", defaultWeight: 25 },
  ],
  note: "Scores are transparent teaching judgements derived from the selected stylised model. They are not forecasts or policy advice.",
};

/**
 * The case library deliberately distinguishes factual context from calibrated
 * starting values. All adjustable numbers are indexed/stylised unless a source
 * and date say otherwise, so a learner never mistakes a classroom simulation
 * for an estimate of a named economy or firm.
 */
export const ECONOMIC_CASES: EconomicCaseDefinition[] = [
  {
    id: "oil-price-shock", slug: "oil-price-shock", title: "Oil Price Shock", subtitle: "Balance inflation control, household support, and output after an adverse energy-cost shock.", status: "published", featured: false, category: "macroeconomics", difficulty: "Intermediate", estimatedMinutes: 20, simulationAdapterKey: "oil-price-shock", evaluationConfig: commonEvaluation,
    realWorldContext: { overview: "A stylised importing economy faces a sudden energy-price increase. The shock raises firms’ costs before wages, contracts, and investment fully adjust.", location: "Open economy (stylised)", actors: ["Households", "Energy-intensive firms", "Central bank", "Government"], decision: "Choose a policy mix that contains inflation without treating a classroom index as a forecast.", significance: "Energy shocks can create a short-run inflation-output trade-off.", facts: ["Oil prices and supply conditions can shift quickly.", "The IEA’s Oil Market Report tracks these market conditions."], assumptions: ["The shock is represented as a supply-side index shift, not a barrel-price forecast."] },
    economicProblem: { primaryOptions: ["Adverse supply shock", "Demand boom", "Positive productivity shock", "Pure redistribution"], secondaryOptions: ["Inflation-output trade-off", "No trade-off"], correctPrimary: "Adverse supply shock", correctSecondary: ["Inflation-output trade-off"], reveal: "Higher energy costs shift short-run aggregate supply adversely: inflation pressure rises while output can fall." },
    modelMappings: [{ model: "AD–AS / Phillips transmission", route: "/models/ad-as", realWorldEvent: "Energy becomes more costly", mechanism: "Production costs rise", modelVariable: "Supply shock", response: "SRAS pressure increases; output and inflation move in opposing directions", expectedOutcome: "Higher inflation and lower activity in the short run", selectedReason: "It makes the supply-side channel visible.", omittedVariables: ["Exchange rates", "Strategic petroleum reserves", "Sectoral heterogeneity"], alternatives: ["IS–LM for a demand-policy response"], limitation: "The mapping uses indexed teaching parameters, not an econometric forecast." }],
    initialConditions: [{ key: "energyShock", label: "Energy-cost shock", value: 12, unit: "index points", sourceType: "calibrated", note: "Teaching calibration; not a quoted oil-price change." }, { key: "policyRate", label: "Policy rate", value: 4, unit: "%", sourceType: "indexed", note: "Starts at the Sandbox baseline." }],
    predictionQuestions: [{ id: "inflation", prompt: "Before running the model, which short-run direction is most likely?", type: "choice", options: ["Inflation up, output down", "Inflation down, output up", "Both unchanged"], required: true }, { id: "tradeoff", prompt: "Name one group that may need targeted support if policy tightens.", type: "text", required: true }],
    availablePolicies: [calibrated("energyShock", "Energy-cost shock", 12, 0, 30, 1, " index", "A calibrated adverse supply shock."), calibrated("policyRate", "Policy rate", 4, 0, 12, 0.25, "%", "A stylised central-bank policy rate."), calibrated("householdRelief", "Targeted household relief", 0, 0, 30, 1, " index", "A small targeted fiscal-support index.")],
    constraints: [{ label: "Inflation guardrail", rule: "Avoid treating a lower unemployment index as proof of welfare.", explanation: "The model shows a trade-off, not a complete welfare calculation." }, { label: "Budget guardrail", rule: "Relief uses public resources.", explanation: "Fiscal cost rises with targeted relief." }],
    outputMetrics: [{ key: "inflation", label: "Inflation", unit: "%", meaning: "Stylised short-run inflation estimate." }, { key: "output", label: "Output index", unit: "index", meaning: "Activity relative to a teaching baseline." }, { key: "unemployment", label: "Unemployment", unit: "%", meaning: "Mapped short-run labour-market pressure." }],
    stakeholderGroups: [{ name: "Low-income households", note: "Energy expenditure can be a larger budget share." }, { name: "Energy-intensive firms", note: "Face higher marginal costs." }, { name: "Central bank", note: "Balances price stability against activity." }], reflectionQuestions: ["Which channel is not represented by the aggregate model?", "What evidence would you need before selecting actual relief?"], evidenceSources: [official("IEA Oil Market Report", "https://www.iea.org/reports/oil-market-report-march-2026", "Official market context; the simulation itself is calibrated."), official("IMF commodity data", "https://www.imf.org/en/Research/commodity-prices", "Public context for commodity-price variation.")],
  },
  {
    id: "carbon-tax", slug: "carbon-tax", title: "Carbon Tax Design", subtitle: "Use a corrective price while considering output, revenue, distribution, and alternatives.", status: "published", featured: false, category: "environment", difficulty: "Intermediate", estimatedMinutes: 22, simulationAdapterKey: "carbon-tax", evaluationConfig: commonEvaluation,
    realWorldContext: { overview: "A stylised carbon-intensive market does not include the full climate cost in its private production decision. Government considers a tax and targeted recycling of revenue.", location: "Market-level policy case (stylised)", actors: ["Consumers", "Emitting firms", "Government", "Future residents"], decision: "Choose a corrective tax and a revenue-recycling emphasis.", significance: "Carbon pricing makes an external cost visible in market incentives.", facts: ["Carbon taxes and emissions trading systems are in use in many jurisdictions.", "Design and revenue use affect distributional outcomes."], assumptions: ["The per-unit external cost is a teaching calibration, not a social-cost estimate."] },
    economicProblem: { primaryOptions: ["Negative externality", "Public good", "Natural monopoly", "Information asymmetry"], secondaryOptions: ["Private cost is below social cost", "Private cost is above social cost"], correctPrimary: "Negative externality", correctSecondary: ["Private cost is below social cost"], reveal: "With an unpriced negative externality, the private market quantity exceeds the simplified social optimum." },
    modelMappings: [{ model: "Externalities", route: "/models/externalities", realWorldEvent: "Emissions impose an unpriced cost", mechanism: "Marginal social cost exceeds private supply cost", modelVariable: "External cost / corrective tax", response: "A tax shifts the producer-side incentive", expectedOutcome: "Output moves toward the efficient quantity", selectedReason: "It directly distinguishes private and social marginal cost.", omittedVariables: ["Innovation", "Cross-border leakage", "Measurement uncertainty"], alternatives: ["Policy Lab for broad macro spillovers"], limitation: "It assumes the external cost is known and constant per unit." }],
    initialConditions: [{ key: "externalCost", label: "External cost", value: 10, unit: "per unit", sourceType: "calibrated", note: "Illustrative teaching value." }, { key: "recycling", label: "Revenue recycling", value: 20, unit: "%", sourceType: "indexed", note: "Share targeted to lower-income households in this case." }],
    predictionQuestions: [{ id: "quantity", prompt: "What happens to market output when a binding corrective tax rises?", type: "choice", options: ["It falls toward the efficient quantity", "It rises above the market quantity", "It is mechanically unchanged"], required: true }, { id: "equity", prompt: "Which group needs particular distributional attention?", type: "text", required: true }],
    availablePolicies: [calibrated("carbonTax", "Corrective carbon tax", 10, 0, 40, 1, " per unit", "The per-unit charge introduced into the market."), calibrated("recycling", "Targeted revenue recycling", 20, 0, 100, 5, "%", "Share of notional tax revenue directed to low-income households."), calibrated("greenSubsidy", "Green-transition support", 0, 0, 30, 1, " index", "A stylised complement, not a separately optimised programme.")],
    constraints: [{ label: "Efficiency", rule: "Tax cannot be negative.", explanation: "This case models a negative externality only." }, { label: "Equity", rule: "Revenue recycling is capped at available notional revenue.", explanation: "A share is not a new independent funding source." }],
    outputMetrics: [{ key: "quantity", label: "Market quantity", unit: "units", meaning: "Quantity under the selected charge." }, { key: "welfare", label: "Potential welfare gain", unit: "model value", meaning: "Gain from moving toward the static efficient quantity." }, { key: "revenue", label: "Tax revenue", unit: "model value", meaning: "Tax times quantity, before recycled transfers." }],
    stakeholderGroups: [{ name: "Low-income households", note: "May experience higher energy-related prices." }, { name: "Emitting firms", note: "Face a stronger abatement or output incentive." }, { name: "Future residents", note: "Benefit if external harm is reduced." }], reflectionQuestions: ["Why might the correct tax differ across sectors?", "Which emissions or welfare data would you need?"], evidenceSources: [official("World Bank Carbon Pricing Dashboard", "https://carbonpricingdashboard.worldbank.org/", "Official global policy context."), official("UNFCCC", "https://unfccc.int/", "Official international climate-policy context.")],
  },
  {
    id: "housing-rent-control", slug: "housing-rent-control", title: "Housing Rent Control", subtitle: "Examine affordability, shortages, allocation, and supply incentives under a binding rent ceiling.", status: "published", featured: false, category: "housing", difficulty: "Intermediate", estimatedMinutes: 22, simulationAdapterKey: "housing-rent-control", evaluationConfig: commonEvaluation,
    realWorldContext: { overview: "A city faces a tight rental market. Policymakers consider a rent ceiling alongside construction support, but cannot assume that a lower listed rent guarantees access.", location: "Urban rental market (stylised)", actors: ["Tenants", "Landlords", "Prospective movers", "City government"], decision: "Set a rent ceiling and supply-side support while exposing the rationing trade-off.", significance: "Housing affordability includes both price and access.", facts: ["Rent regulation has different designs and exemptions.", "Housing supply responds slowly in many locations."], assumptions: ["One homogeneous rental unit; allocation is initially modelled as efficient rationing."] },
    economicProblem: { primaryOptions: ["Binding price ceiling", "Price floor", "Positive externality", "Public good"], secondaryOptions: ["Shortage risk", "Surplus risk"], correctPrimary: "Binding price ceiling", correctSecondary: ["Shortage risk"], reveal: "A ceiling below equilibrium price increases quantity demanded relative to quantity supplied in the simple market." },
    modelMappings: [{ model: "Price Controls", route: "/models/price-controls", realWorldEvent: "Legal rent cap", mechanism: "Ceiling can sit below equilibrium", modelVariable: "Control price", response: "Quantity supplied becomes the short side", expectedOutcome: "Lower paid rent but possible shortage", selectedReason: "It separates price affordability from allocation.", omittedVariables: ["Tenant quality", "Search costs", "New construction lags"], alternatives: ["Elasticity for long-run supply responsiveness"], limitation: "The model does not determine who receives scarce homes." }],
    initialConditions: [{ key: "rentCeiling", label: "Rent ceiling", value: 15, unit: "rent index", sourceType: "calibrated", note: "Below the classroom equilibrium by design." }, { key: "supplySupport", label: "Supply support", value: 0, unit: "index", sourceType: "indexed", note: "A simple outward-supply proxy." }],
    predictionQuestions: [{ id: "access", prompt: "If the ceiling is binding, what constrains actual rentals?", type: "choice", options: ["Quantity supplied", "Quantity demanded", "Neither; everyone rents"], required: true }, { id: "allocation", prompt: "Name a real allocation mechanism missing from the model.", type: "text", required: true }],
    availablePolicies: [calibrated("rentCeiling", "Monthly rent ceiling", 15, 5, 35, 1, " rent index", "A legal price cap in the stylised market."), calibrated("supplySupport", "Construction / supply support", 0, 0, 30, 1, " index", "Shifts supply outward in the teaching calibration."), calibrated("tenantSupport", "Targeted tenant support", 0, 0, 20, 1, " index", "A transfer proxy with fiscal cost.")],
    constraints: [{ label: "Access", rule: "A lower controlled rent may still create a shortage.", explanation: "The short side of the market determines trades." }, { label: "Supply", rule: "Supply support cannot instantly create all units.", explanation: "This remains a static teaching representation." }],
    outputMetrics: [{ key: "shortage", label: "Rental shortage", unit: "units", meaning: "Excess demand under a binding cap." }, { key: "traded", label: "Units rented", unit: "units", meaning: "Quantity available in the simplified market." }, { key: "dwl", label: "Deadweight loss", unit: "model value", meaning: "Lost surplus under efficient-rationing assumption." }],
    stakeholderGroups: [{ name: "Incumbent tenants", note: "May pay lower rent if they secure a unit." }, { name: "Prospective tenants", note: "May face queues or exclusion." }, { name: "Landlords / builders", note: "Supply incentives can change." }], reflectionQuestions: ["Who receives scarce units in reality?", "What vacancy, construction, and tenant-turnover data matter?"], evidenceSources: [official("OECD Housing", "https://www.oecd.org/en/topics/housing.html", "Public housing-policy context."), official("UN-Habitat", "https://unhabitat.org/", "Official urban-housing context.")],
  },
  {
    id: "minimum-wage", slug: "minimum-wage", title: "Minimum Wage", subtitle: "Compare wage protection, labour demand, and targeted support in a transparent labour-market proxy.", status: "published", featured: false, category: "labour", difficulty: "Intermediate", estimatedMinutes: 20, simulationAdapterKey: "minimum-wage", evaluationConfig: commonEvaluation,
    realWorldContext: { overview: "A government considers raising a statutory wage floor in a low-wage sector. The classroom model treats labour as a market with a simplified demand and supply schedule.", location: "Low-wage sector (stylised)", actors: ["Low-wage workers", "Job seekers", "Small employers", "Government"], decision: "Choose a wage floor and complementary worker support.", significance: "A wage floor can change earnings and employment incentives; empirical magnitude depends on local conditions.", facts: ["Actual effects depend on labour-demand elasticity, enforcement, and employer market power.", "This case does not claim a universal employment effect."], assumptions: ["Competitive labour-market proxy; hours, skills, and monopsony are not represented."] },
    economicProblem: { primaryOptions: ["Binding price floor", "Binding price ceiling", "Negative externality", "Tariff"], secondaryOptions: ["Labour surplus risk", "Labour shortage risk"], correctPrimary: "Binding price floor", correctSecondary: ["Labour surplus risk"], reveal: "In the competitive classroom proxy, a binding wage floor makes labour supplied exceed labour demanded." },
    modelMappings: [{ model: "Price Controls + Policy Lab", route: "/models/price-controls", realWorldEvent: "Statutory wage floor", mechanism: "Floor can sit above market-clearing wage", modelVariable: "Control price", response: "Labour supplied and demanded can diverge", expectedOutcome: "Higher paid wage for employed workers with possible employment trade-off", selectedReason: "It makes the competitive benchmark explicit.", omittedVariables: ["Monopsony", "Productivity", "Hours", "Informality"], alternatives: ["Elasticity"], limitation: "This is not an empirical estimate of a real minimum-wage policy." }],
    initialConditions: [{ key: "minimumWage", label: "Wage floor", value: 25, unit: "wage index", sourceType: "calibrated", note: "A classroom floor near the equilibrium threshold." }, { key: "workerSupport", label: "Worker support", value: 0, unit: "index", sourceType: "indexed", note: "A targeted complementary-transfer proxy." }],
    predictionQuestions: [{ id: "employment", prompt: "In the competitive proxy, which side constrains jobs when the floor binds?", type: "choice", options: ["Labour demanded", "Labour supplied", "Neither"], required: true }, { id: "limitation", prompt: "State one reason this proxy may differ from a local labour market.", type: "text", required: true }],
    availablePolicies: [calibrated("minimumWage", "Statutory wage floor", 25, 10, 50, 1, " wage index", "A labour-market price-floor proxy."), calibrated("workerSupport", "Targeted worker support", 0, 0, 20, 1, " index", "A tax-credit / transfer proxy."), calibrated("training", "Training support", 0, 0, 25, 1, " index", "A long-run employability proxy.")],
    constraints: [{ label: "Interpretation", rule: "Do not label the simple surplus as measured unemployment.", explanation: "Hours, participation, and search are not modelled." }, { label: "Fiscal", rule: "Worker and training support use public funds.", explanation: "Costs are not market wage payments." }],
    outputMetrics: [{ key: "employment", label: "Jobs traded", unit: "labour units", meaning: "Demanded labour in a binding-floor proxy." }, { key: "surplus", label: "Excess labour supply", unit: "labour units", meaning: "A potential labour-market mismatch, not an observed unemployment rate." }, { key: "earnings", label: "Worker earnings index", unit: "index", meaning: "Simplified wage times jobs measure." }],
    stakeholderGroups: [{ name: "Employed low-wage workers", note: "Can receive a higher floor wage." }, { name: "Job seekers", note: "May face fewer vacancies in this proxy." }, { name: "Small employers", note: "Face higher labour costs." }], reflectionQuestions: ["What data identify employer market power?", "How could hours adjust even if headcount does not?"], evidenceSources: [official("ILO Minimum Wages", "https://www.ilo.org/topics-and-sectors/wages-and-working-time/minimum-wages", "Official labour-policy context."), official("OECD Employment", "https://www.oecd.org/en/topics/employment.html", "Public labour-market context.")],
  },
  {
    id: "tariff-conflict", slug: "tariff-conflict", title: "Tariff Conflict", subtitle: "Assess consumer prices, domestic firms, revenue, retaliation, and the limits of a one-country policy lever.", status: "published", featured: false, category: "trade", difficulty: "Advanced", estimatedMinutes: 24, simulationAdapterKey: "tariff-conflict", evaluationConfig: commonEvaluation,
    realWorldContext: { overview: "A government considers a tariff after an external trade dispute. Domestic producers seek protection while import users face price and variety effects.", location: "Small importing economy (stylised)", actors: ["Consumers", "Domestic producers", "Importing firms", "Trade partners"], decision: "Set a tariff and domestic-transition support, while making retaliation risk explicit.", significance: "Trade barriers redistribute gains and can prompt strategic responses.", facts: ["Tariffs can raise customs revenue but also change domestic prices and sourcing.", "Retaliation and supply chains matter."], assumptions: ["The Sandbox uses indexed indicators, not a partial-equilibrium customs estimate."] },
    economicProblem: { primaryOptions: ["Trade restriction with distributional trade-off", "Pure public good", "Positive externality", "Rent ceiling"], secondaryOptions: ["Retaliation risk", "No partner response"], correctPrimary: "Trade restriction with distributional trade-off", correctSecondary: ["Retaliation risk"], reveal: "A tariff can protect domestic activity in the short run while reducing consumer welfare and risking a partner response." },
    modelMappings: [{ model: "Economic Sandbox / Game Theory", route: "/sandbox", realWorldEvent: "Import tariff", mechanism: "Higher border cost changes imports and domestic incentives", modelVariable: "Tariff rate", response: "Consumer welfare, firm profits, revenue, and output move through transparent Sandbox rules", expectedOutcome: "Mixed domestic effects and potential retaliation", selectedReason: "It prevents treating tariff revenue as a free gain.", omittedVariables: ["Product variety", "Exchange rate", "Partner-specific elasticities"], alternatives: ["Prisoner’s Dilemma for strategic escalation"], limitation: "No bilateral trade-flow forecast is produced." }],
    initialConditions: [{ key: "tariffRate", label: "Tariff rate", value: 10, unit: "%", sourceType: "indexed", note: "Classroom starting point." }, { key: "retaliation", label: "Retaliation intensity", value: 20, unit: "%", sourceType: "calibrated", note: "Stylised partner-response probability/intensity." }],
    predictionQuestions: [{ id: "consumer", prompt: "Which domestic group is most likely to face the immediate cost of a tariff?", type: "choice", options: ["Consumers and import-using firms", "Only the foreign government", "No one until retaliation"], required: true }, { id: "strategy", prompt: "What partner response should be considered?", type: "text", required: true }],
    availablePolicies: [calibrated("tariffRate", "Import tariff", 10, 0, 60, 1, "%", "A standardised border charge."), calibrated("domesticSubsidy", "Domestic transition support", 0, 0, 30, 1, " index", "A limited production-support proxy."), calibrated("retaliation", "Expected retaliation intensity", 20, 0, 100, 5, "%", "A transparent risk calibration.")],
    constraints: [{ label: "Retaliation", rule: "A higher tariff can increase expected partner response.", explanation: "The risk is an assumption, not a prediction." }, { label: "Consumer cost", rule: "Revenue is not a net welfare measure.", explanation: "The Sandbox reports multiple indicators." }],
    outputMetrics: [{ key: "consumerWelfare", label: "Consumer welfare", unit: "index", meaning: "Sandbox indicator, not household income." }, { key: "firmProfit", label: "Firm profit", unit: "index", meaning: "Sandbox domestic-firm indicator." }, { key: "revenue", label: "Government revenue", unit: "index", meaning: "Sandbox fiscal indicator." }],
    stakeholderGroups: [{ name: "Consumers", note: "Can face higher prices or fewer choices." }, { name: "Protected domestic firms", note: "May gain short-run protection." }, { name: "Exporters", note: "Can be exposed to retaliation." }], reflectionQuestions: ["What import-share and product-substitution data are missing?", "How would a negotiated outcome change the comparison?"], evidenceSources: [official("WTO Tariffs", "https://www.wto.org/english/tratop_e/tariffs_e/tariffs_e.htm", "Official trade-policy context."), official("World Bank Trade", "https://www.worldbank.org/en/topic/trade", "Public trade context.")],
  },
  {
    id: "restaurant-food-waste", slug: "restaurant-food-waste", title: "Restaurant Food Waste", subtitle: "Use a newsvendor-style inventory decision to balance waste, stockouts, customer experience, and insurance.", status: "published", featured: true, category: "business-decision", difficulty: "Intermediate", estimatedMinutes: 25, simulationAdapterKey: "restaurant-food-waste", evaluationConfig: commonEvaluation,
    realWorldContext: { overview: "An anonymised restaurant group prepares a perishable signature dish. Demand fluctuates, waste has disposal costs, and stockouts damage customer experience. No private restaurant data are used.", location: "Restaurant operation (stylised, anonymised)", actors: ["Restaurant manager", "Kitchen team", "Customers", "Insurer / waste partner"], decision: "Choose inventory, forecasting, freshness, and risk-management settings.", significance: "Food service waste is a material operational and environmental issue.", facts: ["Food service is one of the sectors measured in global food-waste work.", "Perishable inventory creates a stockout–waste trade-off."], assumptions: ["Demand is normally approximated; insurance is a simplified eligible-loss cover, not a quotation."] },
    economicProblem: { primaryOptions: ["Perishable inventory / newsvendor trade-off", "Price ceiling", "Public good", "Tariff escalation"], secondaryOptions: ["Overage and underage costs", "No uncertainty"], correctPrimary: "Perishable inventory / newsvendor trade-off", correctSecondary: ["Overage and underage costs"], reveal: "Ordering more reduces expected stockouts but raises expected unsold perishable inventory; the best choice depends on both costs." },
    modelMappings: [{ model: "Perishable inventory engine", route: "/cases/restaurant-food-waste", realWorldEvent: "Daily food preparation under uncertain demand", mechanism: "Expected sales are bounded by inventory and demand", modelVariable: "Order quantity, forecast accuracy, and cost parameters", response: "Expected waste and shortage change together", expectedOutcome: "A transparent service–waste–profit trade-off", selectedReason: "The dedicated engine is more appropriate than a market-price chart.", omittedVariables: ["Menu substitution", "Multi-day carryover", "Staff constraints", "Actual insurance contract terms"], alternatives: ["Externalities for disposal impacts"], limitation: "It produces expected values, not a guarantee for a single service." }],
    initialConditions: [{ key: "expectedDemand", label: "Expected daily demand", value: DEFAULT_FOOD_WASTE.expectedDemand, unit: "meals", sourceType: "calibrated", note: "Anonymised classroom starting value." }, { key: "inventoryLevel", label: "Initial inventory", value: DEFAULT_FOOD_WASTE.inventoryLevel, unit: "meals", sourceType: "calibrated", note: "Rounded to the minimum order quantity." }],
    predictionQuestions: [{ id: "inventory", prompt: "If you increase inventory with demand fixed, what trade-off should you expect?", type: "choice", options: ["Less shortage but more expected waste", "Less shortage and less waste always", "No change"], required: true }, { id: "data", prompt: "What operational data would improve the forecast?", type: "text", required: true }],
    availablePolicies: [
      calibrated("expectedDemand", "Expected demand", DEFAULT_FOOD_WASTE.expectedDemand, 20, 300, 5, " meals", "Forecast demand before acceptance adjustments."), calibrated("demandVolatility", "Demand volatility", DEFAULT_FOOD_WASTE.demandVolatility, 2, 80, 1, " meals", "Demand standard-deviation proxy."), calibrated("forecastAccuracy", "Forecast accuracy", DEFAULT_FOOD_WASTE.forecastAccuracy, 0, 100, 1, "%", "Reduces effective forecast uncertainty in the teaching model."), calibrated("inventoryLevel", "Prepared inventory", DEFAULT_FOOD_WASTE.inventoryLevel, 20, 350, 5, " meals", "Target preparation quantity before MOQ rounding."), calibrated("minimumOrderQuantity", "Minimum order quantity", DEFAULT_FOOD_WASTE.minimumOrderQuantity, 1, 50, 1, " meals", "Supplier batch constraint."), calibrated("replenishmentFlexibility", "Same-day replenishment flexibility", DEFAULT_FOOD_WASTE.replenishmentFlexibility, 0, 100, 5, "%", "Ability to adjust toward forecast demand."), calibrated("sellingPrice", "Selling price", DEFAULT_FOOD_WASTE.sellingPrice, 1, 50, 0.5, " currency", "Per-meal revenue."), calibrated("productionCost", "Production cost", DEFAULT_FOOD_WASTE.productionCost, 0.5, 30, 0.5, " currency", "Per prepared meal."), calibrated("disposalCost", "Disposal cost", DEFAULT_FOOD_WASTE.disposalCost, 0, 10, 0.1, " currency", "Per wasted meal."), calibrated("shortageCost", "Stockout cost", DEFAULT_FOOD_WASTE.shortageCost, 0, 20, 0.5, " currency", "Lost contribution / operational shortage proxy."), calibrated("customerComplaintCost", "Customer-experience cost", DEFAULT_FOOD_WASTE.customerComplaintCost, 0, 10, 0.1, " currency", "Per unmet expected meal, stylised."), calibrated("insuranceCoverage", "Eligible-loss insurance cover", DEFAULT_FOOD_WASTE.insuranceCoverage, 0, 100, 5, "%", "Simplified coverage share."), calibrated("insurancePremiumRate", "Insurance premium rate", DEFAULT_FOOD_WASTE.insurancePremiumRate, 0, 20, 0.5, "%", "Rate applied to a defined simplified cost base."), calibrated("claimThreshold", "Insurance claim threshold", DEFAULT_FOOD_WASTE.claimThreshold, 0, 500, 10, " currency", "Losses above this amount may be covered."), calibrated("freshnessVerification", "Freshness verification", DEFAULT_FOOD_WASTE.freshnessVerification, 0, 100, 5, "%", "A transparent quality-control index."), calibrated("transparency", "Waste-process transparency", DEFAULT_FOOD_WASTE.transparency, 0, 100, 5, "%", "A communication and traceability proxy."), calibrated("consumerAcceptance", "Base customer acceptance", DEFAULT_FOOD_WASTE.consumerAcceptance, 40, 100, 1, "%", "Demand acceptance before quality measures.")],
    constraints: [{ label: "Perishability", rule: "Unsold meals cannot be carried over in the engine.", explanation: "This intentionally makes over-ordering costly." }, { label: "Insurance", rule: "Claims only cover modelled eligible losses above the threshold.", explanation: "It is not a real-policy quote or legal interpretation." }, { label: "Data integrity", rule: "Restaurant values are anonymised and stylised.", explanation: "The system must not imply access to private data." }],
    outputMetrics: [{ key: "waste", label: "Expected food waste", unit: "meals", meaning: "Expected unsold prepared meals." }, { key: "shortage", label: "Expected shortage", unit: "meals", meaning: "Expected unmet demand." }, { key: "profit", label: "Expected profit", unit: "currency", meaning: "Expected revenue less modelled costs and plus eligible claim." }, { key: "risk", label: "Operational risk", unit: "/100", meaning: "Transparent composite teaching indicator." }],
    stakeholderGroups: [{ name: "Restaurant manager", note: "Balances expected profit and operational risk." }, { name: "Customers", note: "Experience availability and quality." }, { name: "Kitchen team", note: "Faces production and waste-management burden." }, { name: "Waste partner / local environment", note: "Affected by avoidable disposal." }], reflectionQuestions: ["Which demand data would reduce uncertainty most?", "How would donation, dynamic pricing, or multi-period storage change the model?"], evidenceSources: [official("UNEP Food Waste Index Report 2024", "https://www.unep.org/resources/publication/food-waste-index-report-2024", "Official global food-waste measurement context."), official("WRAP Hospitality and Food Service", "https://wrap.org.uk/taking-action/food-drink/sector/hospitality-and-food-service", "Public operational-waste context.")],
  },
];

export const CASE_BY_SLUG = Object.fromEntries(ECONOMIC_CASES.map((item) => [item.slug, item])) as Record<string, EconomicCaseDefinition>;
export const CASE_STAGES = ["context", "problem", "mapping", "conditions", "prediction", "simulation", "comparison", "evaluation", "recommendation", "reflection"] as const;
