"use client";

import { useState } from "react";
import { ExternalLink, FileLock2, FlaskConical } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { FINAL_WORLD_TEACHING, asArray, asRecord } from "@/lib/economics/final-world-teaching/catalog";

type EvidenceProject = { project_id: string; title: string; status: string; source_data: { primary?: { url?: string; publisher?: string; coverage?: string; licence_or_access?: string }; secondary?: { url?: string; publisher?: string; coverage?: string; licence_or_access?: string } }; teaching_sample: { path: string; status: string; reason: string }; sample_period: string; variables: [string, string, string][]; cleaning: string[]; formulae: Record<string, string>; expected_result: string; chart_suggestions: string[]; causal_limit: string };
const projects = asArray<EvidenceProject>(asRecord(FINAL_WORLD_TEACHING.evidenceLabProjects).projects);

export function EvidenceLab() {
  const [activeId, setActiveId] = useState(projects[0]?.project_id ?? ""); const active = projects.find((project) => project.project_id === activeId) ?? projects[0];
  if (!active) return null;
  return <main className="min-h-[calc(100vh-4rem)] p-5 sm:p-8 lg:p-10"><div className="max-w-4xl"><p className="text-[10px] font-extrabold uppercase tracking-[.18em] text-[var(--accent)]">Learning & research · curated only</p><h1 className="mt-3 text-4xl font-bold tracking-[-.05em] sm:text-5xl">Evidence Lab</h1><p className="mt-4 max-w-3xl text-sm leading-6 text-[var(--ink-muted)]">Three transparent, read-only evidence exercises. Each separates a reproducible teaching calculation from real-world evidence and states the boundary of its causal claim.</p></div>
    <div className="mt-7 rounded-xl border border-[var(--amber)] bg-[var(--amber-soft)] p-4 text-sm text-[var(--ink-muted)]"><p className="flex items-center gap-2 font-bold text-[var(--ink)]"><FileLock2 size={17} />Read-only in this release</p><p className="mt-1 leading-6">Evidence uploads are intentionally unavailable. Use the fixed teaching samples and source links below; this keeps data use reviewable and avoids collecting student research data.</p></div>
    <div className="mt-7 grid gap-6 xl:grid-cols-[260px_minmax(0,1fr)]"><aside className="rounded-xl border border-[var(--line)] bg-[var(--surface)] p-3 xl:self-start"><p className="px-2 pb-2 text-[10px] font-bold uppercase tracking-wider text-[var(--ink-faint)]">Curated projects</p>{projects.map((project) => <button key={project.project_id} type="button" onClick={() => setActiveId(project.project_id)} className={`block w-full rounded-lg px-3 py-3 text-left text-sm font-semibold ${project.project_id === active.project_id ? "bg-[var(--accent-soft)] text-[var(--accent)]" : "text-[var(--ink-muted)] hover:bg-[var(--surface-subtle)]"}`}><span className="block text-[10px] uppercase tracking-wider opacity-70">{project.project_id}</span><span className="mt-1 block">{project.title}</span></button>)}</aside>
      <section className="min-w-0 rounded-xl border border-[var(--line)] bg-[var(--surface)] p-5 sm:p-7"><div className="flex flex-wrap gap-2"><Badge className="bg-[var(--accent-soft)] text-[var(--accent)]">{active.project_id}</Badge><Badge>{active.status.replaceAll("_", " ")}</Badge></div><h2 className="mt-4 text-2xl font-bold tracking-[-.035em]">{active.title}</h2><p className="mt-3 text-sm text-[var(--ink-muted)]">Teaching sample: <code className="rounded bg-[var(--surface-subtle)] px-1.5 py-1 text-xs">{active.teaching_sample.path}</code></p>
        <section className="mt-7 grid gap-4 md:grid-cols-2"><SourceCard heading="Primary source" source={active.source_data.primary} /><SourceCard heading="Context source" source={active.source_data.secondary} /></section>
        <section className="mt-7 rounded-lg bg-[var(--surface-subtle)] p-5"><p className="flex items-center gap-2 text-sm font-bold"><FlaskConical size={17} className="text-[var(--accent)]" />Teaching sample and method</p><p className="mt-3 text-sm leading-6 text-[var(--ink-muted)]">{active.teaching_sample.reason}</p><p className="mt-2 text-xs text-[var(--ink-faint)]">Period: {active.sample_period}</p><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[500px] text-left text-xs"><thead className="border-b border-[var(--line)] text-[10px] uppercase tracking-wider text-[var(--ink-faint)]"><tr><th className="pb-2">Variable</th><th className="pb-2">Definition</th><th className="pb-2">Unit</th></tr></thead><tbody>{active.variables.map(([name, definition, unit]) => <tr key={name} className="border-b border-[var(--line)] last:border-0"><td className="py-2 font-semibold">{name}</td><td className="py-2 text-[var(--ink-muted)]">{definition}</td><td className="py-2 text-[var(--ink-muted)]">{unit}</td></tr>)}</tbody></table></div></section>
        <section className="mt-7 grid gap-4 md:grid-cols-2"><Panel title="Cleaning steps" lines={active.cleaning} /><Panel title="Suggested visual checks" lines={active.chart_suggestions} /></section>
        <section className="mt-7"><p className="text-xs font-bold uppercase tracking-wider text-[var(--ink-faint)]">Formulae</p><div className="mt-3 space-y-2">{Object.entries(active.formulae).map(([name, formula]) => <div key={name} className="rounded-lg border border-[var(--line)] p-4"><p className="text-xs font-bold">{name}</p><code className="mt-2 block overflow-x-auto text-xs leading-6 text-[var(--ink-muted)]">{formula}</code></div>)}</div></section>
        <section className="mt-7 rounded-lg border border-[var(--accent)] bg-[var(--accent-soft)] p-5"><p className="text-sm font-bold text-[var(--accent)]">Expected calculation result</p><p className="mt-2 text-sm leading-6 text-[var(--ink-muted)]">{active.expected_result}</p><p className="mt-4 border-t border-[var(--line)] pt-4 text-xs leading-5 text-[var(--red)]"><span className="font-bold">Causal limit:</span> {active.causal_limit}</p></section>
      </section></div></main>;
}

function SourceCard({ heading, source }: { heading: string; source: EvidenceProject["source_data"]["primary"] }) { if (!source) return <div className="rounded-lg bg-[var(--surface-subtle)] p-4"><p className="text-xs font-bold">{heading}</p><p className="mt-2 text-xs text-[var(--ink-faint)]">Not required for this exercise.</p></div>; return <div className="rounded-lg bg-[var(--surface-subtle)] p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-[var(--ink-faint)]">{heading}</p><p className="mt-2 text-sm font-bold">{source.publisher}</p><p className="mt-2 text-xs leading-5 text-[var(--ink-muted)]">{source.coverage}</p>{source.url && <a className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-[var(--accent)]" href={source.url} target="_blank" rel="noreferrer">Open source <ExternalLink size={12} /></a>}<p className="mt-3 text-[10px] leading-4 text-[var(--ink-faint)]">{source.licence_or_access}</p></div>; }
function Panel({ title, lines }: { title: string; lines: string[] }) { return <div className="rounded-lg border border-[var(--line)] p-4"><p className="text-xs font-bold">{title}</p><ul className="mt-3 space-y-2 text-xs leading-5 text-[var(--ink-muted)]">{lines.map((line) => <li key={line}>• {line}</li>)}</ul></div>; }
