"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowRight, CheckCircle2, CloudUpload, Plus, Trash2 } from "lucide-react";
import { useAuth } from "@/components/auth/auth-provider";
import { Button } from "@/components/ui/button";
import { MODEL_REGISTRY } from "@/lib/models/registry";
import { listReusableModelCompositions, publishModelComposition, saveModelComposition, type ModelComposition } from "@/lib/supabase/model-composer";

const models = MODEL_REGISTRY.filter((model) => model.status === "available");
const titleFor = (slug: string) => models.find((model) => model.slug === slug)?.title ?? slug.replaceAll("-", " ");

export function ModelComposer() {
  const { role } = useAuth(); const [chain, setChain] = useState<string[]>([models[0]?.slug ?? "", models[1]?.slug ?? ""]); const [title, setTitle] = useState("Untitled model chain"); const [reusable, setReusable] = useState<ModelComposition[]>([]); const [saved, setSaved] = useState<ModelComposition | null>(null); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const links = useMemo(() => chain.slice(0, -1).map((from, index) => ({ from, to: chain[index + 1], relation: "feeds output into next model" })), [chain]);
  useEffect(() => { void listReusableModelCompositions().then(setReusable).catch(() => setReusable([])); }, []);
  const updateItem = (index: number, value: string) => setChain((current) => current.map((item, itemIndex) => itemIndex === index ? value : item));
  const save = async () => { setBusy(true); setMessage(null); try { const record = await saveModelComposition({ title, modelChain: chain, links }); setSaved(record); setMessage("Private draft saved. It does not affect any shared model or the World Economy."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not save this composition."); } finally { setBusy(false); } };
  const publish = async () => { if (!saved) return; setBusy(true); setMessage(null); try { const record = await publishModelComposition(saved.id); setSaved(record); setReusable((current) => [record, ...current.filter((item) => item.id !== record.id)]); setMessage("Published for registered learners to reuse."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not publish this composition."); } finally { setBusy(false); } };
  return <main className="min-h-[calc(100vh-4rem)] p-5 sm:p-8 lg:p-10"><div className="max-w-4xl"><p className="text-[10px] font-extrabold uppercase tracking-[.18em] text-[var(--accent)]">Model learning system · structured composition</p><h1 className="mt-3 text-4xl font-bold tracking-[-.05em] sm:text-5xl">Model Composer</h1><p className="mt-4 max-w-3xl text-sm leading-6 text-[var(--ink-muted)]">Build a two-to-four-model reasoning chain from existing models. Composer explains connections and assumptions; it never rewrites a model, creates an unvalidated formula, or changes the live World Economy.</p></div>
    <div className="mt-8 grid gap-6 xl:grid-cols-[minmax(0,1fr)_300px]"><section className="rounded-xl border border-[var(--line)] bg-[var(--surface)] p-5 sm:p-7"><label className="block max-w-xl text-xs font-bold text-[var(--ink-muted)]">Composition title<input value={title} maxLength={120} onChange={(event) => setTitle(event.target.value)} className="mt-2 h-10 w-full rounded-lg border border-[var(--line)] bg-[var(--canvas)] px-3 text-sm text-[var(--ink)] outline-none focus:border-[var(--accent)]" /></label><div className="mt-8"><p className="text-xs font-bold uppercase tracking-wider text-[var(--ink-faint)]">Model chain</p><div className="mt-4 space-y-3">{chain.map((slug, index) => <div key={`${index}-${slug}`}><div className="flex items-center gap-3"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-[var(--accent-soft)] text-xs font-bold text-[var(--accent)]">{index + 1}</span><select value={slug} onChange={(event) => updateItem(index, event.target.value)} className="h-11 min-w-0 flex-1 rounded-lg border border-[var(--line)] bg-[var(--canvas)] px-3 text-sm font-semibold text-[var(--ink)]">{models.map((model) => <option key={model.slug} value={model.slug}>{model.title}</option>)}</select>{chain.length > 2 && <button type="button" aria-label="Remove model" onClick={() => setChain((current) => current.filter((_, itemIndex) => itemIndex !== index))} className="grid size-9 place-items-center rounded-lg text-[var(--red)] hover:bg-[var(--red-soft)]"><Trash2 size={16} /></button>}</div>{index < chain.length - 1 && <div className="ml-3.5 flex h-7 items-center border-l border-dashed border-[var(--accent)] pl-5 text-[10px] text-[var(--ink-faint)]"><ArrowRight size={13} className="mr-2 text-[var(--accent)]" />Feeds output into the next model</div>}</div>)}</div>{chain.length < 4 && <button type="button" onClick={() => setChain((current) => [...current, models.find((model) => !current.includes(model.slug))?.slug ?? models[0].slug])} className="mt-4 inline-flex items-center gap-2 text-xs font-bold text-[var(--accent)]"><Plus size={15} />Add another model</button>}</div>
      <section className="mt-8 rounded-lg bg-[var(--surface-subtle)] p-5"><p className="text-sm font-bold">Composer checks before you use the chain</p><ul className="mt-3 space-y-2 text-xs leading-5 text-[var(--ink-muted)]"><li>• Inputs and outputs must use compatible units and time bases.</li><li>• Shared assumptions must not contradict each other (for example, partial equilibrium versus endogenous feedback).</li><li>• A chain is descriptive only unless it declares a causal design and evidence source.</li><li>• Circular feedback is shown as a limitation, not silently calculated.</li></ul></section>
      <div className="mt-6 flex flex-wrap gap-3"><Button onClick={save} disabled={busy || title.trim().length < 2}><CloudUpload size={15} />Save private draft</Button>{role === "teacher" && saved?.status === "draft" && <Button variant="secondary" onClick={publish} disabled={busy}><CheckCircle2 size={15} />Publish for reuse</Button>}</div>{role !== "teacher" && <p className="mt-3 text-xs text-[var(--ink-faint)]">Teachers and platform administrators can publish their own saved chains. All registered users can compose and save private drafts.</p>}{message && <p className={`mt-4 rounded-lg p-3 text-sm ${message.startsWith("Could") ? "bg-[var(--red-soft)] text-[var(--red)]" : "bg-[var(--accent-soft)] text-[var(--accent)]"}`}>{message}</p>}</section>
      <aside className="rounded-xl border border-[var(--line)] bg-[var(--surface)] p-5 xl:self-start"><p className="text-[10px] font-bold uppercase tracking-wider text-[var(--ink-faint)]">Published reusable chains</p><div className="mt-4 space-y-3">{reusable.length ? reusable.map((composition) => <article key={composition.id} className="rounded-lg bg-[var(--surface-subtle)] p-3"><p className="text-sm font-bold">{composition.title}</p><p className="mt-2 text-xs leading-5 text-[var(--ink-muted)]">{composition.model_chain.map(titleFor).join(" → ")}</p><button type="button" onClick={() => { setTitle(composition.title); setChain(composition.model_chain); setMessage("Loaded a published chain into your private workspace."); }} className="mt-3 text-xs font-bold text-[var(--accent)]">Reuse this structure</button></article>) : <p className="rounded-lg bg-[var(--surface-subtle)] p-3 text-xs leading-5 text-[var(--ink-muted)]">No published chains yet. Teacher-published examples will appear here after review.</p>}</div></aside></div></main>;
}
