"use client";

import Link from "next/link";
import { ArrowDown, ArrowUpRight, Network } from "lucide-react";
import { ExpandableAnalysisPanel } from "@/components/models/expandable-analysis-panel";
import { CROSS_MODEL_MAPPINGS, type MacroWorkspaceState, calculateMacroTransmission, normalisedIndex } from "@/lib/models/model-mapping";

const f = (value: number) => new Intl.NumberFormat("en-US", { maximumFractionDigits: 2 }).format(value);

export function CrossModelTransmissionView({ state, modelLabel = "Inflation Crisis" }: { state: MacroWorkspaceState; modelLabel?: string }) {
  const t = calculateMacroTransmission(state);
  const baseline = calculateMacroTransmission({ governmentSpending: 100, taxLevel: 25, moneySupplyGrowth: 3, policyRate: 4, expectedInflation: 2, supplyShock: 0 });
  const stages = [
    { name: "Policy controls", route: "/policy-lab", input: `G index ${f(state.governmentSpending)} · tax ${f(state.taxLevel)}% · money growth ${f(state.moneySupplyGrowth)}% · policy rate ${f(state.policyRate)}%`, output: "Shared macro-policy inputs", mapped: "Native controls; no numerical merge.", mechanism: "Fiscal and monetary settings are translated once through the visible Sandbox-to-IS–LM assumptions.", assumption: CROSS_MODEL_MAPPINGS[0].assumptionLabel, limitation: "Controls are educational indices and rates, not a national policy database." },
    { name: "IS–LM", route: "/models/is-lm", input: `G = ${f(t.islmParameters.governmentSpending)} · T = ${f(t.islmParameters.taxation)} · M = ${f(t.islmParameters.moneySupply)}`, output: `Y = ${f(t.islm.output)} model units · i = ${f(t.islm.interestRate)}`, mapped: `Output normalised to ${f(normalisedIndex(t.islm.output, baseline.islm.output))} (baseline = 100)`, mechanism: "The IS and LM relationships clear jointly; fiscal demand can raise output and interest rates while monetary conditions move real balances.", assumption: CROSS_MODEL_MAPPINGS[2].assumptionLabel, limitation: CROSS_MODEL_MAPPINGS[2].limitation },
    { name: "AD–AS", route: "/models/ad-as", input: `Mapped ΔAD = ${f(t.adasParameters.demandShock)} · supply shock = ${f(t.adasParameters.supplyShock)}`, output: `Output = ${f(t.adas.output)} index · price level = ${f(t.adas.priceLevel)}`, mapped: `Output normalised to ${f(normalisedIndex(t.adas.output, baseline.adas.output))}; native output index retained`, mechanism: "The mapped demand effect shifts AD while the selected supply shock shifts SRAS, producing a separate short-run output and price result.", assumption: CROSS_MODEL_MAPPINGS[2].assumptionLabel, limitation: "AD–AS output is an index, not the IS–LM model-unit level." },
    { name: "Phillips Curve", route: "/models/phillips-curve", input: `Mapped unemployment = ${f(t.phillipsParameters.unemployment)}% · expected inflation = ${f(t.phillipsParameters.expectedInflation)}%`, output: `Inflation = ${f(t.phillips.inflation)}% · unemployment gap = ${f(t.phillips.unemploymentGap)}pp`, mapped: `Inflation change ${f(t.phillips.inflation - baseline.phillips.inflation)} percentage points`, mechanism: "The AD–AS output gap maps through the displayed Okun-style relationship to a point on a short-run Phillips curve.", assumption: CROSS_MODEL_MAPPINGS[3].assumptionLabel, limitation: "The inflation estimate is conditional on an explicitly stylised curve, not a forecast." },
  ];
  return <ExpandableAnalysisPanel title="Cross-model transmission" modelLabel={modelLabel} subtitle="Native units stay visible. Links are stylised educational mappings, not empirical forecasts.">
    <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.12em] text-[var(--accent)]"><Network size={16} /><span>Inflation-crisis transmission sequence</span></div>
    <p className="mt-3 rounded-lg border border-[var(--amber)] bg-[var(--amber-soft)] p-3 text-xs leading-5 text-[var(--amber)]">Cross-model links are stylised educational mappings. They illustrate economic transmission mechanisms and are not empirical forecasts.</p>
    <ol className="mt-5 space-y-3">{stages.map((stage, index) => <li key={stage.name}>{index > 0 && <ArrowDown className="mx-auto my-2 text-[var(--accent)]" size={18} />}<section className="rounded-xl border border-[var(--line)] bg-[var(--canvas)] p-4 sm:p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><p className="text-[10px] font-extrabold uppercase tracking-wider text-[var(--accent)]">{index + 1}. {stage.name}</p><p className="mt-2 text-sm font-bold">{stage.output}</p></div><Link href={stage.route} className="inline-flex items-center gap-1 rounded-md border border-[var(--line-strong)] bg-[var(--surface)] px-2.5 py-1.5 text-xs font-bold hover:border-[var(--accent)]">Open model <ArrowUpRight size={13} /></Link></div><div className="mt-4 grid gap-3 text-xs leading-5 md:grid-cols-2"><p><strong>Input:</strong> {stage.input}</p><p><strong>Mapped / normalised:</strong> {stage.mapped}</p><p><strong>Mechanism:</strong> {stage.mechanism}</p><p><strong>Assumption:</strong> {stage.assumption}<br /><span className="text-[var(--ink-faint)]">Limitation: {stage.limitation}</span></p></div></section></li>)}</ol>
  </ExpandableAnalysisPanel>;
}
