"use client";

import { useState } from "react";
import { CheckCircle2, Target } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { SandboxParameters } from "@/lib/economics/sandbox/types";

type Focus = "inflation" | "carbon" | "climate";
const briefs: Record<Focus, { title: string; objective: string; parameters: Partial<SandboxParameters>; priorities: string[] }> = {
  inflation: { title: "Inflation Crisis", objective: "Reduce inflation while limiting output and employment losses.", parameters: { interestRate: 6, moneySupplyGrowth: 6, governmentSpending: 112, incomeTaxRate: 25 }, priorities: ["Price stability", "Employment", "Growth"] },
  carbon: { title: "Carbon Transition", objective: "Reduce emissions without ignoring welfare, profitability or fiscal capacity.", parameters: { carbonTax: 40, greenSubsidy: 12, subsidyRate: 5, governmentSpending: 104 }, priorities: ["Emissions", "Consumer welfare", "Growth"] },
  climate: { title: "Climate Cooperation", objective: "Create incentives for durable cooperation while protecting domestic welfare.", parameters: { carbonTax: 30, greenSubsidy: 20, governmentSpending: 105, subsidyRate: 7 }, priorities: ["Cooperation", "Emissions", "Consumer welfare"] },
};

export function PersonalPolicyLab({ onApply }: { onApply: (parameters: Partial<SandboxParameters>) => void }) {
  const [focus, setFocus] = useState<Focus>("inflation"); const [priority, setPriority] = useState(briefs.inflation.priorities[0]); const [prediction, setPrediction] = useState(""); const [locked, setLocked] = useState(""); const brief = briefs[focus];
  function choose(next: Focus) { setFocus(next); setPriority(briefs[next].priorities[0]); setPrediction(""); setLocked(""); onApply(briefs[next].parameters); }
  return <section className="mx-auto max-w-[1500px] px-4 pt-5 sm:px-6 lg:px-8"><div className="rounded-xl border border-[var(--line)] bg-[var(--surface)] p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-extrabold uppercase tracking-[.16em] text-[var(--accent)]">Integrated Policy Lab</p><h2 className="mt-2 text-xl font-bold">Choose a brief, state a priority, then test the package live.</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--ink-muted)]">This guided layer now shares the Economic Sandbox controls and calculation engine instead of maintaining a separate policy simulator.</p></div><span className="grid size-10 place-items-center rounded-lg bg-[var(--accent-soft)] text-[var(--accent)]"><Target size={18} /></span></div><div className="mt-5 grid gap-3 md:grid-cols-3">{(Object.keys(briefs) as Focus[]).map((key) => <button key={key} type="button" onClick={() => choose(key)} className={`rounded-lg border p-4 text-left ${focus === key ? "border-[var(--accent)] bg-[var(--accent-soft)]" : "border-[var(--line)] hover:bg-[var(--surface-subtle)]"}`}><p className="text-sm font-bold">{briefs[key].title}</p><p className="mt-2 text-xs leading-5 text-[var(--ink-muted)]">{briefs[key].objective}</p></button>)}</div><div className="mt-5 grid gap-4 lg:grid-cols-[1.4fr_.7fr_1fr]"><div className="rounded-lg bg-[var(--canvas)] p-4"><p className="text-xs font-bold">Current brief: {brief.title}</p><p className="mt-2 text-xs leading-5 text-[var(--ink-muted)]">{brief.objective}</p></div><label className="text-xs font-bold">Priority<select value={priority} onChange={(event) => setPriority(event.target.value)} className="mt-2 h-10 w-full rounded-lg border border-[var(--line)] bg-[var(--canvas)] px-2 text-sm font-normal">{brief.priorities.map((item) => <option key={item}>{item}</option>)}</select></label><div><label className="text-xs font-bold">Prediction<input value={prediction} maxLength={220} onChange={(event) => { setPrediction(event.target.value); setLocked(""); }} placeholder="What do you expect, and why?" className="mt-2 h-10 w-full rounded-lg border border-[var(--line)] bg-[var(--canvas)] px-3 text-sm font-normal" /></label><Button size="sm" className="mt-2" disabled={!prediction.trim()} onClick={() => setLocked(prediction.trim())}>Lock prediction</Button>{locked && <p className="mt-2 flex gap-1 text-[10px] leading-5 text-[var(--accent)]"><CheckCircle2 size={12} />Recorded in this browser session.</p>}</div></div></div></section>;
}
