import { BookOpenCheck, Database, FlaskConical, Globe2, LineChart, ShieldCheck } from "lucide-react";

const features = [
  { icon: LineChart, title: "35 interactive economics models", text: "A focused library spanning market, macroeconomic, strategic, externality, development, and inequality reasoning. Calculations respond in the browser as parameters change." },
  { icon: FlaskConical, title: "Sandbox and policy exploration", text: "A browser-based Economic Sandbox and policy tools let learners test assumptions, compare effects, and inspect simplified predicted outcomes." },
  { icon: BookOpenCheck, title: "Cases, briefs, and practice", text: "Real-world teaching cases, curated Daily Briefs, model practice, EconBench workspaces, and Mechanism Arena scenarios connect concepts to structured questions." },
  { icon: Globe2, title: "Schools, teams, League, and Simulation", text: "The public League directory connects participating schools and teams. Authenticated learning workspaces support organised collaboration and a separate continuous simulation environment." },
  { icon: Database, title: "Saved work when you choose it", text: "Accounts can save model runs, learning progress, selected scenarios, challenge records, and other feature-specific work in Supabase." },
  { icon: ShieldCheck, title: "Private by default", text: "Supabase Auth and Row Level Security protect normal account data. Public school/team information is deliberately limited, and view-only invitations cannot make changes." },
] as const;

export default function AboutPage() {
  return (
    <main>
      <section className="border-b border-[var(--line)] bg-[var(--surface)]"><div className="mx-auto max-w-6xl px-5 py-20 sm:px-8 lg:py-28"><p className="text-[10px] font-extrabold uppercase tracking-[.2em] text-[var(--accent)]">About EconMind OS</p><h1 className="mt-4 max-w-5xl text-4xl font-bold tracking-[-.06em] sm:text-6xl">From real-world questions to disciplined economic reasoning.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-[var(--ink-muted)]">EconMind OS is a student-led educational platform for learning economics through interactive models, transparent assumptions, shared school activities, and evidence-aware reflection.</p></div></section>
      <section className="mx-auto max-w-6xl px-5 py-16 sm:px-8 lg:py-20"><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{features.map((feature) => { const Icon = feature.icon; return <article key={feature.title} className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-6 shadow-[var(--shadow)]"><span className="grid size-10 place-items-center rounded-lg bg-[var(--accent-soft)] text-[var(--accent)]"><Icon size={18} /></span><h2 className="mt-5 text-lg font-bold tracking-[-.025em]">{feature.title}</h2><p className="mt-3 text-sm leading-6 text-[var(--ink-muted)]">{feature.text}</p></article>; })}</div></section>
      <section className="border-y border-[var(--line)] bg-[var(--surface)]"><div className="mx-auto grid max-w-6xl gap-10 px-5 py-16 sm:px-8 lg:grid-cols-[1fr_1fr]"><div><p className="text-[10px] font-extrabold uppercase tracking-[.18em] text-[var(--accent)]">How the platform works</p><h2 className="mt-3 text-3xl font-bold tracking-[-.04em]">A model is a way to make assumptions visible.</h2></div><div className="space-y-4 text-sm leading-7 text-[var(--ink-muted)]"><p>Interactive calculations are designed to update as you work, rather than treating a model as a static answer. Each model is an educational simplification, with scope and assumptions that should be questioned alongside the result.</p><p>School, team, and challenge tools add a collaborative layer where a feature needs it. They do not turn model outputs into forecasts or professional advice, and they do not replace teachers&apos; or schools&apos; own learning safeguards.</p></div></div></section>
      <section className="mx-auto max-w-6xl px-5 py-16 sm:px-8 lg:py-20"><div className="max-w-3xl"><p className="text-[10px] font-extrabold uppercase tracking-[.18em] text-[var(--accent)]">Responsible use</p><h2 className="mt-3 text-3xl font-bold tracking-[-.04em]">Built for learning, not for claims of certainty.</h2><p className="mt-5 text-sm leading-7 text-[var(--ink-muted)]">EconMind OS is not a financial, legal, tax, investment, or policy advisory service. Its models, scenarios, and charts support discussion and learning; they do not predict outcomes or guarantee a decision. Read our <a href="/privacy" className="font-bold text-[var(--accent)]">Privacy Notice</a>, <a href="/terms" className="font-bold text-[var(--accent)]">Terms of Use</a>, and <a href="/integrity" className="font-bold text-[var(--accent)]">Integrity standard</a> for the rules that support the platform.</p></div></section>
    </main>
  );
}
