"use client";

import { useEffect, useState } from "react";
import { useAuth } from "@/components/auth/auth-provider";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { listEconomicCasesForAdmin, updateEconomicCaseStatus } from "@/lib/supabase/daily-brief";

type Row = Awaited<ReturnType<typeof listEconomicCasesForAdmin>>[number];
export function AdminCases() { const { user, role, roleLoading, openAuth } = useAuth(); const [rows, setRows] = useState<Row[]>([]); const [message, setMessage] = useState(""); const load = () => { void listEconomicCasesForAdmin().then(setRows).catch((caught) => setMessage(caught instanceof Error ? caught.message : "Could not load cases.")); }; useEffect(() => { if (user && role === "teacher") load(); }, [user, role]); if (!user && !roleLoading) return <main className="mx-auto grid min-h-[65vh] max-w-xl place-items-center px-5 text-center"><div><h1 className="text-3xl font-bold">Sign in as a teacher</h1><Button className="mt-5" onClick={() => openAuth("sign-in")}>Sign in</Button></div></main>; if (roleLoading) return <main className="mx-auto min-h-[60vh] max-w-5xl px-5 py-12"><p className="text-sm text-[var(--ink-muted)]">Checking access…</p></main>; if (role !== "teacher") return <main className="mx-auto grid min-h-[65vh] max-w-xl place-items-center px-5 text-center"><div><h1 className="text-3xl font-bold">Teacher access required</h1><p className="mt-3 text-sm text-[var(--ink-muted)]">You can browse published cases, but the database prevents non-teachers changing publication status.</p></div></main>; return <main className="mx-auto min-h-screen max-w-5xl px-5 py-12 sm:px-8"><header><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[var(--accent)]">Teacher administration</p><h1 className="mt-2 text-4xl font-bold">Cases</h1><p className="mt-3 text-sm text-[var(--ink-muted)]">The versioned application definitions remain the teaching source of truth in this first release. This table controls publication metadata and creates an audit point for future editable cases.</p></header>{message && <p className="mt-5 rounded-lg bg-[var(--accent-soft)] p-4 text-sm text-[var(--accent)]">{message}</p>}<div className="mt-8 space-y-3">{rows.map((row) => <Card key={row.id} className="flex flex-wrap items-center justify-between gap-4 p-5"><div><h2 className="text-lg font-bold">{row.title}</h2><p className="mt-1 text-xs text-[var(--ink-faint)]">{row.slug} · updated {new Date(row.updated_at).toLocaleString()}</p></div><select value={row.status} onChange={(event) => void updateEconomicCaseStatus(row.id, event.target.value as Row["status"]).then(load).catch((caught) => setMessage(caught instanceof Error ? caught.message : "Could not update case."))} className="h-10 rounded-lg border border-[var(--line)] bg-[var(--canvas)] px-3 text-sm"><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></Card>)}{rows.length === 0 && <Card className="p-10 text-center text-sm text-[var(--ink-muted)]">Run the Real-World Cases migration to seed the six case records.</Card>}</div></main>; }
