"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Check, ExternalLink, Save } from "lucide-react";
import { useAuth } from "@/components/auth/auth-provider";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { ExpandableAnalysisPanel } from "@/components/models/expandable-analysis-panel";
import { EquationView } from "@/components/models/equation-view";
import { MechanismChain } from "@/components/models/mechanism-chain";
import { StakeholderImpact } from "@/components/models/stakeholder-impact";
import { defaultCaseSettings, evaluateCase, runCaseSimulation } from "@/lib/cases/adapters";
import { CASE_STAGES } from "@/lib/cases/definitions";
import type { CaseRecommendation, CaseRunDraft, CaseScenarioName, CaseStage, EconomicCaseDefinition } from "@/lib/cases/types";
import { usePersistentState } from "@/lib/hooks/use-persistent-state";
import { saveCaseRun } from "@/lib/supabase/cases";

const stageLabels: Record<CaseStage, string> = { context: "Context", problem: "Problem", mapping: "Model mapping", conditions: "Conditions", prediction: "Prediction", simulation: "Simulation", comparison: "Comparison", evaluation: "Evaluation", recommendation: "Recommendation", reflection: "Reflection" };
const emptyRecommendation: CaseRecommendation = { selectedPolicy: "", mainBenefit: "", mainCost: "", affectedStakeholder: "", tradeOff: "", keyAssumption: "", limitation: "", evidenceNeeded: "" };
const freshDraft = (definition: EconomicCaseDefinition): CaseRunDraft => ({ caseSlug: definition.slug, currentStage: "context", predictions: {}, settings: defaultCaseSettings(definition), scenarios: {}, updatedAt: new Date().toISOString(), completed: false });
const number = (value: number) => new Intl.NumberFormat("en-US", { maximumFractionDigits: 2 }).format(value);

export function CaseWorkbench({ definition }: { definition: EconomicCaseDefinition }) {
  const { user, openAuth } = useAuth();
  const [draft, setDraft, hydrated] = usePersistentState<CaseRunDraft>(`econmind:case:${definition.slug}:v1`, freshDraft(definition));
  const [problemChecked, setProblemChecked] = useState(false); const [savedId, setSavedId] = useState<string | undefined>(); const [message, setMessage] = useState(""); const [runTitle, setRunTitle] = useState("");
  const currentIndex = CASE_STAGES.indexOf(draft.currentStage); const result = useMemo(() => runCaseSimulation(definition, draft.settings), [definition, draft.settings]);
  const predictionsComplete = definition.predictionQuestions.filter((question) => question.required).every((question) => Boolean(draft.predictions[question.id]?.trim()));
  const update = (partial: Partial<CaseRunDraft>) => setDraft((current) => ({ ...current, ...partial, updatedAt: new Date().toISOString() }));
  const go = (stage: CaseStage) => { if (stage === "simulation" && !predictionsComplete) { setMessage("Complete the required prediction before running the simulation."); return; } update({ currentStage: stage }); };
  const changeSetting = (key: string, value: number) => update({ settings: { ...draft.settings, [key]: value } });
  const saveScenario = (name: CaseScenarioName) => update({ scenarios: { ...draft.scenarios, [name]: { name, label: name === "baseline" ? "Baseline" : name === "no-intervention" ? "No intervention" : name === "policy-a" ? "Policy A" : "Policy B", settings: { ...draft.settings }, results: result, savedAt: new Date().toISOString() } } });
  const loadScenario = (name: CaseScenarioName) => { const scenario = draft.scenarios[name]; if (scenario) update({ settings: scenario.settings }); };
  const reset = () => { setDraft(freshDraft(definition)); setProblemChecked(false); setMessage("Local case draft reset."); };
  const save = async () => {
    if (!user) { openAuth("sign-in"); return; }
    try { const row = await saveCaseRun({ id: savedId, title: runTitle || `${definition.title} — ${new Date().toLocaleDateString()}`, draft: { ...draft, evaluation: draft.evaluation ?? evaluateCase(definition, result, {}) }, results: result as unknown as Record<string, unknown> }); setSavedId(row.id); setMessage("Saved privately to your EconMind account."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not save this case run."); }
  };
  const evaluation = draft.evaluation ?? evaluateCase(definition, result, {});

  if (!hydrated) return <main className="mx-auto min-h-screen max-w-7xl px-5 py-12 sm:px-8"><p className="text-sm text-[var(--ink-muted)]">Loading your local case draft…</p></main>;
  return <main className="mx-auto min-h-screen max-w-7xl px-5 py-8 sm:px-8 lg:py-12">
    <Link href="/cases" className="inline-flex items-center gap-2 text-xs font-bold text-[var(--ink-muted)] hover:text-[var(--ink)]"><ArrowLeft size={14} /> Cases</Link>
    <header className="mt-7 grid gap-6 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="text-[10px] font-extrabold uppercase tracking-[.18em] text-[var(--accent)]">Real-world case · {definition.category.replace("-", " ")}</p><h1 className="mt-3 text-4xl font-bold tracking-[-.05em] sm:text-5xl">{definition.title}</h1><p className="mt-4 max-w-3xl text-base leading-7 text-[var(--ink-muted)]">{definition.subtitle}</p><p className="mt-3 text-xs text-[var(--ink-faint)]">{definition.difficulty} · about {definition.estimatedMinutes} minutes · all simulation math runs in this browser</p></div><div className="flex max-w-sm flex-wrap gap-2"><input aria-label="Saved case title" value={runTitle} onChange={(event) => setRunTitle(event.target.value)} className="h-10 min-w-48 flex-1 rounded-lg border border-[var(--line)] bg-[var(--surface)] px-3 text-xs outline-none focus:border-[var(--accent)]" placeholder="Name this case run (optional)" /><Button variant="secondary" onClick={reset}>Reset local draft</Button><Button onClick={() => void save()}><Save size={15} />{user ? "Save case" : "Sign in to save"}</Button></div></header>
    {message && <p role="status" className="mt-5 rounded-lg border border-[var(--accent)] bg-[var(--accent-soft)] p-3 text-sm text-[var(--accent)]">{message}</p>}
    <nav aria-label="Case stages" className="scroll-rail mt-8 overflow-x-auto border-y border-[var(--line)] py-3"><ol className="flex min-w-max gap-1">{CASE_STAGES.map((stage, index) => <li key={stage}><button type="button" aria-current={stage === draft.currentStage ? "step" : undefined} onClick={() => go(stage)} className={`rounded-md px-3 py-2 text-xs font-bold ${stage === draft.currentStage ? "bg-[var(--accent)] text-white" : index < currentIndex ? "text-[var(--accent)]" : "text-[var(--ink-faint)] hover:bg-[var(--surface-subtle)]"}`}>{index + 1}. {stageLabels[stage]}</button></li>)}</ol></nav>
    <section className="mt-8">{draft.currentStage === "context" && <ContextStage definition={definition} />}{draft.currentStage === "problem" && <ProblemStage definition={definition} draft={draft} checked={problemChecked} onCheck={() => setProblemChecked(true)} onUpdate={update} />}{draft.currentStage === "mapping" && <MappingStage definition={definition} />}{draft.currentStage === "conditions" && <ConditionsStage definition={definition} />}{draft.currentStage === "prediction" && <PredictionStage definition={definition} values={draft.predictions} onChange={(id, value) => update({ predictions: { ...draft.predictions, [id]: value } })} />}{draft.currentStage === "simulation" && <SimulationStage definition={definition} result={result} settings={draft.settings} onChange={changeSetting} />}{draft.currentStage === "comparison" && <ComparisonStage draft={draft} result={result} save={saveScenario} load={loadScenario} />}{draft.currentStage === "evaluation" && <EvaluationStage definition={definition} evaluation={evaluation} onChange={(weights) => update({ evaluation: evaluateCase(definition, result, weights) })} />}{draft.currentStage === "recommendation" && <RecommendationStage recommendation={draft.recommendation ?? emptyRecommendation} onChange={(recommendation) => update({ recommendation })} />}{draft.currentStage === "reflection" && <ReflectionStage definition={definition} draft={draft} onComplete={() => update({ completed: true })} />}</section>
    <footer className="mt-8 flex items-center justify-between border-t border-[var(--line)] pt-5"><Button variant="secondary" disabled={currentIndex === 0} onClick={() => go(CASE_STAGES[Math.max(0, currentIndex - 1)])}><ArrowLeft size={15} /> Previous</Button><span className="text-xs text-[var(--ink-faint)]">Stage {currentIndex + 1} of {CASE_STAGES.length}</span><Button disabled={currentIndex === CASE_STAGES.length - 1 || (draft.currentStage === "prediction" && !predictionsComplete)} onClick={() => go(CASE_STAGES[Math.min(CASE_STAGES.length - 1, currentIndex + 1)])}>Next <ArrowRight size={15} /></Button></footer>
  </main>;
}

function StageHeader({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <header className="max-w-3xl"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[var(--accent)]">{eyebrow}</p><h2 className="mt-2 text-3xl font-bold tracking-[-.04em]">{title}</h2><p className="mt-3 text-sm leading-7 text-[var(--ink-muted)]">{text}</p></header>; }
function ContextStage({ definition }: { definition: EconomicCaseDefinition }) { const context = definition.realWorldContext; return <><StageHeader eyebrow="1. Context" title="Decide in a real-world setting." text={context.overview} /><div className="mt-7 grid gap-4 lg:grid-cols-3"><Info title="Decision" text={context.decision} /><Info title="Actors" text={context.actors.join(" · ")} /><Info title="Why it matters" text={context.significance} /></div><ExpandableAnalysisPanel title="Evidence and scope" modelLabel={definition.title} subtitle="Facts, calibrated inputs, and assumptions are kept separate."><div className="grid gap-5 md:grid-cols-2"><div><h3 className="text-xs font-bold">Context facts</h3><ul className="mt-3 space-y-2 text-sm leading-6 text-[var(--ink-muted)]">{context.facts.map((item) => <li key={item}>• {item}</li>)}</ul></div><div><h3 className="text-xs font-bold">Core assumptions</h3><ul className="mt-3 space-y-2 text-sm leading-6 text-[var(--ink-muted)]">{context.assumptions.map((item) => <li key={item}>• {item}</li>)}</ul></div></div></ExpandableAnalysisPanel></>; }
function ProblemStage({ definition, draft, checked, onCheck, onUpdate }: { definition: EconomicCaseDefinition; draft: CaseRunDraft; checked: boolean; onCheck: () => void; onUpdate: (value: Partial<CaseRunDraft>) => void }) { const problem = definition.economicProblem; const answer = draft.problemAnswer ?? { primary: "", secondary: [] }; return <><StageHeader eyebrow="2. Economic problem" title="Classify before you reveal." text="Choose the most useful economic framing. There can be more than one relevant concern, but start with the main mechanism." /><div className="mt-7 grid gap-4 lg:grid-cols-2"><ChoiceGroup label="Primary problem" options={problem.primaryOptions} value={answer.primary} onChange={(primary) => onUpdate({ problemAnswer: { ...answer, primary } })} /><ChoiceGroup label="Secondary consideration" options={problem.secondaryOptions} value={answer.secondary[0] ?? ""} onChange={(secondary) => onUpdate({ problemAnswer: { ...answer, secondary: secondary ? [secondary] : [] } })} /></div><Button className="mt-5" onClick={onCheck} disabled={!answer.primary}>Check classification</Button>{checked && <div className="mt-5 rounded-xl border border-[var(--accent)] bg-[var(--accent-soft)] p-5"><p className="text-sm font-bold">{answer.primary === problem.correctPrimary ? "Strong primary classification." : "Try comparing your choice with the case mechanism."}</p><p className="mt-2 text-sm leading-6 text-[var(--ink-muted)]">{problem.reveal}</p></div>}</>; }
function MappingStage({ definition }: { definition: EconomicCaseDefinition }) { return <><StageHeader eyebrow="3. Model mapping" title="Map the event to a model, then name what is left out." text="The model is a lens, not the whole situation." /><div className="mt-7 space-y-4">{definition.modelMappings.map((mapping) => <Card key={mapping.model} className="p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="text-lg font-bold">{mapping.model}</h3><Link href={mapping.route} className="inline-flex items-center gap-1 text-xs font-bold text-[var(--accent)]">Open model <ExternalLink size={13} /></Link></div><dl className="mt-5 grid gap-4 text-sm leading-6 md:grid-cols-2"><Definition label="Real-world event" value={mapping.realWorldEvent} /><Definition label="Model variable" value={mapping.modelVariable} /><Definition label="Mechanism" value={mapping.mechanism} /><Definition label="Expected outcome" value={mapping.expectedOutcome} /><Definition label="Why this model" value={mapping.selectedReason} /><Definition label="Key limitation" value={mapping.limitation} /></dl><p className="mt-4 text-xs text-[var(--ink-muted)]"><strong>Not represented:</strong> {mapping.omittedVariables.join(", ")}</p></Card>)}</div></>; }
function ConditionsStage({ definition }: { definition: EconomicCaseDefinition }) { return <><StageHeader eyebrow="4. Initial conditions" title="Separate observed context from teaching inputs." text="Source labels show whether a value is real-world context, calibrated, indexed, or stylised." /><div className="scroll-slim mt-7 overflow-x-auto rounded-xl border border-[var(--line)]"><table className="min-w-[720px] w-full text-left text-sm"><thead className="bg-[var(--surface-subtle)] text-[10px] uppercase tracking-wider text-[var(--ink-faint)]"><tr><th className="p-3">Variable</th><th className="p-3">Start</th><th className="p-3">Type</th><th className="p-3">Interpretation</th></tr></thead><tbody>{definition.initialConditions.map((item) => <tr key={item.key} className="border-t border-[var(--line)]"><td className="p-3 font-bold">{item.label}</td><td className="p-3">{String(item.value)}{item.unit}</td><td className="p-3 capitalize">{item.sourceType}</td><td className="p-3 text-[var(--ink-muted)]">{item.note}</td></tr>)}</tbody></table></div><div className="mt-6 grid gap-4 md:grid-cols-2">{definition.constraints.map((item) => <Info key={item.label} title={item.label} text={`${item.rule} ${item.explanation}`} />)}</div></>; }
function PredictionStage({ definition, values, onChange }: { definition: EconomicCaseDefinition; values: Record<string, string>; onChange: (id: string, value: string) => void }) { return <><StageHeader eyebrow="5. Prediction" title="Commit to a prediction before you simulate." text="A prediction is not graded as a forecast; it makes the mechanism you expect explicit." /><div className="mt-7 space-y-5">{definition.predictionQuestions.map((question) => <Card key={question.id} className="p-5"><label className="block text-sm font-bold">{question.prompt}{question.required && <span className="ml-1 text-[var(--red)]">*</span>}</label>{question.type === "choice" || question.type === "direction" ? <div className="mt-4 flex flex-wrap gap-2">{question.options?.map((option) => <button key={option} type="button" onClick={() => onChange(question.id, option)} className={`rounded-lg border px-3 py-2 text-xs font-bold ${values[question.id] === option ? "border-[var(--accent)] bg-[var(--accent-soft)] text-[var(--accent)]" : "border-[var(--line)]"}`}>{option}</button>)}</div> : <textarea value={values[question.id] ?? ""} onChange={(event) => onChange(question.id, event.target.value)} className="mt-4 min-h-24 w-full rounded-lg border border-[var(--line)] bg-[var(--canvas)] p-3 text-sm outline-none focus:border-[var(--accent)]" placeholder="Write a short explanation…" />}</Card>)}</div></>; }
function SimulationStage({ definition, result, settings, onChange }: { definition: EconomicCaseDefinition; result: ReturnType<typeof runCaseSimulation>; settings: Record<string, number>; onChange: (key: string, value: number) => void }) { return <><StageHeader eyebrow="6. Simulation" title="Change the permitted levers and watch the model update." text="Every calculation is local to your browser. Values marked as estimates are classroom outputs, not forecasts." /><div className="mt-7 grid gap-6 xl:grid-cols-[360px_1fr]"><Card className="h-fit p-5"><h3 className="text-sm font-bold">Policy controls</h3><p className="mt-1 text-xs leading-5 text-[var(--ink-muted)]">Only decision-relevant inputs are editable in this case.</p><div className="scroll-slim mt-3 max-h-[68vh] overflow-y-auto pr-1">{definition.availablePolicies.map((control) => <div key={control.key} className="border-b border-[var(--line)] py-4 last:border-0"><div className="flex justify-between gap-3"><label htmlFor={control.key} className="text-xs font-bold">{control.label}<span className="mt-1 block text-[10px] font-normal leading-4 text-[var(--ink-muted)]">{control.description}</span></label><output className="h-fit rounded bg-[var(--accent-soft)] px-2 py-1 text-xs font-bold text-[var(--accent)]">{number(settings[control.key] ?? control.defaultValue)}{control.unit}</output></div><input id={control.key} className="mt-3 w-full" type="range" min={control.min} max={control.max} step={control.step} value={settings[control.key] ?? control.defaultValue} onChange={(event) => onChange(control.key, Number(event.target.value))} /><div className="mt-1 flex justify-between text-[9px] text-[var(--ink-faint)]"><span>{control.min}</span><span>{control.max}</span></div></div>)}</div></Card><div>{!result.valid && <p className="rounded-lg bg-[var(--red-soft)] p-4 text-sm text-[var(--red)]">{result.validationMessage ?? result.constraintMessages.join(" ")}</p>}<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{Object.entries(result.headline).map(([key, value]) => <Metric key={key} label={key.replace(/([A-Z])/g, " $1")} value={value} unit={result.metricUnits[key] ?? ""} />)}</div><div className="mt-5"><MechanismChain steps={result.mechanism} modelLabel={definition.title} /></div><div className="mt-5"><EquationView steps={result.equations} modelLabel={definition.title} /></div><div className="mt-5"><StakeholderImpact items={result.stakeholders} modelLabel={definition.title} /></div></div></div></>; }
function ComparisonStage({ draft, result, save, load }: { draft: CaseRunDraft; result: ReturnType<typeof runCaseSimulation>; save: (name: CaseScenarioName) => void; load: (name: CaseScenarioName) => void }) { const names: CaseScenarioName[] = ["baseline", "no-intervention", "policy-a", "policy-b"]; return <><StageHeader eyebrow="7. Outcome comparison" title="Compare explicit scenarios, not labels alone." text="Save any setting as a named snapshot. Stored snapshots stay in localStorage until you sign in and save a case run." /><div className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{names.map((name) => { const snapshot = draft.scenarios[name]; return <Card key={name} className="p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-[var(--ink-faint)]">{name.replace("-", " ")}</p>{snapshot ? <><p className="mt-3 text-sm font-bold">Saved {new Date(snapshot.savedAt).toLocaleTimeString()}</p><p className="mt-2 text-xs leading-5 text-[var(--ink-muted)]">{Object.entries(snapshot.results.headline).slice(0, 3).map(([key, value]) => <span key={key} className="block">{key}: {number(value)}{snapshot.results.metricUnits[key] ?? ""}</span>)}</p><Button className="mt-4" size="sm" variant="secondary" onClick={() => load(name)}>Load</Button></> : <p className="mt-3 text-sm text-[var(--ink-muted)]">No snapshot yet.</p>}<Button className="mt-3" size="sm" onClick={() => save(name)}>Save current</Button></Card>; })}</div><Card className="mt-5 p-5"><h3 className="text-sm font-bold">Live outcome</h3><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(result.headline).slice(0, 4).map(([key, value]) => <Metric key={key} label={key.replace(/([A-Z])/g, " $1")} value={value} unit={result.metricUnits[key] ?? ""} />)}</div><p className="mt-4 text-xs leading-5 text-[var(--ink-muted)]">Compare each scenario only against the same case definition and assumptions. A snapshot does not prove causality outside this model.</p></Card></>; }
function EvaluationStage({ definition, evaluation, onChange }: { definition: EconomicCaseDefinition; evaluation: ReturnType<typeof evaluateCase>; onChange: (weights: Record<string, number>) => void }) { return <><StageHeader eyebrow="8. Evaluation" title="Make your weighting visible." text={definition.evaluationConfig.note} /><div className="mt-7 grid gap-6 lg:grid-cols-[1fr_320px]"><Card className="p-5"><h3 className="text-sm font-bold">Decision weights</h3><div className="mt-4 space-y-4">{definition.evaluationConfig.objectives.map((objective) => <label key={objective.key} className="block"><span className="flex justify-between text-xs font-bold"><span>{objective.label}</span><output>{evaluation.weights[objective.key] ?? objective.defaultWeight}%</output></span><input type="range" className="mt-2 w-full" min="0" max="100" step="5" value={evaluation.weights[objective.key] ?? objective.defaultWeight} onChange={(event) => onChange({ ...evaluation.weights, [objective.key]: Number(event.target.value) })} /></label>)}</div></Card><Card className="p-5"><p className="text-[10px] font-bold uppercase tracking-wider text-[var(--ink-faint)]">Transparent score</p><p className="mt-2 text-5xl font-bold tracking-[-.06em]">{number(evaluation.score)}<span className="text-lg text-[var(--ink-faint)]">/100</span></p><div className="mt-5 space-y-2 text-sm">{Object.entries(evaluation.dimensionScores).map(([key, value]) => <p key={key} className="flex justify-between"><span className="capitalize">{key}</span><b>{number(value)}</b></p>)}</div></Card></div><p className="mt-5 rounded-lg bg-[var(--surface-subtle)] p-4 text-sm leading-6 text-[var(--ink-muted)]">{evaluation.explanation}</p><button type="button" onClick={() => onChange(evaluation.weights)} className="mt-4 text-xs font-bold text-[var(--accent)]">Store this evaluation in the local draft</button></>; }
function RecommendationStage({ recommendation, onChange }: { recommendation: CaseRecommendation; onChange: (value: CaseRecommendation) => void }) { const fields: Array<[keyof CaseRecommendation, string, string]> = [["selectedPolicy", "Recommended policy / action", "Choose a concrete setting or package."], ["mainBenefit", "Main benefit", "Who gains and through what mechanism?"], ["mainCost", "Main cost", "State a cost, risk, or constraint."], ["affectedStakeholder", "Most affected stakeholder", "Name a group, not just ‘the economy’."], ["tradeOff", "Trade-off", "What objective worsens or remains uncertain?"], ["keyAssumption", "Key assumption", "Which model assumption matters most?"], ["limitation", "Limitation", "What does the current model not establish?"], ["evidenceNeeded", "Evidence needed", "What real data would you request next?"]]; return <><StageHeader eyebrow="9. Recommendation" title="Recommend, but make the trade-off explicit." text="A valid recommendation names its beneficiaries, costs, assumptions, and missing evidence." /><Card className="mt-7 p-5"><div className="grid gap-4 md:grid-cols-2">{fields.map(([key, label, placeholder]) => <label key={key} className="block text-xs font-bold">{label}<textarea value={recommendation[key]} onChange={(event) => onChange({ ...recommendation, [key]: event.target.value })} className="mt-2 min-h-24 w-full rounded-lg border border-[var(--line)] bg-[var(--canvas)] p-3 text-sm font-normal outline-none focus:border-[var(--accent)]" placeholder={placeholder} /></label>)}</div></Card><p className="mt-4 text-xs text-[var(--ink-muted)]">This is an educational policy memo, not professional financial, legal, or operational advice.</p></>; }
function ReflectionStage({ definition, draft, onComplete }: { definition: EconomicCaseDefinition; draft: CaseRunDraft; onComplete: () => void }) { return <><StageHeader eyebrow="10. Reflection" title="Transfer the mechanism, not the number." text="Use the questions below to check whether your decision depends on a fragile assumption." /><div className="mt-7 space-y-3">{definition.reflectionQuestions.map((question, index) => <Card key={question} className="p-5"><p className="text-xs font-bold text-[var(--accent)]">Reflection {index + 1}</p><p className="mt-2 text-sm leading-6">{question}</p></Card>)}</div><Card className="mt-5 p-5"><p className="text-sm font-bold">Case completion</p><p className="mt-2 text-sm leading-6 text-[var(--ink-muted)]">{draft.completed ? "Completed locally. Use Save case to store this record privately in Supabase." : "Mark the case complete when you have reviewed the model limitations and written your recommendation."}</p>{!draft.completed && <Button className="mt-4" onClick={onComplete}><Check size={15} /> Mark complete</Button>}</Card><div className="mt-6"><ExpandableAnalysisPanel title="Case assumptions" modelLabel={definition.title} subtitle="These conditions limit what an output can establish."><ul className="space-y-3 text-sm leading-6 text-[var(--ink-muted)]">{definition.realWorldContext.assumptions.concat(definition.modelMappings.flatMap((item) => item.omittedVariables.map((value) => `Not modelled: ${value}`))).map((item) => <li key={item}>• {item}</li>)}</ul></ExpandableAnalysisPanel></div><div className="mt-5"><ExpandableAnalysisPanel title="Sources" modelLabel={definition.title} subtitle="Use original sources for context; calculations remain transparent teaching calibrations."><ul className="space-y-3">{definition.evidenceSources.map((source) => <li key={source.url}><a className="text-sm font-bold text-[var(--accent)] hover:underline" href={source.url} target="_blank" rel="noreferrer">{source.label} <ExternalLink className="inline" size={12} /></a><p className="mt-1 text-xs leading-5 text-[var(--ink-muted)]">{source.note}</p></li>)}</ul></ExpandableAnalysisPanel></div></>; }
function Info({ title, text }: { title: string; text: string }) { return <Card className="p-5"><h3 className="text-[10px] font-extrabold uppercase tracking-wider text-[var(--ink-faint)]">{title}</h3><p className="mt-3 text-sm leading-6 text-[var(--ink-muted)]">{text}</p></Card>; }
function Definition({ label, value }: { label: string; value: string }) { return <div><dt className="text-[10px] font-extrabold uppercase tracking-wider text-[var(--ink-faint)]">{label}</dt><dd className="mt-1 text-[var(--ink-muted)]">{value}</dd></div>; }
function ChoiceGroup({ label, options, value, onChange }: { label: string; options: string[]; value: string; onChange: (value: string) => void }) { return <Card className="p-5"><p className="text-sm font-bold">{label}</p><div className="mt-4 grid gap-2">{options.map((option) => <button type="button" key={option} onClick={() => onChange(option)} className={`rounded-lg border p-3 text-left text-sm ${option === value ? "border-[var(--accent)] bg-[var(--accent-soft)] font-bold text-[var(--accent)]" : "border-[var(--line)] text-[var(--ink-muted)]"}`}>{option}</button>)}</div></Card>; }
function Metric({ label, value, unit }: { label: string; value: number; unit: string }) { return <Card className="p-4"><p className="text-[10px] font-extrabold uppercase tracking-wider text-[var(--ink-faint)]">{label}</p><p className="mt-2 text-2xl font-bold tracking-[-.04em]">{number(value)}<span className="ml-1 text-xs font-semibold text-[var(--ink-faint)]">{unit}</span></p></Card>; }
