/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 51d7982b12312bd61ca3ee06aebbfbf5)
interface __BaseEnv_Env {
	SUPABASE_URL: "https://vimksjrhaxdpnkvgsavz.supabase.co";
	SITE_ORIGIN: "https://econmind.group";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SUPABASE_URL" | "SITE_ORIGIN">> {}
}
