// EconMind Live Auction preset data.
// starting_price_usd is a PRESET equal to the published auction estimate LOW bound.
// It is NOT claimed to be the historical auction's literal opening bid.

export const ECONMIND_AUCTION_PRESETS = [
  {
    "id": "porcelain_kangxi_landscape_dish",
    "category": "porcelain",
    "category_zh": "瓷器",
    "title_zh": "清康熙 青花山水人物图盘《大清康熙年制》款",
    "title_en": "A large and very rare blue and white 'landscape' dish, Mark and period of Kangxi",
    "maker_or_period": "Kangxi period, Qing dynasty",
    "auction_house": "Sotheby's",
    "auction_year": 2024,
    "lot_number": "325",
    "estimate_low_usd": 8000,
    "estimate_high_usd": 12000,
    "starting_price_usd": 8000,
    "short_description_zh": "康熙朝青花山水人物大盘，画面以浓淡钴蓝描绘山水、人物与河景，直径约27.3厘米。",
    "source_url": "https://www.sothebys.com/en/buy/auction/2024/important-chinese-art/a-large-and-very-rare-blue-and-white-landscape",
    "image_output_stem": "porcelain_01_kangxi_landscape_dish",
    "currency": "USD",
    "starting_price_basis": "LOW_ESTIMATE_PROXY",
    "image_local_path": null
  },
  {
    "id": "porcelain_kangxi_clair_de_lune_hu_vase",
    "category": "porcelain",
    "category_zh": "瓷器",
    "title_zh": "清康熙 天蓝釉琵琶式尊《大清康熙年制》款",
    "title_en": "A clair-de-lune-glazed Hu-form vase, Kangxi mark and period",
    "maker_or_period": "Kangxi period, Qing dynasty",
    "auction_house": "Sotheby's",
    "auction_year": 2020,
    "lot_number": "105",
    "estimate_low_usd": 200000,
    "estimate_high_usd": 300000,
    "starting_price_usd": 200000,
    "short_description_zh": "康熙官窑天蓝釉琵琶式尊，釉色淡雅，器身呈压扁梨形，足底书康熙六字款。",
    "source_url": "https://www.sothebys.com/en/buy/auction/2020/kangxi-porcelain-a-private-collection/a-clair-de-lune-glazed-hu-form-vase-kangxi-mark",
    "image_output_stem": "porcelain_02_kangxi_clair_de_lune_hu_vase",
    "currency": "USD",
    "starting_price_basis": "LOW_ESTIMATE_PROXY",
    "image_local_path": null
  },
  {
    "id": "porcelain_kangxi_aubergine_bowl",
    "category": "porcelain",
    "category_zh": "瓷器",
    "title_zh": "清康熙 茄皮紫釉盌《大清康熙年制》款",
    "title_en": "A rare aubergine-glazed bowl, Kangxi mark and period",
    "maker_or_period": "Kangxi period, Qing dynasty",
    "auction_house": "Sotheby's",
    "auction_year": 2020,
    "lot_number": "104",
    "estimate_low_usd": 40000,
    "estimate_high_usd": 60000,
    "starting_price_usd": 40000,
    "short_description_zh": "康熙官窑茄皮紫釉碗，通体施紫靛色透明釉，口沿外撇，直径约12.5厘米。",
    "source_url": "https://www.sothebys.com/buy/715b73cb-e5a6-4845-9bf4-ec7deceedfd3/lots/bfefc060-0e8c-4309-ba13-b23c72264a48",
    "image_output_stem": "porcelain_03_kangxi_aubergine_bowl",
    "currency": "USD",
    "starting_price_basis": "LOW_ESTIMATE_PROXY",
    "image_local_path": null
  },
  {
    "id": "porcelain_kangxi_blue_meiping",
    "category": "porcelain",
    "category_zh": "瓷器",
    "title_zh": "清康熙 霁蓝釉梅瓶《大清康熙年制》款",
    "title_en": "A rare blue-glazed Meiping, Kangxi mark and period",
    "maker_or_period": "Kangxi period, Qing dynasty",
    "auction_house": "Sotheby's",
    "auction_year": 2020,
    "lot_number": "118",
    "estimate_low_usd": 40000,
    "estimate_high_usd": 60000,
    "starting_price_usd": 40000,
    "short_description_zh": "康熙霁蓝釉梅瓶，器身施浓郁深蓝釉，器底书六字康熙款，高约17厘米。",
    "source_url": "https://www.sothebys.com/en/buy/auction/2020/kangxi-porcelain-a-private-collection/a-rare-blue-glazed-meiping-kangxi-mark-and-period",
    "image_output_stem": "porcelain_04_kangxi_blue_meiping",
    "currency": "USD",
    "starting_price_basis": "LOW_ESTIMATE_PROXY",
    "image_local_path": null
  },
  {
    "id": "porcelain_kangxi_yellow_dragon_cup",
    "category": "porcelain",
    "category_zh": "瓷器",
    "title_zh": "清康熙 黄釉暗刻赶珠龙纹双耳小盃《大清康熙年制》款",
    "title_en": "A fine incised yellow-glazed 'dragon' handled cup, Kangxi mark and period",
    "maker_or_period": "Kangxi period, Qing dynasty",
    "auction_house": "Sotheby's",
    "auction_year": 2020,
    "lot_number": "101",
    "estimate_low_usd": 20000,
    "estimate_high_usd": 30000,
    "starting_price_usd": 20000,
    "short_description_zh": "康熙黄釉双耳小盃，外壁暗刻双龙追逐火珠纹，器底书康熙六字款。",
    "source_url": "https://www.sothebys.com/en/buy/auction/2020/kangxi-porcelain-a-private-collection/a-fine-incised-yellow-glazed-dragon-handled-cup",
    "image_output_stem": "porcelain_05_kangxi_yellow_dragon_cup",
    "currency": "USD",
    "starting_price_basis": "LOW_ESTIMATE_PROXY",
    "image_local_path": null
  },
  {
    "id": "painting_zhang_daqian_narcissus",
    "category": "painting",
    "category_zh": "画作",
    "title_zh": "张大千《水仙花》",
    "title_en": "Zhang Daqian — Narcissus",
    "maker_or_period": "Zhang Daqian (1899–1983)",
    "auction_house": "Sotheby's",
    "auction_year": 2021,
    "lot_number": "778",
    "estimate_low_usd": 30000,
    "estimate_high_usd": 50000,
    "starting_price_usd": 30000,
    "short_description_zh": "张大千水仙题材设色纸本立轴，署款并钤多方艺术家印章。",
    "source_url": "https://www.sothebys.com/en/buy/auction/2021/in-the-studio-asian-art-featuring-works-from-the-collection-of-bruce-dayton-and-ruth-stricker-dayton/narcissus-ink-and-light-color-on-paper-hanging",
    "image_output_stem": "painting_01_zhang_daqian_narcissus",
    "currency": "USD",
    "starting_price_basis": "LOW_ESTIMATE_PROXY",
    "image_local_path": null
  },
  {
    "id": "painting_qi_baishi_persimmons",
    "category": "painting",
    "category_zh": "画作",
    "title_zh": "齐白石《柿子篮》",
    "title_en": "Qi Baishi — Persimmons in a Basket",
    "maker_or_period": "Qi Baishi (1864–1957)",
    "auction_house": "Sotheby's",
    "auction_year": 2012,
    "lot_number": "699",
    "estimate_low_usd": 120000,
    "estimate_high_usd": 180000,
    "starting_price_usd": 120000,
    "short_description_zh": "齐白石纸本设色立轴，以一篮柿子为题，并有艺术家署款与钤印。",
    "source_url": "https://www.sothebys.com/en/auctions/ecatalogue/2012/fine-classical-chinese-paintings-n08835/lot.699.html",
    "image_output_stem": "painting_02_qi_baishi_persimmons",
    "currency": "USD",
    "starting_price_basis": "LOW_ESTIMATE_PROXY",
    "image_local_path": null
  },
  {
    "id": "painting_fu_baoshi_kunlun",
    "category": "painting",
    "category_zh": "画作",
    "title_zh": "傅抱石《昆仑山》",
    "title_en": "Fu Baoshi — Kunlun Mountain",
    "maker_or_period": "Fu Baoshi (1904–1965)",
    "auction_house": "Sotheby's",
    "auction_year": 2018,
    "lot_number": "1150",
    "estimate_low_usd": 30000,
    "estimate_high_usd": 50000,
    "starting_price_usd": 30000,
    "short_description_zh": "傅抱石水墨纸本《昆仑山》，装裱待框，画面以山势与水墨层次为主体。",
    "source_url": "https://www.sothebys.com/en/auctions/ecatalogue/2018/chew-family-collection-chinese-paintings-calligraphy-n09832/lot.1150.html",
    "image_output_stem": "painting_03_fu_baoshi_kunlun",
    "currency": "USD",
    "starting_price_basis": "LOW_ESTIMATE_PROXY",
    "image_local_path": null
  },
  {
    "id": "painting_xu_beihong_galloping_horse",
    "category": "painting",
    "category_zh": "画作",
    "title_zh": "徐悲鸿《奔马》",
    "title_en": "Xu Beihong — Galloping Horse",
    "maker_or_period": "Xu Beihong (1895–1953), dated 1945",
    "auction_house": "Sotheby's",
    "auction_year": 2007,
    "lot_number": "111",
    "estimate_low_usd": 35000,
    "estimate_high_usd": 45000,
    "starting_price_usd": 35000,
    "short_description_zh": "徐悲鸿1945年作奔马水墨纸本立轴，以传统笔墨结合现代透视与马匹解剖表现。",
    "source_url": "https://www.sothebys.com/en/auctions/ecatalogue/2007/the-concordia-house-collection-fine-chinese-jades-and-important-works-of-art-from-a-midwestern-family-n08347/lot.111.html",
    "image_output_stem": "painting_04_xu_beihong_galloping_horse",
    "currency": "USD",
    "starting_price_basis": "LOW_ESTIMATE_PROXY",
    "image_local_path": null
  },
  {
    "id": "painting_wu_guanzhong_riverside_village",
    "category": "painting",
    "category_zh": "画作",
    "title_zh": "吴冠中《河畔村庄》",
    "title_en": "Wu Guanzhong — Village by the Riverside",
    "maker_or_period": "Wu Guanzhong (1919–2010)",
    "auction_house": "Sotheby's",
    "auction_year": 2013,
    "lot_number": "765",
    "estimate_low_usd": 80000,
    "estimate_high_usd": 120000,
    "starting_price_usd": 80000,
    "short_description_zh": "吴冠中纸本设色《河畔村庄》，装框，作品带艺术家钤印。",
    "source_url": "https://www.sothebys.com/en/auctions/ecatalogue/2013/fine-classical-chinese-paintings-n09009/lot.765.html",
    "image_output_stem": "painting_05_wu_guanzhong_riverside_village",
    "currency": "USD",
    "starting_price_basis": "LOW_ESTIMATE_PROXY",
    "image_local_path": null
  },
  {
    "id": "bronze_late_shang_gui",
    "category": "bronze",
    "category_zh": "青铜器",
    "title_zh": "商末 青铜礼器簋",
    "title_en": "An archaic bronze ritual food vessel (Gui), Late Shang dynasty",
    "maker_or_period": "Late Shang dynasty",
    "auction_house": "Sotheby's",
    "auction_year": 2024,
    "lot_number": "28",
    "estimate_low_usd": 50000,
    "estimate_high_usd": 70000,
    "starting_price_usd": 50000,
    "short_description_zh": "商末青铜簋，器身铸繁复雷纹与分区纹饰，宽约26.3厘米，并配木座。",
    "source_url": "https://www.sothebys.com/en/buy/auction/2024/chinese-art/an-archaic-bronze-ritual-food-vessel-gui-late",
    "image_output_stem": "bronze_01_late_shang_gui",
    "currency": "USD",
    "starting_price_basis": "LOW_ESTIMATE_PROXY",
    "image_local_path": null
  },
  {
    "id": "bronze_eastern_zhou_jian",
    "category": "bronze",
    "category_zh": "青铜器",
    "title_zh": "东周 春秋末约公元前500年 青铜变形龙纹兽首耳鉴",
    "title_en": "A massive archaic bronze water basin (Jian), Eastern Zhou dynasty, late Spring and Autumn period, circa 500 BC",
    "maker_or_period": "Eastern Zhou, late Spring and Autumn period, c. 500 BC",
    "auction_house": "Sotheby's",
    "auction_year": 2021,
    "lot_number": "17",
    "estimate_low_usd": 80000,
    "estimate_high_usd": 120000,
    "starting_price_usd": 80000,
    "short_description_zh": "大型东周青铜鉴，四侧置兽面D形耳，器表饰密集卷曲纹与垂叶纹。",
    "source_url": "https://www.sothebys.com/en/buy/auction/2021/important-chinese-art-5/a-massive-archaic-bronze-water-basin-jian-eastern",
    "image_output_stem": "bronze_02_eastern_zhou_jian",
    "currency": "USD",
    "starting_price_basis": "LOW_ESTIMATE_PROXY",
    "image_local_path": null
  },
  {
    "id": "bronze_late_shang_pou",
    "category": "bronze",
    "category_zh": "青铜器",
    "title_zh": "商末 青铜饕餮纹羊首瓿",
    "title_en": "An archaic bronze ritual vessel (Pou), Late Shang dynasty",
    "maker_or_period": "Late Shang dynasty",
    "auction_house": "Sotheby's",
    "auction_year": 2021,
    "lot_number": "34",
    "estimate_low_usd": 100000,
    "estimate_high_usd": 150000,
    "starting_price_usd": 100000,
    "short_description_zh": "商末青铜瓿，器身饰饕餮、夔龙及羊首高浮雕，直径约33.1厘米。",
    "source_url": "https://www.sothebys.com/en/buy/auction/2021/important-chinese-art-5/an-archaic-bronze-ritual-vessel-pou-late-shang",
    "image_output_stem": "bronze_03_late_shang_pou",
    "currency": "USD",
    "starting_price_basis": "LOW_ESTIMATE_PROXY",
    "image_local_path": null
  },
  {
    "id": "bronze_eastern_zhou_he",
    "category": "bronze",
    "category_zh": "青铜器",
    "title_zh": "东周 春秋 青铜兽面纹龙流盉",
    "title_en": "An exceptionally rare archaic bronze ritual pouring vessel (He), Eastern Zhou dynasty, Spring and Autumn period",
    "maker_or_period": "Eastern Zhou, Spring and Autumn period",
    "auction_house": "Sotheby's",
    "auction_year": 2021,
    "lot_number": "12",
    "estimate_low_usd": 250000,
    "estimate_high_usd": 350000,
    "starting_price_usd": 250000,
    "short_description_zh": "春秋时期青铜盉，三足、龙首流与兽首纹装饰并用，长约35.8厘米。",
    "source_url": "https://www.sothebys.com/buy/95dec87f-7d0e-4499-927a-bf96d47eb14b/lots/d0a45209-e52d-40d3-97d0-f07e2fa6d833",
    "image_output_stem": "bronze_04_eastern_zhou_he",
    "currency": "USD",
    "starting_price_basis": "LOW_ESTIMATE_PROXY",
    "image_local_path": null
  },
  {
    "id": "bronze_late_western_zhou_yi",
    "category": "bronze",
    "category_zh": "青铜器",
    "title_zh": "西周末 青铜兽体纹龙鋬匜",
    "title_en": "An archaic bronze ritual pouring vessel (Yi), Late Western Zhou dynasty",
    "maker_or_period": "Late Western Zhou dynasty",
    "auction_house": "Sotheby's",
    "auction_year": 2023,
    "lot_number": "618",
    "estimate_low_usd": 60000,
    "estimate_high_usd": 80000,
    "starting_price_usd": 60000,
    "short_description_zh": "西周末青铜匜，具龙形鋬与兽体纹饰，长约37厘米，并配木座。",
    "source_url": "https://www.sothebys.com/buy/09186a6d-d0a0-4969-873d-4b1c281fdf44/lots/b6fe44dc-912e-40f8-8329-759675a7b88e",
    "image_output_stem": "bronze_05_late_western_zhou_yi",
    "currency": "USD",
    "starting_price_basis": "LOW_ESTIMATE_PROXY",
    "image_local_path": null
  },
  {
    "id": "jade_qianlong_gu_vase",
    "category": "jade",
    "category_zh": "玉器",
    "title_zh": "清乾隆 白玉雕双耳活环花觚",
    "title_en": "A white jade loose-handled gu-form vase, Qing dynasty, Qianlong period",
    "maker_or_period": "Qing dynasty, Qianlong period",
    "auction_house": "Sotheby's",
    "auction_year": 2024,
    "lot_number": "447",
    "estimate_low_usd": 200000,
    "estimate_high_usd": 300000,
    "starting_price_usd": 200000,
    "short_description_zh": "乾隆白玉仿古花觚，双耳配活环，高约18.7厘米，为宫廷仿古风格玉器。",
    "source_url": "https://www.sothebys.com/en/buy/auction/2024/important-chinese-art/a-white-jade-loose-handled-gu-form-vase-qing",
    "image_output_stem": "jade_01_qianlong_gu_vase",
    "currency": "USD",
    "starting_price_basis": "LOW_ESTIMATE_PROXY",
    "image_local_path": null
  },
  {
    "id": "jade_18c_celadon_mountain",
    "category": "jade",
    "category_zh": "玉器",
    "title_zh": "清十八世纪 青白玉雕灵岳绝壁图山子",
    "title_en": "An extraordinary and rare pale celadon jade mountain, Qing dynasty, 18th century",
    "maker_or_period": "Qing dynasty, 18th century",
    "auction_house": "Sotheby's",
    "auction_year": 2020,
    "lot_number": "211",
    "estimate_low_usd": 100000,
    "estimate_high_usd": 150000,
    "starting_price_usd": 100000,
    "short_description_zh": "十八世纪青白玉山子，以整块玉料雕峭壁、灵芝与树木，高约29.4厘米。",
    "source_url": "https://www.sothebys.com/en/buy/auction/2020/junkunc-chinese-jade-carvings/an-extraordinary-and-rare-pale-celadon-jade",
    "image_output_stem": "jade_02_18c_celadon_mountain",
    "currency": "USD",
    "starting_price_basis": "LOW_ESTIMATE_PROXY",
    "image_local_path": null
  },
  {
    "id": "jade_qianlong_prunus_lingzhi_vase",
    "category": "jade",
    "category_zh": "玉器",
    "title_zh": "清乾隆 白玉梅花灵芝纹盖瓶",
    "title_en": "A large white jade 'prunus and lingzhi' vase and cover, Qing dynasty, Qianlong period",
    "maker_or_period": "Qing dynasty, Qianlong period",
    "auction_house": "Sotheby's",
    "auction_year": 2023,
    "lot_number": "522",
    "estimate_low_usd": 60000,
    "estimate_high_usd": 80000,
    "starting_price_usd": 60000,
    "short_description_zh": "乾隆白玉盖瓶，以高浮雕与镂雕表现梅花、灵芝纹，高约24.6厘米。",
    "source_url": "https://www.sothebys.com/en/buy/auction/2023/important-chinese-art/a-large-white-jade-prunus-and-lingzhi-vase-and",
    "image_output_stem": "jade_03_qianlong_prunus_lingzhi_vase",
    "currency": "USD",
    "starting_price_basis": "LOW_ESTIMATE_PROXY",
    "image_local_path": null
  },
  {
    "id": "jade_qianlong_crab",
    "category": "jade",
    "category_zh": "玉器",
    "title_zh": "清乾隆 白玉雕岁岁和谐摆件（蟹）",
    "title_en": "A white jade carving of a crab, Qing dynasty, Qianlong period",
    "maker_or_period": "Qing dynasty, Qianlong period",
    "auction_house": "Sotheby's",
    "auction_year": 2024,
    "lot_number": "444",
    "estimate_low_usd": 8000,
    "estimate_high_usd": 12000,
    "starting_price_usd": 8000,
    "short_description_zh": "乾隆白玉蟹形摆件，长约13.3厘米，并配木座，以“蟹/谐”形成吉祥语意。",
    "source_url": "https://www.sothebys.com/en/buy/auction/2024/important-chinese-art/a-white-jade-carving-of-a-crab-qing-dynasty",
    "image_output_stem": "jade_04_qianlong_crab",
    "currency": "USD",
    "starting_price_basis": "LOW_ESTIMATE_PROXY",
    "image_local_path": null
  },
  {
    "id": "jade_qianlong_chilong_disc",
    "category": "jade",
    "category_zh": "玉器",
    "title_zh": "清乾隆 白玉雕螭龙纹璧",
    "title_en": "A white jade archaistic 'chilong' disc, Qing dynasty, Qianlong period",
    "maker_or_period": "Qing dynasty, Qianlong period",
    "auction_house": "Sotheby's",
    "auction_year": 2023,
    "lot_number": "840",
    "estimate_low_usd": 6000,
    "estimate_high_usd": 8000,
    "starting_price_usd": 6000,
    "short_description_zh": "乾隆白玉仿古螭龙纹璧，直径约5.8厘米，属于清宫常见的仿古玉器审美。",
    "source_url": "https://www.sothebys.com/en/buy/auction/2023/important-chinese-art-3/a-white-jade-archaistic-chilong-disc-qing-dynasty",
    "image_output_stem": "jade_05_qianlong_chilong_disc",
    "currency": "USD",
    "starting_price_basis": "LOW_ESTIMATE_PROXY",
    "image_local_path": null
  }
] as const;

export type EconMindAuctionPreset = (typeof ECONMIND_AUCTION_PRESETS)[number];
