"use client";

import Link from "next/link";
import { Check, Copy, Gavel, LoaderCircle, ShieldCheck } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { useAuth } from "@/components/auth/auth-provider";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { liveAuctionRoomPath, liveAuctionRoomUrl } from "@/lib/live-auction/links";
import { canHostLiveSession } from "@/lib/platform/live-session-access";
import { createLiveAuctionRoom, listLiveAuctionRoomsForAdmin, type CreatedLiveAuctionRoom } from "@/lib/supabase/live-auction";

export function LiveAuctionAdmin() {
  const { user, role, platformRole, loading, openAuth } = useAuth(); const liveSessionHost = canHostLiveSession(role, platformRole);
  const [name, setName] = useState("Live Auction Session"); const [capacity, setCapacity] = useState(30); const [balance, setBalance] = useState(100);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [created, setCreated] = useState<CreatedLiveAuctionRoom | null>(null);
  const [rooms, setRooms] = useState<Awaited<ReturnType<typeof listLiveAuctionRoomsForAdmin>>>([]);
  const refresh = useCallback(async () => { if (!liveSessionHost) return; try { setRooms(await listLiveAuctionRoomsForAdmin()); } catch (caught) { setError(caught instanceof Error ? caught.message : "Live Auction rooms could not be loaded."); } }, [liveSessionHost]);
  useEffect(() => { queueMicrotask(() => { void refresh(); }); }, [refresh]);
  async function create(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { setCreated(await createLiveAuctionRoom(name, capacity, balance)); await refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "The Live Auction room could not be created."); } finally { setBusy(false); } }
  if (loading) return <main className="mx-auto max-w-6xl px-5 py-12 text-sm text-[var(--ink-muted)]">Checking administrator access…</main>;
  if (!user) return <Gate title="Live session host access" detail="Sign in with a Teacher, School Leader, or Platform Admin account to create Live Auction rooms." action={() => openAuth("sign-in")} />;
  if (!liveSessionHost) return <Gate title="Live session host access required" detail="Teachers, School Leaders, and Platform Admins can create a short Live Auction event." />;
  return <main className="mx-auto min-h-screen max-w-6xl px-5 py-12 sm:px-8"><header><p className="text-[10px] font-extrabold uppercase tracking-[.2em] text-[var(--accent)]">Platform administration</p><h1 className="mt-3 flex items-center gap-3 text-4xl font-bold tracking-[-.05em]"><Gavel className="text-[var(--accent)]" /> Live Auction Rooms</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[var(--ink-muted)]">Create a standalone classroom auction. Every room receives one random link plus separate player and administrator codes; the temporary room identity is isolated from EconMind accounts.</p></header><div className="mt-8 grid items-start gap-6 lg:grid-cols-[.85fr_1.15fr]"><Card className="p-6"><h2 className="text-xl font-bold">Create a room</h2><form className="mt-5 grid gap-5" onSubmit={(event) => void create(event)}><Field label="Room name"><input maxLength={120} value={name} onChange={(event) => setName(event.target.value)} required /></Field><Field label="Buyer capacity"><input type="number" min={1} max={100} value={capacity} onChange={(event) => setCapacity(Math.max(1, Math.min(100, Number(event.target.value) || 1)))} /></Field><Field label="Starting balance"><input type="number" min={0} max={1000000} value={balance} onChange={(event) => setBalance(Math.max(0, Number(event.target.value) || 0))} /></Field>{error && <p role="alert" className="rounded-lg bg-[var(--red-soft)] p-3 text-xs text-[var(--red)]">{error}</p>}<Button type="submit" disabled={busy}>{busy && <LoaderCircle className="animate-spin" size={15} />}{busy ? "Creating…" : "Create Live Auction room"}</Button></form>{created && <section className="mt-6 rounded-xl border border-[var(--accent)] bg-[var(--accent-soft)] p-4"><p className="text-xs font-bold text-[var(--accent)]">Share the random room link, then send each invitation code separately. Codes are shown only once.</p><Code label="Player code" value={created.playerCode} /><Code label="Administrator code" value={created.adminCode} /><div className="mt-4 flex flex-wrap gap-2"><Link href={liveAuctionRoomPath(created.room.id)} target="_blank"><Button size="sm">Open room</Button></Link><CopyAction label="Copy room link" value={() => liveAuctionRoomUrl(window.location.origin, created.room.id)} /></div></section>}</Card><section><h2 className="text-xl font-bold">Existing rooms</h2><div className="mt-4 grid gap-3">{rooms.map((room) => <Card key={room.id} className="flex flex-wrap items-center justify-between gap-4 p-5"><div><h3 className="text-lg font-bold">{room.name}</h3><p className="mt-1 text-xs text-[var(--ink-muted)]">{room.participant_count}/{room.participant_capacity} buyers · {room.item_count} items</p></div><Link href={liveAuctionRoomPath(room.id)} target="_blank"><Button size="sm" variant="secondary">Open control room</Button></Link></Card>)}{rooms.length === 0 && <Card className="p-6 text-sm text-[var(--ink-muted)]">No Live Auction rooms have been created yet.</Card>}</div></section></div></main>;
}
function Gate({ title, detail, action }: { title: string; detail: string; action?: () => void }) { return <main className="mx-auto max-w-6xl px-5 py-12"><Card className="max-w-xl p-7"><ShieldCheck className="text-[var(--accent)]" size={22} /><h1 className="mt-4 text-2xl font-bold">{title}</h1><p className="mt-2 text-sm leading-6 text-[var(--ink-muted)]">{detail}</p>{action && <Button className="mt-5" onClick={action}>Sign in</Button>}</Card></main>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-2 text-xs font-bold">{label}<span className="[&_input]:h-10 [&_input]:w-full [&_input]:rounded-lg [&_input]:border [&_input]:border-[var(--line)] [&_input]:bg-[var(--canvas)] [&_input]:px-3 [&_input]:text-sm">{children}</span></label>; }
function Code({ label, value }: { label: string; value: string }) { return <div className="mt-3"><p className="text-[10px] font-extrabold uppercase tracking-[.14em] text-[var(--ink-faint)]">{label}</p><div className="mt-1 flex items-center justify-between gap-2 rounded-lg border border-[var(--line)] bg-[var(--canvas)] px-3 py-2"><code className="text-sm font-bold tracking-wide">{value}</code><CopyAction label={label} value={value} compact /></div></div>; }
function CopyAction({ label, value, compact = false }: { label: string; value: string | (() => string); compact?: boolean }) { const [copied, setCopied] = useState(false); const timer = useRef<number | null>(null); useEffect(() => () => { if (timer.current) window.clearTimeout(timer.current); }, []); async function copy() { try { await navigator.clipboard.writeText(typeof value === "function" ? value() : value); setCopied(true); if (timer.current) window.clearTimeout(timer.current); timer.current = window.setTimeout(() => setCopied(false), 1800); } catch { /* browser will keep the label */ } } return <button type="button" onClick={() => void copy()} className={compact ? "grid size-7 place-items-center rounded-md text-[var(--accent)] hover:bg-[var(--accent-soft)]" : "inline-flex h-9 items-center gap-2 rounded-lg border border-[var(--accent)] px-3 text-xs font-bold text-[var(--accent)] hover:bg-[var(--accent-soft)]"}>{copied ? <Check size={15} /> : <Copy size={15} />}{!compact && (copied ? "Copied" : label)}</button>; }
