export type ModelCategory = "Microeconomics" | "Macroeconomics" | "Strategic Interaction" | "Policy Lab" | "Sandbox";
export type ModelDifficulty = "Beginner" | "Intermediate" | "Advanced";
export type ModelStatus = "available" | "coming-soon";
export type ModelIconKey =
  | "market"
  | "policy"
  | "controls"
  | "elasticity"
  | "externality"
  | "monopoly"
  | "ppf"
  | "macro"
  | "trade"
  | "behavioral"
  | "sandbox";

export type ModelDefinition = {
  slug: string;
  route: string;
  title: string;
  shortTitle: string;
  description: string;
  category: ModelCategory;
  difficulty: ModelDifficulty;
  estimatedMinutes: number;
  prerequisites: string[];
  relatedModels: string[];
  learningObjectives: string[];
  concepts: string[];
  status: ModelStatus;
  icon: ModelIconKey;
  number: string;
};

export const MODEL_REGISTRY = [
  {
    slug: "supply-demand",
    route: "/models/supply-demand",
    title: "Supply & Demand",
    shortTitle: "Market Equilibrium",
    description: "See how buyers and sellers jointly determine equilibrium price, quantity, and economic surplus.",
    category: "Microeconomics",
    difficulty: "Beginner",
    estimatedMinutes: 12,
    prerequisites: [],
    relatedModels: ["elasticity", "policy", "price-controls"],
    learningObjectives: ["Find a competitive equilibrium", "Interpret market shifts", "Measure gains from trade"],
    concepts: ["Equilibrium", "Welfare", "Market shifts"],
    status: "available",
    icon: "market",
    number: "01",
  },
  {
    slug: "policy",
    route: "/models/policy",
    title: "Indirect Tax & Subsidy",
    shortTitle: "Policy Incidence",
    description: "Trace a policy wedge through buyer prices, seller prices, trade volume, public finance, and welfare.",
    category: "Microeconomics",
    difficulty: "Intermediate",
    estimatedMinutes: 15,
    prerequisites: ["supply-demand"],
    relatedModels: ["elasticity", "externalities", "sandbox"],
    learningObjectives: ["Calculate tax incidence", "Compare taxes and subsidies", "Identify deadweight loss"],
    concepts: ["Tax incidence", "Subsidies", "Deadweight loss"],
    status: "available",
    icon: "policy",
    number: "02",
  },
  {
    slug: "price-controls",
    route: "/models/price-controls",
    title: "Price Controls",
    shortTitle: "Ceilings, Floors & Rationing",
    description: "Test when a price ceiling or floor becomes binding and measure shortages, surpluses, and welfare loss.",
    category: "Microeconomics",
    difficulty: "Intermediate",
    estimatedMinutes: 14,
    prerequisites: ["supply-demand"],
    relatedModels: ["policy", "elasticity"],
    learningObjectives: ["Identify binding controls", "Calculate shortages and surpluses", "Explain rationing costs"],
    concepts: ["Price ceiling", "Price floor", "Shortage"],
    status: "available",
    icon: "controls",
    number: "03",
  },
  {
    slug: "elasticity",
    route: "/models/elasticity",
    title: "Elasticity & Revenue",
    shortTitle: "Price Sensitivity",
    description: "Move along a demand curve and discover how local price sensitivity governs total revenue.",
    category: "Microeconomics",
    difficulty: "Beginner",
    estimatedMinutes: 12,
    prerequisites: ["supply-demand"],
    relatedModels: ["policy", "monopoly"],
    learningObjectives: ["Calculate point elasticity", "Classify demand response", "Connect elasticity to revenue"],
    concepts: ["Point elasticity", "Total revenue", "Pricing"],
    status: "available",
    icon: "elasticity",
    number: "04",
  },
  {
    slug: "externalities",
    route: "/models/externalities",
    title: "Externalities",
    shortTitle: "Private and Social Welfare",
    description: "Compare private incentives with social costs and benefits, then derive a corrective policy.",
    category: "Microeconomics",
    difficulty: "Intermediate",
    estimatedMinutes: 18,
    prerequisites: ["supply-demand", "policy"],
    relatedModels: ["policy", "sandbox"],
    learningObjectives: ["Separate private and social curves", "Find the efficient quantity", "Calculate corrective policy"],
    concepts: ["Social cost", "Pigouvian policy", "Welfare"],
    status: "available",
    icon: "externality",
    number: "05",
  },
  {
    slug: "monopoly",
    route: "/models/monopoly",
    title: "Monopoly",
    shortTitle: "Market Power & Markup",
    description: "Compare profit-maximizing monopoly output with a competitive benchmark.",
    category: "Microeconomics",
    difficulty: "Intermediate",
    estimatedMinutes: 18,
    prerequisites: ["elasticity"],
    relatedModels: ["elasticity", "price-controls"],
    learningObjectives: ["Use MR = MC", "Calculate profit", "Measure monopoly deadweight loss"],
    concepts: ["Marginal revenue", "Profit", "Market power"],
    status: "available",
    icon: "monopoly",
    number: "06",
  },
  {
    slug: "ppf",
    route: "/models/ppf",
    title: "Production Possibility Frontier",
    shortTitle: "Scarcity & Opportunity Cost",
    description: "Allocate productive capacity and distinguish efficient, inefficient, and unattainable outcomes.",
    category: "Microeconomics",
    difficulty: "Beginner",
    estimatedMinutes: 14,
    prerequisites: [],
    relatedModels: ["comparative-advantage", "ad-as"],
    learningObjectives: ["Classify production points", "Calculate opportunity cost", "Explain economic growth"],
    concepts: ["Scarcity", "Efficiency", "Growth"],
    status: "available",
    icon: "ppf",
    number: "07",
  },
  {
    slug: "ad-as",
    route: "/models/ad-as",
    title: "Aggregate Demand & Supply",
    shortTitle: "Output, Prices & Gaps",
    description: "Explore simplified demand and supply shocks without presenting the result as a real forecast.",
    category: "Macroeconomics",
    difficulty: "Intermediate",
    estimatedMinutes: 18,
    prerequisites: ["supply-demand", "ppf"],
    relatedModels: ["ppf", "sandbox"],
    learningObjectives: ["Find short-run macro equilibrium", "Identify output gaps", "Distinguish demand and supply inflation"],
    concepts: ["AD", "SRAS", "Output gap"],
    status: "available",
    icon: "macro",
    number: "08",
  },
  {
    slug: "sandbox",
    route: "/sandbox",
    title: "Economic Sandbox",
    shortTitle: "Policy Mix Laboratory",
    description: "Combine simplified fiscal, monetary, market, environmental, and trade policy tools.",
    category: "Sandbox",
    difficulty: "Advanced",
    estimatedMinutes: 20,
    prerequisites: ["supply-demand", "policy"],
    relatedModels: ["policy", "externalities", "ad-as"],
    learningObjectives: ["Combine policy instruments", "Read multi-indicator trade-offs", "Compare scenarios transparently"],
    concepts: ["Policy mix", "Trade-offs", "Scenario analysis"],
    status: "available",
    icon: "sandbox",
    number: "09",
  },
  {
    slug: "is-lm",
    route: "/models/is-lm",
    title: "IS–LM",
    shortTitle: "Goods & Money Markets",
    description: "Solve a transparent joint equilibrium for output and interest rates.",
    category: "Macroeconomics",
    difficulty: "Advanced",
    estimatedMinutes: 22,
    prerequisites: ["ad-as"],
    relatedModels: ["ad-as", "phillips-curve", "sandbox"],
    learningObjectives: ["Solve IS–LM equilibrium", "Trace fiscal and monetary shifts", "Interpret crowding out"],
    concepts: ["Fiscal policy", "Money market", "Interest rate"],
    status: "available",
    icon: "macro",
    number: "18",
  },
  {
    slug: "prisoners-dilemma",
    route: "/models/prisoners-dilemma",
    title: "Prisoner’s Dilemma",
    shortTitle: "Payoffs & Strategic Choice",
    description: "Edit a payoff matrix and identify best responses, Nash equilibria, and efficiency.",
    category: "Strategic Interaction",
    difficulty: "Intermediate",
    estimatedMinutes: 18,
    prerequisites: [],
    relatedModels: ["repeated-games", "cournot"],
    learningObjectives: ["Identify best responses", "Find Nash equilibria", "Compare private and joint incentives"],
    concepts: ["Dominance", "Nash equilibrium", "Pareto efficiency"],
    status: "available",
    icon: "behavioral",
    number: "11",
  },
  {
    slug: "repeated-games",
    route: "/models/repeated-games",
    title: "Repeated Games",
    shortTitle: "Cooperation over Time",
    description: "Compare deterministic strategy rules under future interaction and noise.",
    category: "Strategic Interaction",
    difficulty: "Advanced",
    estimatedMinutes: 20,
    prerequisites: ["prisoners-dilemma"],
    relatedModels: ["prisoners-dilemma", "cournot"],
    learningObjectives: ["Compare strategies", "Read cooperation paths", "Interpret discounting"],
    concepts: ["Tit for Tat", "Punishment", "Discount factor"],
    status: "available",
    icon: "behavioral",
    number: "12",
  },
  {
    slug: "cournot",
    route: "/models/cournot",
    title: "Cournot Competition",
    shortTitle: "Oligopoly Best Responses",
    description: "Compare firm quantities, profits, welfare, and Cournot–Nash equilibrium.",
    category: "Strategic Interaction",
    difficulty: "Advanced",
    estimatedMinutes: 22,
    prerequisites: ["monopoly"],
    relatedModels: ["monopoly", "prisoners-dilemma"],
    learningObjectives: ["Derive best responses", "Find Cournot equilibrium", "Compare market structures"],
    concepts: ["Oligopoly", "Best response", "Market power"],
    status: "available",
    icon: "monopoly",
    number: "13",
  },
  {
    slug: "phillips-curve",
    route: "/models/phillips-curve",
    title: "Phillips Curve",
    shortTitle: "Inflation & Unemployment",
    description: "Separate shifts in the short-run curve from movements along it.",
    category: "Macroeconomics",
    difficulty: "Intermediate",
    estimatedMinutes: 18,
    prerequisites: ["ad-as"],
    relatedModels: ["ad-as", "is-lm"],
    learningObjectives: ["Read SRPC shifts", "Distinguish short and long run", "Interpret supply shocks"],
    concepts: ["Inflation", "Unemployment", "Expectations"],
    status: "available",
    icon: "macro",
    number: "14",
  },
  {
    slug: "solow-growth",
    route: "/models/solow-growth",
    title: "Solow Growth Model",
    shortTitle: "Capital & Steady State",
    description: "Trace capital accumulation, saving, and steady-state output.",
    category: "Macroeconomics",
    difficulty: "Advanced",
    estimatedMinutes: 22,
    prerequisites: ["ppf"],
    relatedModels: ["ad-as", "lorenz-gini"],
    learningObjectives: ["Find a steady state", "Read a transition", "Compare the Golden Rule"],
    concepts: ["Saving", "Capital", "Technology"],
    status: "available",
    icon: "macro",
    number: "15",
  },
  {
    slug: "lorenz-gini",
    route: "/models/lorenz-gini",
    title: "Lorenz Curve & Gini Coefficient",
    shortTitle: "Distribution & Redistribution",
    description: "Calculate a discrete Gini coefficient and compare simple tax-transfer policies.",
    category: "Macroeconomics",
    difficulty: "Intermediate",
    estimatedMinutes: 20,
    prerequisites: [],
    relatedModels: ["policy", "sandbox"],
    learningObjectives: ["Read Lorenz curves", "Calculate Gini", "Evaluate redistribution"],
    concepts: ["Inequality", "Tax", "Transfer"],
    status: "available",
    icon: "trade",
    number: "16",
  },
  {
    slug: "policy-lab",
    route: "/policy-lab",
    title: "Policy Lab",
    shortTitle: "Structured Policy Scenarios",
    description: "Set priorities, make predictions, and test constrained policy packages.",
    category: "Policy Lab",
    difficulty: "Advanced",
    estimatedMinutes: 25,
    prerequisites: ["sandbox"],
    relatedModels: ["sandbox", "ad-as", "externalities"],
    learningObjectives: ["Evaluate trade-offs", "Set policy priorities", "Defend a recommendation"],
    concepts: ["Policy mix", "Constraints", "Stakeholders"],
    status: "available",
    icon: "sandbox",
    number: "17",
  },
  {
    slug: "comparative-advantage",
    route: "/models/comparative-advantage",
    title: "Comparative Advantage",
    shortTitle: "Specialization & Trade",
    description: "Compare opportunity costs and gains from specialization.",
    category: "Microeconomics",
    difficulty: "Intermediate",
    estimatedMinutes: 16,
    prerequisites: ["ppf"],
    relatedModels: ["ppf", "sandbox"],
    learningObjectives: ["Compare opportunity costs", "Choose specialization", "Explain gains from trade"],
    concepts: ["Opportunity cost", "Trade", "Specialization"],
    status: "coming-soon",
    icon: "trade",
    number: "10",
  },
  {
    slug: "behavioral-biases",
    route: "/models/behavioral-biases",
    title: "Behavioral Biases",
    shortTitle: "Choice Under Friction",
    description: "Explore how framing and reference points can influence simplified choices.",
    category: "Strategic Interaction",
    difficulty: "Beginner",
    estimatedMinutes: 12,
    prerequisites: [],
    relatedModels: ["elasticity"],
    learningObjectives: ["Recognize framing", "Explain reference dependence", "Separate description from prediction"],
    concepts: ["Framing", "Reference points", "Choice"],
    status: "coming-soon",
    icon: "behavioral",
    number: "19",
  },
  {
    slug: "labour-market",
    route: "/models/labour-market",
    title: "Labour Market",
    shortTitle: "Wages, Employment & Productivity",
    description: "Connect labour demand, labour supply and marginal productivity in a transparent competitive benchmark.",
    category: "Microeconomics",
    difficulty: "Intermediate",
    estimatedMinutes: 18,
    prerequisites: ["supply-demand"],
    relatedModels: ["minimum-wage", "monopoly"],
    learningObjectives: ["Read labour-market equilibrium", "Compare wage changes", "Interpret employment incentives"],
    concepts: ["Labour demand", "Wage", "Productivity"],
    status: "coming-soon",
    icon: "market",
    number: "20",
  },
  {
    slug: "minimum-wage",
    route: "/models/minimum-wage",
    title: "Minimum Wage",
    shortTitle: "Wage Floors & Employment",
    description: "Compare a binding wage floor with competitive and employer-power benchmarks.",
    category: "Microeconomics",
    difficulty: "Intermediate",
    estimatedMinutes: 18,
    prerequisites: ["labour-market"],
    relatedModels: ["labour-market", "monopoly"],
    learningObjectives: ["Identify a binding floor", "Read employment effects", "State model limits"],
    concepts: ["Wage floor", "Employment", "Monopsony"],
    status: "coming-soon",
    icon: "controls",
    number: "21",
  },
  {
    slug: "consumer-choice",
    route: "/models/consumer-choice",
    title: "Consumer Choice",
    shortTitle: "Budget Sets & Preferences",
    description: "Use a budget constraint and simple preferences to reason about consumption choices.",
    category: "Microeconomics",
    difficulty: "Intermediate",
    estimatedMinutes: 17,
    prerequisites: ["supply-demand"],
    relatedModels: ["elasticity", "behavioral-biases"],
    learningObjectives: ["Read budget sets", "Identify an optimum", "Separate income and substitution effects"],
    concepts: ["Utility", "Budget constraint", "Substitution"],
    status: "coming-soon",
    icon: "market",
    number: "22",
  },
  {
    slug: "firm-production-costs",
    route: "/models/firm-production-costs",
    title: "Firm Production & Costs",
    shortTitle: "Technology, Cost & Output",
    description: "Relate production technology to short-run costs and the firm’s output decision.",
    category: "Microeconomics",
    difficulty: "Intermediate",
    estimatedMinutes: 18,
    prerequisites: ["supply-demand"],
    relatedModels: ["monopoly", "labour-market"],
    learningObjectives: ["Classify costs", "Read marginal cost", "Connect output to profit"],
    concepts: ["Production", "Marginal cost", "Fixed cost"],
    status: "coming-soon",
    icon: "market",
    number: "23",
  },
  {
    slug: "public-goods",
    route: "/models/public-goods",
    title: "Public Goods",
    shortTitle: "Free Riding & Provision",
    description: "Make non-rivalry, non-excludability and the collective-action problem observable.",
    category: "Microeconomics",
    difficulty: "Intermediate",
    estimatedMinutes: 17,
    prerequisites: ["externalities"],
    relatedModels: ["externalities", "prisoners-dilemma"],
    learningObjectives: ["Recognise public goods", "Explain free riding", "Compare provision rules"],
    concepts: ["Public good", "Free rider", "Collective action"],
    status: "coming-soon",
    icon: "externality",
    number: "24",
  },
  {
    slug: "information-asymmetry",
    route: "/models/information-asymmetry",
    title: "Information Asymmetry",
    shortTitle: "Adverse Selection & Signals",
    description: "Trace how unequal information can alter prices, quality and market participation.",
    category: "Microeconomics",
    difficulty: "Advanced",
    estimatedMinutes: 20,
    prerequisites: ["supply-demand"],
    relatedModels: ["behavioral-biases", "policy"],
    learningObjectives: ["Identify information gaps", "Explain adverse selection", "Evaluate a signal"],
    concepts: ["Information", "Screening", "Signalling"],
    status: "coming-soon",
    icon: "behavioral",
    number: "25",
  },
  {
    slug: "mixed-strategies",
    route: "/models/mixed-strategies",
    title: "Mixed Strategies",
    shortTitle: "Randomisation in Games",
    description: "Find a mixed-strategy equilibrium when predictable actions invite an opponent response.",
    category: "Strategic Interaction",
    difficulty: "Advanced",
    estimatedMinutes: 19,
    prerequisites: ["prisoners-dilemma"],
    relatedModels: ["prisoners-dilemma", "repeated-games"],
    learningObjectives: ["Read a payoff matrix", "Calculate mixing probabilities", "Interpret strategic uncertainty"],
    concepts: ["Mixed strategy", "Equilibrium", "Payoffs"],
    status: "coming-soon",
    icon: "behavioral",
    number: "26",
  },
  {
    slug: "exchange-rates",
    route: "/models/exchange-rates",
    title: "Exchange Rates",
    shortTitle: "Currency Markets & Pass-through",
    description: "Connect currency demand and supply to trade prices and simplified inflation pass-through.",
    category: "Macroeconomics",
    difficulty: "Advanced",
    estimatedMinutes: 20,
    prerequisites: ["ad-as"],
    relatedModels: ["comparative-advantage", "balance-of-payments"],
    learningObjectives: ["Read appreciation and depreciation", "Trace pass-through", "State open-economy limits"],
    concepts: ["Exchange rate", "Imports", "Competitiveness"],
    status: "coming-soon",
    icon: "trade",
    number: "27",
  },
  {
    slug: "balance-of-payments",
    route: "/models/balance-of-payments",
    title: "Balance of Payments",
    shortTitle: "Trade, Income & Capital Flows",
    description: "Organise current-account and financial-account flows without treating a teaching identity as a forecast.",
    category: "Macroeconomics",
    difficulty: "Advanced",
    estimatedMinutes: 20,
    prerequisites: ["comparative-advantage"],
    relatedModels: ["exchange-rates", "ad-as"],
    learningObjectives: ["Classify external flows", "Read account identities", "Interpret financing"],
    concepts: ["Current account", "Capital flows", "Reserves"],
    status: "coming-soon",
    icon: "trade",
    number: "28",
  },
  {
    slug: "fiscal-multiplier",
    route: "/models/fiscal-multiplier",
    title: "Fiscal Multiplier",
    shortTitle: "Spending, Tax & Output",
    description: "Compare simplified spending and tax multipliers while keeping leakages and capacity constraints visible.",
    category: "Macroeconomics",
    difficulty: "Intermediate",
    estimatedMinutes: 18,
    prerequisites: ["ad-as"],
    relatedModels: ["is-lm", "policy-lab"],
    learningObjectives: ["Calculate a multiplier", "Compare instruments", "Identify leakages"],
    concepts: ["Multiplier", "Fiscal policy", "Aggregate demand"],
    status: "coming-soon",
    icon: "macro",
    number: "29",
  },
  {
    slug: "monetary-policy",
    route: "/models/monetary-policy",
    title: "Monetary Policy Transmission",
    shortTitle: "Rates, Credit & Demand",
    description: "Trace a policy-rate change through borrowing costs, demand and inflation pressure.",
    category: "Macroeconomics",
    difficulty: "Advanced",
    estimatedMinutes: 20,
    prerequisites: ["is-lm"],
    relatedModels: ["is-lm", "phillips-curve"],
    learningObjectives: ["Trace transmission", "Compare lags", "Interpret trade-offs"],
    concepts: ["Interest rate", "Credit", "Inflation"],
    status: "coming-soon",
    icon: "macro",
    number: "30",
  },
  {
    slug: "unemployment",
    route: "/models/unemployment",
    title: "Unemployment Dynamics",
    shortTitle: "Flows, Matching & Cycles",
    description: "Separate job destruction, matching and participation in a simple labour-market flow model.",
    category: "Macroeconomics",
    difficulty: "Intermediate",
    estimatedMinutes: 18,
    prerequisites: ["labour-market"],
    relatedModels: ["phillips-curve", "minimum-wage"],
    learningObjectives: ["Read labour flows", "Compare cyclical and structural forces", "Interpret matching"],
    concepts: ["Unemployment", "Vacancies", "Matching"],
    status: "coming-soon",
    icon: "macro",
    number: "31",
  },
  {
    slug: "inflation-expectations",
    route: "/models/inflation-expectations",
    title: "Inflation Expectations",
    shortTitle: "Credibility & Price Setting",
    description: "Show how expected inflation changes a short-run inflation-output trade-off.",
    category: "Macroeconomics",
    difficulty: "Advanced",
    estimatedMinutes: 19,
    prerequisites: ["phillips-curve"],
    relatedModels: ["phillips-curve", "monetary-policy"],
    learningObjectives: ["Separate expected and realised inflation", "Read credibility", "Explain curve shifts"],
    concepts: ["Expectations", "Credibility", "Inflation"],
    status: "coming-soon",
    icon: "macro",
    number: "32",
  },
  {
    slug: "public-debt",
    route: "/models/public-debt",
    title: "Public Debt Dynamics",
    shortTitle: "Debt, Interest & Primary Balances",
    description: "Use the debt-ratio identity to study how growth, interest costs and fiscal balances interact over time.",
    category: "Macroeconomics",
    difficulty: "Advanced",
    estimatedMinutes: 20,
    prerequisites: ["fiscal-multiplier"],
    relatedModels: ["policy-lab", "is-lm"],
    learningObjectives: ["Read debt dynamics", "Compare primary balances", "State sustainability conditions"],
    concepts: ["Debt ratio", "Interest", "Primary balance"],
    status: "coming-soon",
    icon: "policy",
    number: "33",
  },
  {
    slug: "human-capital-growth",
    route: "/models/human-capital-growth",
    title: "Human Capital & Growth",
    shortTitle: "Skills, Productivity & Time",
    description: "Explore how education and skill accumulation affect productive capacity with gradual lags.",
    category: "Macroeconomics",
    difficulty: "Intermediate",
    estimatedMinutes: 18,
    prerequisites: ["solow-growth"],
    relatedModels: ["solow-growth", "ppf"],
    learningObjectives: ["Trace delayed effects", "Compare investments", "Interpret productivity"],
    concepts: ["Human capital", "Productivity", "Growth"],
    status: "coming-soon",
    icon: "macro",
    number: "34",
  },
  {
    slug: "climate-transition",
    route: "/models/climate-transition",
    title: "Climate Transition",
    shortTitle: "Abatement, Investment & Distribution",
    description: "Compare a stylised transition path across emissions, investment, prices and household protection.",
    category: "Policy Lab",
    difficulty: "Advanced",
    estimatedMinutes: 22,
    prerequisites: ["externalities", "policy-lab"],
    relatedModels: ["externalities", "sandbox"],
    learningObjectives: ["Compare transition instruments", "Read time lags", "Assess distributional trade-offs"],
    concepts: ["Climate policy", "Investment", "Equity"],
    status: "coming-soon",
    icon: "externality",
    number: "35",
  },
] as const satisfies readonly ModelDefinition[];

export type ModelSlug = (typeof MODEL_REGISTRY)[number]["slug"];

export const AVAILABLE_MODELS = MODEL_REGISTRY.filter((model) => model.status === "available");
export const getModel = (slug: string) => MODEL_REGISTRY.find((model) => model.slug === slug);
export const getAvailableModel = (slug: string) => AVAILABLE_MODELS.find((model) => model.slug === slug);
export const getModelsByCategory = (category: ModelCategory) => MODEL_REGISTRY.filter((model) => model.category === category);
