export type ModelCategory = "Microeconomics" | "Macroeconomics" | "Strategic Interaction" | "Policy Lab" | "Sandbox";
export type ModelDifficulty = "Beginner" | "Intermediate" | "Advanced";
export type ModelStatus = "available" | "coming-soon";
export type ModelIconKey =
  | "market"
  | "policy"
  | "controls"
  | "elasticity"
  | "externality"
  | "monopoly"
  | "ppf"
  | "macro"
  | "trade"
  | "behavioral"
  | "sandbox";

export type ModelDefinition = {
  slug: string;
  route: string;
  title: string;
  shortTitle: string;
  description: string;
  category: ModelCategory;
  difficulty: ModelDifficulty;
  estimatedMinutes: number;
  prerequisites: string[];
  relatedModels: string[];
  learningObjectives: string[];
  concepts: string[];
  status: ModelStatus;
  icon: ModelIconKey;
  number: string;
};

export const MODEL_REGISTRY = [
  {
    slug: "supply-demand",
    route: "/models/supply-demand",
    title: "Supply & Demand",
    shortTitle: "Market Equilibrium",
    description: "See how buyers and sellers jointly determine equilibrium price, quantity, and economic surplus.",
    category: "Microeconomics",
    difficulty: "Beginner",
    estimatedMinutes: 12,
    prerequisites: [],
    relatedModels: ["elasticity", "policy", "price-controls"],
    learningObjectives: ["Find a competitive equilibrium", "Interpret market shifts", "Measure gains from trade"],
    concepts: ["Equilibrium", "Welfare", "Market shifts"],
    status: "available",
    icon: "market",
    number: "01",
  },
  {
    slug: "policy",
    route: "/models/policy",
    title: "Indirect Tax & Subsidy",
    shortTitle: "Policy Incidence",
    description: "Trace a policy wedge through buyer prices, seller prices, trade volume, public finance, and welfare.",
    category: "Microeconomics",
    difficulty: "Intermediate",
    estimatedMinutes: 15,
    prerequisites: ["supply-demand"],
    relatedModels: ["elasticity", "externalities", "sandbox"],
    learningObjectives: ["Calculate tax incidence", "Compare taxes and subsidies", "Identify deadweight loss"],
    concepts: ["Tax incidence", "Subsidies", "Deadweight loss"],
    status: "available",
    icon: "policy",
    number: "02",
  },
  {
    slug: "price-controls",
    route: "/models/price-controls",
    title: "Price Controls",
    shortTitle: "Ceilings, Floors & Rationing",
    description: "Test when a price ceiling or floor becomes binding and measure shortages, surpluses, and welfare loss.",
    category: "Microeconomics",
    difficulty: "Intermediate",
    estimatedMinutes: 14,
    prerequisites: ["supply-demand"],
    relatedModels: ["policy", "elasticity"],
    learningObjectives: ["Identify binding controls", "Calculate shortages and surpluses", "Explain rationing costs"],
    concepts: ["Price ceiling", "Price floor", "Shortage"],
    status: "available",
    icon: "controls",
    number: "03",
  },
  {
    slug: "elasticity",
    route: "/models/elasticity",
    title: "Elasticity & Revenue",
    shortTitle: "Price Sensitivity",
    description: "Move along a demand curve and discover how local price sensitivity governs total revenue.",
    category: "Microeconomics",
    difficulty: "Beginner",
    estimatedMinutes: 12,
    prerequisites: ["supply-demand"],
    relatedModels: ["policy", "monopoly"],
    learningObjectives: ["Calculate point elasticity", "Classify demand response", "Connect elasticity to revenue"],
    concepts: ["Point elasticity", "Total revenue", "Pricing"],
    status: "available",
    icon: "elasticity",
    number: "04",
  },
  {
    slug: "externalities",
    route: "/models/externalities",
    title: "Externalities",
    shortTitle: "Private and Social Welfare",
    description: "Compare private incentives with social costs and benefits, then derive a corrective policy.",
    category: "Microeconomics",
    difficulty: "Intermediate",
    estimatedMinutes: 18,
    prerequisites: ["supply-demand", "policy"],
    relatedModels: ["policy", "sandbox"],
    learningObjectives: ["Separate private and social curves", "Find the efficient quantity", "Calculate corrective policy"],
    concepts: ["Social cost", "Pigouvian policy", "Welfare"],
    status: "available",
    icon: "externality",
    number: "05",
  },
  {
    slug: "monopoly",
    route: "/models/monopoly",
    title: "Monopoly",
    shortTitle: "Market Power & Markup",
    description: "Compare profit-maximizing monopoly output with a competitive benchmark.",
    category: "Microeconomics",
    difficulty: "Intermediate",
    estimatedMinutes: 18,
    prerequisites: ["elasticity"],
    relatedModels: ["elasticity", "price-controls"],
    learningObjectives: ["Use MR = MC", "Calculate profit", "Measure monopoly deadweight loss"],
    concepts: ["Marginal revenue", "Profit", "Market power"],
    status: "available",
    icon: "monopoly",
    number: "06",
  },
  {
    slug: "ppf",
    route: "/models/ppf",
    title: "Production Possibility Frontier",
    shortTitle: "Scarcity & Opportunity Cost",
    description: "Allocate productive capacity and distinguish efficient, inefficient, and unattainable outcomes.",
    category: "Microeconomics",
    difficulty: "Beginner",
    estimatedMinutes: 14,
    prerequisites: [],
    relatedModels: ["comparative-advantage", "ad-as"],
    learningObjectives: ["Classify production points", "Calculate opportunity cost", "Explain economic growth"],
    concepts: ["Scarcity", "Efficiency", "Growth"],
    status: "available",
    icon: "ppf",
    number: "07",
  },
  {
    slug: "ad-as",
    route: "/models/ad-as",
    title: "Aggregate Demand & Supply",
    shortTitle: "Output, Prices & Gaps",
    description: "Explore simplified demand and supply shocks without presenting the result as a real forecast.",
    category: "Macroeconomics",
    difficulty: "Intermediate",
    estimatedMinutes: 18,
    prerequisites: ["supply-demand", "ppf"],
    relatedModels: ["ppf", "sandbox"],
    learningObjectives: ["Find short-run macro equilibrium", "Identify output gaps", "Distinguish demand and supply inflation"],
    concepts: ["AD", "SRAS", "Output gap"],
    status: "available",
    icon: "macro",
    number: "08",
  },
  {
    slug: "sandbox",
    route: "/sandbox",
    title: "Economic Sandbox",
    shortTitle: "Policy Mix Laboratory",
    description: "Combine simplified fiscal, monetary, market, environmental, and trade policy tools.",
    category: "Sandbox",
    difficulty: "Advanced",
    estimatedMinutes: 20,
    prerequisites: ["supply-demand", "policy"],
    relatedModels: ["policy", "externalities", "ad-as"],
    learningObjectives: ["Combine policy instruments", "Read multi-indicator trade-offs", "Compare scenarios transparently"],
    concepts: ["Policy mix", "Trade-offs", "Scenario analysis"],
    status: "available",
    icon: "sandbox",
    number: "09",
  },
  {
    slug: "is-lm",
    route: "/models/is-lm",
    title: "IS–LM",
    shortTitle: "Goods & Money Markets",
    description: "Solve a transparent joint equilibrium for output and interest rates.",
    category: "Macroeconomics",
    difficulty: "Advanced",
    estimatedMinutes: 22,
    prerequisites: ["ad-as"],
    relatedModels: ["ad-as", "phillips-curve", "sandbox"],
    learningObjectives: ["Solve IS–LM equilibrium", "Trace fiscal and monetary shifts", "Interpret crowding out"],
    concepts: ["Fiscal policy", "Money market", "Interest rate"],
    status: "available",
    icon: "macro",
    number: "10",
  },
  {
    slug: "prisoners-dilemma",
    route: "/models/prisoners-dilemma",
    title: "Prisoner’s Dilemma",
    shortTitle: "Payoffs & Strategic Choice",
    description: "Edit a payoff matrix and identify best responses, Nash equilibria, and efficiency.",
    category: "Strategic Interaction",
    difficulty: "Intermediate",
    estimatedMinutes: 18,
    prerequisites: [],
    relatedModels: ["repeated-games", "cournot"],
    learningObjectives: ["Identify best responses", "Find Nash equilibria", "Compare private and joint incentives"],
    concepts: ["Dominance", "Nash equilibrium", "Pareto efficiency"],
    status: "available",
    icon: "behavioral",
    number: "11",
  },
  {
    slug: "repeated-games",
    route: "/models/repeated-games",
    title: "Repeated Games",
    shortTitle: "Cooperation over Time",
    description: "Compare deterministic strategy rules under future interaction and noise.",
    category: "Strategic Interaction",
    difficulty: "Advanced",
    estimatedMinutes: 20,
    prerequisites: ["prisoners-dilemma"],
    relatedModels: ["prisoners-dilemma", "cournot"],
    learningObjectives: ["Compare strategies", "Read cooperation paths", "Interpret discounting"],
    concepts: ["Tit for Tat", "Punishment", "Discount factor"],
    status: "available",
    icon: "behavioral",
    number: "12",
  },
  {
    slug: "cournot",
    route: "/models/cournot",
    title: "Cournot Competition",
    shortTitle: "Oligopoly Best Responses",
    description: "Compare firm quantities, profits, welfare, and Cournot–Nash equilibrium.",
    category: "Strategic Interaction",
    difficulty: "Advanced",
    estimatedMinutes: 22,
    prerequisites: ["monopoly"],
    relatedModels: ["monopoly", "prisoners-dilemma"],
    learningObjectives: ["Derive best responses", "Find Cournot equilibrium", "Compare market structures"],
    concepts: ["Oligopoly", "Best response", "Market power"],
    status: "available",
    icon: "monopoly",
    number: "13",
  },
  {
    slug: "phillips-curve",
    route: "/models/phillips-curve",
    title: "Phillips Curve",
    shortTitle: "Inflation & Unemployment",
    description: "Separate shifts in the short-run curve from movements along it.",
    category: "Macroeconomics",
    difficulty: "Intermediate",
    estimatedMinutes: 18,
    prerequisites: ["ad-as"],
    relatedModels: ["ad-as", "is-lm"],
    learningObjectives: ["Read SRPC shifts", "Distinguish short and long run", "Interpret supply shocks"],
    concepts: ["Inflation", "Unemployment", "Expectations"],
    status: "available",
    icon: "macro",
    number: "14",
  },
  {
    slug: "solow-growth",
    route: "/models/solow-growth",
    title: "Solow Growth Model",
    shortTitle: "Capital & Steady State",
    description: "Trace capital accumulation, saving, and steady-state output.",
    category: "Macroeconomics",
    difficulty: "Advanced",
    estimatedMinutes: 22,
    prerequisites: ["ppf"],
    relatedModels: ["ad-as", "lorenz-gini"],
    learningObjectives: ["Find a steady state", "Read a transition", "Compare the Golden Rule"],
    concepts: ["Saving", "Capital", "Technology"],
    status: "available",
    icon: "macro",
    number: "15",
  },
  {
    slug: "lorenz-gini",
    route: "/models/lorenz-gini",
    title: "Lorenz Curve & Gini Coefficient",
    shortTitle: "Distribution & Redistribution",
    description: "Calculate a discrete Gini coefficient and compare simple tax-transfer policies.",
    category: "Macroeconomics",
    difficulty: "Intermediate",
    estimatedMinutes: 20,
    prerequisites: [],
    relatedModels: ["policy", "sandbox"],
    learningObjectives: ["Read Lorenz curves", "Calculate Gini", "Evaluate redistribution"],
    concepts: ["Inequality", "Tax", "Transfer"],
    status: "available",
    icon: "trade",
    number: "16",
  },
  {
    slug: "policy-lab",
    route: "/policy-lab",
    title: "Policy Lab",
    shortTitle: "Structured Policy Scenarios",
    description: "Set priorities, make predictions, and test constrained policy packages.",
    category: "Policy Lab",
    difficulty: "Advanced",
    estimatedMinutes: 25,
    prerequisites: ["sandbox"],
    relatedModels: ["sandbox", "ad-as", "externalities"],
    learningObjectives: ["Evaluate trade-offs", "Set policy priorities", "Defend a recommendation"],
    concepts: ["Policy mix", "Constraints", "Stakeholders"],
    status: "available",
    icon: "sandbox",
    number: "17",
  },
  {
    slug: "comparative-advantage",
    route: "/models/comparative-advantage",
    title: "Comparative Advantage",
    shortTitle: "Specialization & Trade",
    description: "Compare opportunity costs and gains from specialization.",
    category: "Microeconomics",
    difficulty: "Intermediate",
    estimatedMinutes: 16,
    prerequisites: ["ppf"],
    relatedModels: ["ppf", "sandbox"],
    learningObjectives: ["Compare opportunity costs", "Choose specialization", "Explain gains from trade"],
    concepts: ["Opportunity cost", "Trade", "Specialization"],
    status: "available",
    icon: "trade",
    number: "18",
  },
  {
    slug: "labour-market",
    route: "/models/labour-market",
    title: "Labour Market",
    shortTitle: "Wages & Employment",
    description: "Solve a competitive labour-market equilibrium from labour demand and supply schedules.",
    category: "Microeconomics",
    difficulty: "Intermediate",
    estimatedMinutes: 18,
    prerequisites: ["supply-demand"],
    relatedModels: ["monopsony", "policy"],
    learningObjectives: ["Solve for a wage", "Find employment", "State the competitive benchmark"],
    concepts: ["Labour demand", "Labour supply", "Wage"],
    status: "available",
    icon: "market",
    number: "19",
  },
  {
    slug: "monopsony",
    route: "/models/monopsony",
    title: "Monopsony",
    shortTitle: "Employer Wage Setting",
    description: "Compare marginal revenue product, labour supply and marginal expenditure for a wage-setting employer.",
    category: "Microeconomics",
    difficulty: "Advanced",
    estimatedMinutes: 20,
    prerequisites: ["labour-market"],
    relatedModels: ["labour-market", "monopoly"],
    learningObjectives: ["Derive marginal expenditure", "Find monopsony employment", "Compare wage and MRP"],
    concepts: ["Monopsony", "Marginal expenditure", "MRP"],
    status: "available",
    icon: "market",
    number: "20",
  },
  {
    slug: "public-goods",
    route: "/models/public-goods",
    title: "Public Goods",
    shortTitle: "Free Riding & Provision",
    description: "Calculate individual payoff from a shared contribution and make the free-rider incentive visible.",
    category: "Microeconomics",
    difficulty: "Intermediate",
    estimatedMinutes: 17,
    prerequisites: ["externalities"],
    relatedModels: ["prisoners-dilemma", "policy"],
    learningObjectives: ["Calculate payoff", "Identify free riding", "Compare private and group incentives"],
    concepts: ["Public good", "Free rider", "Contribution"],
    status: "available",
    icon: "externality",
    number: "21",
  },
  {
    slug: "common-pool-resources",
    route: "/models/common-pool-resources",
    title: "Common-Pool Resources",
    shortTitle: "Stock, Growth & Harvest",
    description: "Trace how collective harvest changes a renewable stock under a stated logistic growth rule.",
    category: "Microeconomics",
    difficulty: "Advanced",
    estimatedMinutes: 20,
    prerequisites: ["public-goods"],
    relatedModels: ["public-goods", "policy-lab"],
    learningObjectives: ["Calculate next stock", "Compare harvest pressure", "Recognise collapse risk"],
    concepts: ["Common pool", "Stock", "Sustainability"],
    status: "available",
    icon: "externality",
    number: "22",
  },
  {
    slug: "information-asymmetry",
    route: "/models/information-asymmetry",
    title: "Information Asymmetry",
    shortTitle: "Posterior Value & Signals",
    description: "Use posterior probabilities to calculate the value implied by an imperfect signal.",
    category: "Microeconomics",
    difficulty: "Advanced",
    estimatedMinutes: 18,
    prerequisites: ["supply-demand"],
    relatedModels: ["adverse-selection", "signalling"],
    learningObjectives: ["Weight a posterior", "Interpret signal quality", "Separate information from certainty"],
    concepts: ["Signal", "Posterior", "Expected value"],
    status: "available",
    icon: "behavioral",
    number: "23",
  },
  {
    slug: "adverse-selection",
    route: "/models/adverse-selection",
    title: "Adverse Selection",
    shortTitle: "Risk Types & Pooling",
    description: "Calculate a pooled premium when risk type is privately known before coverage is chosen.",
    category: "Microeconomics",
    difficulty: "Advanced",
    estimatedMinutes: 18,
    prerequisites: ["information-asymmetry"],
    relatedModels: ["information-asymmetry", "moral-hazard"],
    learningObjectives: ["Calculate a fair premium", "Identify selection risk", "State pooling limits"],
    concepts: ["Risk pool", "Premium", "Private information"],
    status: "available",
    icon: "behavioral",
    number: "24",
  },
  {
    slug: "moral-hazard",
    route: "/models/moral-hazard",
    title: "Moral Hazard",
    shortTitle: "Effort, Coverage & Loss",
    description: "Compare the value of prevention with its effort cost when action is not directly observable.",
    category: "Microeconomics",
    difficulty: "Advanced",
    estimatedMinutes: 18,
    prerequisites: ["adverse-selection"],
    relatedModels: ["adverse-selection", "signalling"],
    learningObjectives: ["Calculate prevention value", "Compare incentives", "State observability limits"],
    concepts: ["Effort", "Insurance", "Incentives"],
    status: "available",
    icon: "behavioral",
    number: "25",
  },
  {
    slug: "signalling",
    route: "/models/signalling",
    title: "Signalling",
    shortTitle: "Separating Conditions",
    description: "Test whether a costly signal can separate types when its cost differs across them.",
    category: "Microeconomics",
    difficulty: "Advanced",
    estimatedMinutes: 18,
    prerequisites: ["information-asymmetry"],
    relatedModels: ["information-asymmetry", "adverse-selection"],
    learningObjectives: ["Read separating inequalities", "Compare signal costs", "State what the signal reveals"],
    concepts: ["Signalling", "Screening", "Types"],
    status: "available",
    icon: "behavioral",
    number: "26",
  },
  {
    slug: "keynesian-multiplier",
    route: "/models/keynesian-multiplier",
    title: "Keynesian Multiplier",
    shortTitle: "Demand, Leakages & Output",
    description: "Calculate the short-run output response to spending when taxes and imports are stated leakages.",
    category: "Macroeconomics",
    difficulty: "Intermediate",
    estimatedMinutes: 18,
    prerequisites: ["ad-as"],
    relatedModels: ["fiscal-policy", "is-lm"],
    learningObjectives: ["Calculate a multiplier", "Identify leakages", "Interpret demand slack"],
    concepts: ["Multiplier", "Imports", "Taxes"],
    status: "available",
    icon: "macro",
    number: "27",
  },
  {
    slug: "monetary-policy",
    route: "/models/monetary-policy",
    title: "Monetary Policy Rule",
    shortTitle: "Inflation & Output-Gap Response",
    description: "Calculate a transparent policy-rule setting from inflation and output-gap inputs.",
    category: "Macroeconomics",
    difficulty: "Advanced",
    estimatedMinutes: 20,
    prerequisites: ["ad-as"],
    relatedModels: ["phillips-curve", "is-lm"],
    learningObjectives: ["Apply a stated rule", "Separate inflation and output inputs", "State rule limitations"],
    concepts: ["Policy rate", "Inflation target", "Output gap"],
    status: "available",
    icon: "macro",
    number: "28",
  },
  {
    slug: "fiscal-policy",
    route: "/models/fiscal-policy",
    title: "Fiscal Policy",
    shortTitle: "Spending, Taxes & Output",
    description: "Compare the stated spending and tax channels in a short-run fiscal-output calculation.",
    category: "Macroeconomics",
    difficulty: "Intermediate",
    estimatedMinutes: 18,
    prerequisites: ["ad-as"],
    relatedModels: ["is-lm", "policy-lab"],
    learningObjectives: ["Calculate a multiplier", "Compare instruments", "Identify leakages"],
    concepts: ["Multiplier", "Fiscal policy", "Aggregate demand"],
    status: "available",
    icon: "macro",
    number: "29",
  },
  {
    slug: "public-debt",
    route: "/models/public-debt",
    title: "Public Debt Dynamics",
    shortTitle: "Debt, Interest & Primary Balances",
    description: "Use the debt-ratio identity to compare growth, interest costs and primary balances.",
    category: "Macroeconomics",
    difficulty: "Advanced",
    estimatedMinutes: 20,
    prerequisites: ["fiscal-policy"],
    relatedModels: ["fiscal-policy", "keynesian-multiplier"],
    learningObjectives: ["Calculate next debt", "Compare r and g", "Interpret primary balances"],
    concepts: ["Debt ratio", "Interest", "Primary balance"],
    status: "available",
    icon: "policy",
    number: "30",
  },
  {
    slug: "business-cycle",
    route: "/models/business-cycle",
    title: "Business Cycle",
    shortTitle: "Output Gap & Okun’s Law",
    description: "Calculate an output gap and the associated stated Okun-law unemployment change.",
    category: "Macroeconomics",
    difficulty: "Intermediate",
    estimatedMinutes: 18,
    prerequisites: ["ad-as"],
    relatedModels: ["phillips-curve", "labour-market"],
    learningObjectives: ["Calculate an output gap", "Apply Okun's relationship", "State potential-output uncertainty"],
    concepts: ["Output gap", "Unemployment", "Potential output"],
    status: "available",
    icon: "macro",
    number: "31",
  },
  {
    slug: "money-market",
    route: "/models/money-market",
    title: "Money Market",
    shortTitle: "Real Balances & Interest",
    description: "Solve a money-demand equation for the interest rate that clears a stated real money balance.",
    category: "Macroeconomics",
    difficulty: "Advanced",
    estimatedMinutes: 19,
    prerequisites: ["is-lm"],
    relatedModels: ["is-lm", "monetary-policy"],
    learningObjectives: ["Solve money-market clearing", "Interpret real balances", "Compare income sensitivity"],
    concepts: ["Money demand", "Interest", "Real balances"],
    status: "available",
    icon: "macro",
    number: "32",
  },
  {
    slug: "loanable-funds",
    route: "/models/loanable-funds",
    title: "Loanable Funds",
    shortTitle: "Saving, Investment & Deficits",
    description: "Solve the interest rate that clears saving against investment plus a government deficit.",
    category: "Macroeconomics",
    difficulty: "Advanced",
    estimatedMinutes: 20,
    prerequisites: ["supply-demand"],
    relatedModels: ["public-debt", "money-market"],
    learningObjectives: ["Solve a clearing rate", "Trace deficits", "State closed-economy limits"],
    concepts: ["Saving", "Investment", "Deficit"],
    status: "available",
    icon: "macro",
    number: "33",
  },
  {
    slug: "bank-credit-creation",
    route: "/models/bank-credit-creation",
    title: "Bank Credit Creation",
    shortTitle: "Reserves & Deposit Ceiling",
    description: "Calculate the textbook upper bound on deposits created from an injected reserve amount.",
    category: "Macroeconomics",
    difficulty: "Intermediate",
    estimatedMinutes: 18,
    prerequisites: ["money-market"],
    relatedModels: ["money-market", "monetary-policy"],
    learningObjectives: ["Calculate the deposit ceiling", "Interpret the reserve ratio", "State leakage limits"],
    concepts: ["Reserves", "Deposits", "Multiplier"],
    status: "available",
    icon: "macro",
    number: "34",
  },
  {
    slug: "tariffs",
    route: "/models/tariffs",
    title: "Tariffs",
    shortTitle: "Trade Wedges & Revenue",
    description: "Calculate a small-country tariff wedge, domestic price and revenue from stated imports.",
    category: "Macroeconomics",
    difficulty: "Intermediate",
    estimatedMinutes: 17,
    prerequisites: ["comparative-advantage"],
    relatedModels: ["policy", "comparative-advantage"],
    learningObjectives: ["Calculate a tariff price", "Calculate revenue", "State partial-equilibrium assumptions"],
    concepts: ["Tariff", "Trade", "Revenue"],
    status: "available",
    icon: "trade",
    number: "35",
  },
] as const satisfies readonly ModelDefinition[];

export type ModelSlug = (typeof MODEL_REGISTRY)[number]["slug"];

export const AVAILABLE_MODELS = MODEL_REGISTRY.filter((model) => model.status === "available");
export const getModel = (slug: string) => MODEL_REGISTRY.find((model) => model.slug === slug);
export const getAvailableModel = (slug: string) => AVAILABLE_MODELS.find((model) => model.slug === slug);
export const getModelsByCategory = (category: ModelCategory) => MODEL_REGISTRY.filter((model) => model.category === category);
