"use client";

import { useEffect, useState } from "react";
import { LoaderCircle, Trophy } from "lucide-react";
import { LEAGUE_CHALLENGE_CATALOG } from "@/lib/economics/league-arena";
import type { LeagueChallenge, LeagueLeaderboardRow } from "@/lib/league/async-challenge-types";
import { getLeagueChallengeLeaderboard, listLeagueChallenges } from "@/lib/supabase/league-challenges";

export function LeagueStandings() {
  const [selected, setSelected] = useState(LEAGUE_CHALLENGE_CATALOG[0]?.slug ?? "");
  const [challenges, setChallenges] = useState<LeagueChallenge[]>([]);
  const [rows, setRows] = useState<LeagueLeaderboardRow[]>([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { void listLeagueChallenges().then(setChallenges).catch(() => setChallenges([])); }, []);
  useEffect(() => { queueMicrotask(() => { setLoading(true); void getLeagueChallengeLeaderboard(selected).then(setRows).catch(() => setRows([])).finally(() => setLoading(false)); }); }, [selected]);
  const configured = challenges.find((challenge) => challenge.slug === selected);
  const definition = LEAGUE_CHALLENGE_CATALOG.find((challenge) => challenge.slug === selected);
  return <main className="mx-auto min-h-screen max-w-[1240px] px-5 py-10 sm:px-8 lg:px-12"><header><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[var(--accent)]">Released League results</p><h1 className="mt-2 text-4xl font-bold tracking-[-.06em]">Standings</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--ink-muted)]">Rankings are Team-first. Each Challenge uses a deterministic Performance Score out of 100 and keeps a Team’s highest official attempt.</p></header><div className="mt-8 flex flex-wrap gap-2" role="tablist" aria-label="Challenge standings">{LEAGUE_CHALLENGE_CATALOG.map((challenge) => <button type="button" role="tab" aria-selected={selected === challenge.slug} key={challenge.slug} onClick={() => setSelected(challenge.slug)} className={`rounded-lg px-4 py-2 text-sm font-bold ${selected === challenge.slug ? "bg-[var(--accent)] text-white" : "border border-[var(--line)] text-[var(--ink-muted)]"}`}>{challenge.eyebrow}</button>)}</div><section className="mt-8 overflow-hidden rounded-xl border border-[var(--line)]"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[var(--line)] bg-[var(--surface-subtle)] px-5 py-4"><div><p className="text-sm font-bold">{definition?.title}</p><p className="mt-1 text-xs text-[var(--ink-muted)]">{configured?.status === "closed" ? "Challenge closed · full results released" : "Open Challenge · released scores only; active strategies remain private"}</p></div><Trophy className="text-[var(--accent)]" size={20} /></div>{loading ? <div className="grid min-h-52 place-items-center"><LoaderCircle className="animate-spin text-[var(--accent)]" /></div> : rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b border-[var(--line)] text-[10px] font-bold uppercase tracking-[.13em] text-[var(--ink-faint)]"><tr><th className="px-5 py-4">Rank</th><th className="px-5 py-4">Team</th><th className="px-5 py-4">School</th><th className="px-5 py-4">Challenges</th><th className="px-5 py-4 text-right">Performance score</th></tr></thead><tbody>{rows.map((row) => <tr key={row.team_id} className="border-b border-[var(--line)] last:border-0"><td className="px-5 py-4 font-bold text-[var(--accent)]">{row.rank}</td><td className="px-5 py-4 font-bold">{row.team_name}</td><td className="px-5 py-4 text-[var(--ink-muted)]">{row.school_name}</td><td className="px-5 py-4">{row.challenges_completed}</td><td className="px-5 py-4 text-right font-mono font-bold">{Number(row.performance_score).toFixed(1)} / 100</td></tr>)}</tbody></table></div> : <p className="p-8 text-sm leading-6 text-[var(--ink-muted)]">No released official Team result is available for this Challenge yet. The absence of a row never exposes teams’ in-progress policies or Ghost parameters.</p>}</section></main>;
}
