import Link from "next/link";
import { ArrowRight, BarChart3, BookOpenCheck, CircleDotDashed, FlaskConical, Globe2, Newspaper, Scale } from "lucide-react";

const directories = [
  { title: "Real World", copy: "Read current economic context and investigate structured applied cases.", icon: Newspaper, links: [{ href: "/daily-brief", label: "Daily Brief" }, { href: "/cases", label: "Real-World Cases" }, { href: "/cases/history", label: "Case history" }] },
  { title: "Models", copy: "Move from a claim to its assumptions, equations, diagrams and interpretation.", icon: CircleDotDashed, links: [{ href: "/models", label: "Model Library" }, { href: "/mechanism-arena", label: "Mechanism Design Arena" }, { href: "/models/practice", label: "Model Practice" }] },
  { title: "Simulation & Policy", copy: "Use controlled, real-time teaching simulations to trace policy transmission.", icon: BarChart3, links: [{ href: "/sandbox", label: "Economic Sandbox" }, { href: "/policy-lab", label: "Policy Lab" }, { href: "/workspace", label: "Integrated Workspace" }] },
  { title: "Practice & Assessment", copy: "Apply mechanisms to bounded questions and receive transparent feedback.", icon: Scale, links: [{ href: "/econbench", label: "EconBench" }, { href: "/experiments", label: "Experiments" }, { href: "/models/practice", label: "Model questions" }] },
  { title: "Evidence & Research", copy: "Test a model against curated evidence and make the limits part of the conclusion.", icon: FlaskConical, links: [{ href: "/research", label: "Evidence Lab" }, { href: "/research", label: "Curated projects" }] },
  { title: "Network", copy: "Learn with school teams in a persistent fictional world economy.", icon: Globe2, links: [{ href: "/league", label: "League home" }, { href: "/league/join", label: "Join a school team" }, { href: "/league/world", label: "World Simulation" }] },
] as const;

export default function ExplorePage() {
  return <main className="explore-directory"><section className="mx-auto max-w-[1560px] px-5 pb-12 pt-16 sm:px-8 lg:px-12 lg:pb-20 lg:pt-24"><p className="home-eyebrow">EconMind operating-system launcher</p><h1>Explore the tools behind an economic argument.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-[var(--ink-muted)]">Choose the kind of question you want to investigate. Each destination preserves the difference between a simplified model, a simulation outcome and real-world evidence.</p><div className="mt-10 flex flex-wrap items-center gap-3 text-[11px] font-extrabold uppercase tracking-[.14em] text-[var(--ink-faint)]"><span>Real World</span><ArrowRight size={14} /><span>Model</span><ArrowRight size={14} /><span>Simulate</span><ArrowRight size={14} /><span>Evidence</span><ArrowRight size={14} /><span>Decide</span></div></section><section className="border-y border-[var(--line)] bg-[var(--surface)]"><div className="mx-auto grid max-w-[1560px] gap-px px-5 py-5 sm:px-8 md:grid-cols-2 lg:grid-cols-3 lg:px-12 lg:py-12">{directories.map((directory, index) => { const Icon = directory.icon; return <section key={directory.title} className="explore-directory-card"><div className="flex items-start justify-between gap-5"><span className="text-[11px] font-extrabold tracking-[.16em] text-[var(--ink-faint)]">{String(index + 1).padStart(2, "0")}</span><Icon size={22} className="text-[var(--accent)]" /></div><h2>{directory.title}</h2><p>{directory.copy}</p><ul>{directory.links.map((link) => <li key={`${directory.title}-${link.href}-${link.label}`}><Link href={link.href}>{link.label} <ArrowRight size={14} /></Link></li>)}</ul></section>; })}</div></section><section className="mx-auto grid max-w-[1560px] gap-6 px-5 py-14 sm:px-8 lg:grid-cols-[1fr_auto] lg:px-12 lg:py-20"><div><p className="home-eyebrow">A disciplined distinction</p><h2 className="max-w-3xl text-3xl font-bold tracking-[-.05em] sm:text-5xl">A model can clarify a mechanism. It cannot replace evidence or a decision.</h2></div><Link href="/research" className="home-primary-action self-end">Test in Evidence Lab <BookOpenCheck size={17} /></Link></section></main>;
}
