/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: c02e0fbb4c030001fa9d06c9711ebdbf)
interface __BaseEnv_Env {
	MANAGEMENT_FORWARD_TO_JSON: string;
	INBOUND_MAIL_WEBHOOK_SECRET: string;
	INBOUND_MAIL_INGEST_URL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "MANAGEMENT_FORWARD_TO_JSON" | "INBOUND_MAIL_WEBHOOK_SECRET" | "INBOUND_MAIL_INGEST_URL">> {}
}
