import sourceSuite from "@/data/final-world-teaching/extended_model_test_suite.json";
import type { EquationStep, ModelParameter } from "@/lib/economics/types";
import type { ModelSlug } from "@/lib/models/registry";

type Values = Record<string, number>;
type SourceTest = { id: string; input: Record<string, unknown>; expected: Record<string, unknown>; tolerance: number };

export const EXTENDED_MODEL_SOURCE_TESTS = sourceSuite.models as SourceTest[];

export const EXTENDED_MODEL_SLUGS = [
  "comparative-advantage", "labour-market", "monopsony", "public-goods", "common-pool-resources", "information-asymmetry", "adverse-selection", "moral-hazard", "signalling", "keynesian-multiplier", "monetary-policy", "fiscal-policy", "public-debt", "business-cycle", "money-market", "loanable-funds", "bank-credit-creation", "tariffs",
] as const satisfies readonly ModelSlug[];

export type ExtendedModelSlug = (typeof EXTENDED_MODEL_SLUGS)[number];

export type ExtendedCalculation = {
  results: Record<string, number>;
  labels: Record<string, string>;
  primaryKey: string;
  interpretation: string;
  equations: EquationStep[];
};

export type ExtendedModelDefinition = {
  slug: ExtendedModelSlug;
  sourceId: string;
  formula: string;
  principle: string;
  assumptions: string[];
  limitations: string[];
  controls: ModelParameter[];
  sensitivityKey: string;
  calculate: (values: Values) => ExtendedCalculation;
};

const n = (value: number, digits = 6) => Number(value.toFixed(digits));
const c = (id: string, label: string, symbol: string, min: number, max: number, step: number, defaultValue: number, description: string): ModelParameter => ({ id, label, symbol, min, max, step, defaultValue, description });
const definition = (item: Omit<ExtendedModelDefinition, "calculate"> & { calculate: (values: Values) => ExtendedCalculation }): ExtendedModelDefinition => item;

export const EXTENDED_MODEL_DEFINITIONS: Record<ExtendedModelSlug, ExtendedModelDefinition> = {
  "comparative-advantage": definition({
    slug: "comparative-advantage", sourceId: "comparative_advantage", formula: "OC_X = a_LX / a_LY", principle: "Specialise in the good with the lower opportunity cost, not necessarily the higher absolute productivity.",
    assumptions: ["Two economies produce two goods with constant unit labour requirements.", "Labour is the only input and production coefficients do not change."], limitations: ["The model does not determine the terms of trade.", "It omits transport costs, scale economies and distributional adjustment."],
    controls: [c("aX", "A labour for X", "aAX", 0.5, 12, 0.5, 2, "Units of labour economy A needs for one unit of X."), c("aY", "A labour for Y", "aAY", 0.5, 12, 0.5, 4, "Units of labour economy A needs for one unit of Y."), c("bX", "B labour for X", "aBX", 0.5, 12, 0.5, 6, "Units of labour economy B needs for one unit of X."), c("bY", "B labour for Y", "aBY", 0.5, 12, 0.5, 3, "Units of labour economy B needs for one unit of Y.")], sensitivityKey: "aX",
    calculate: (p) => { const ocA = p.aX / p.aY; const ocB = p.bX / p.bY; const aAdvantage = ocA < ocB ? 1 : 0; return { results: { opportunityCostA: n(ocA), opportunityCostB: n(ocB), aHasXAdvantage: aAdvantage, gap: n(Math.abs(ocB - ocA)) }, labels: { opportunityCostA: "A opportunity cost of X", opportunityCostB: "B opportunity cost of X", aHasXAdvantage: "A has X advantage", gap: "Opportunity-cost gap" }, primaryKey: "gap", interpretation: aAdvantage ? "Economy A has the lower opportunity cost of X, so the model assigns A comparative advantage in X." : ocA > ocB ? "Economy B has the lower opportunity cost of X, so the model assigns B comparative advantage in X." : "The two economies have equal opportunity cost of X in this calibration.", equations: [{ label: "Opportunity costs", expression: `OC_X^A = ${p.aX}/${p.aY} = ${n(ocA)}; OC_X^B = ${p.bX}/${p.bY} = ${n(ocB)}` }, { label: "Comparison", expression: `Lower OC_X: ${aAdvantage ? "A" : ocA > ocB ? "B" : "tie"}` }] }; },
  }),
  "labour-market": definition({
    slug: "labour-market", sourceId: "labour_market", formula: "L_d = a − bw; L_s = c + dw", principle: "A competitive wage clears labour demand and labour supply under the stated schedules.",
    assumptions: ["Workers and jobs are homogeneous in the displayed market.", "No single worker or firm has wage-setting power."], limitations: ["This is not a monopsony or search-and-matching model.", "It does not identify a real policy wage effect."],
    controls: [c("demandIntercept", "Labour-demand intercept", "a", 20, 180, 5, 100, "Workers demanded when the wage is zero."), c("demandSlope", "Labour-demand slope", "b", 0.2, 6, 0.1, 2, "Demand reduction per one GCU/hour wage rise."), c("supplyIntercept", "Labour-supply intercept", "c", 0, 80, 5, 20, "Workers supplied when the wage is zero."), c("supplySlope", "Labour-supply slope", "d", 0.1, 6, 0.1, 1, "Supply increase per one GCU/hour wage rise.")], sensitivityKey: "demandIntercept",
    calculate: (p) => { const wage = (p.demandIntercept - p.supplyIntercept) / (p.demandSlope + p.supplySlope); const employment = p.demandIntercept - p.demandSlope * wage; return { results: { wage: n(wage), employment: n(employment), labourDemandAtWage: n(employment), labourSupplyAtWage: n(p.supplyIntercept + p.supplySlope * wage) }, labels: { wage: "Equilibrium wage", employment: "Employment", labourDemandAtWage: "Labour demanded", labourSupplyAtWage: "Labour supplied" }, primaryKey: "employment", interpretation: `At ${n(wage)} GCU per hour, the two stated schedules clear at ${n(employment)} workers.`, equations: [{ label: "Schedules", expression: `L_d = ${p.demandIntercept} − ${p.demandSlope}w; L_s = ${p.supplyIntercept} + ${p.supplySlope}w` }, { label: "Clearing wage", expression: `w* = (a − c)/(b + d) = ${n(wage)}` }, { label: "Employment", expression: `L* = ${p.demandIntercept} − ${p.demandSlope}(${n(wage)}) = ${n(employment)}` }] }; },
  }),
  monopsony: definition({
    slug: "monopsony", sourceId: "monopsony", formula: "w(L)=a+bL; ME=a+2bL; MRP=ME", principle: "A wage-setting employer hires where marginal revenue product equals marginal expenditure, not where it equals the wage.",
    assumptions: ["One employer faces an upward-sloping labour supply curve.", "Marginal revenue product is fixed over the displayed range."], limitations: ["The model does not estimate employer power in a real labour market.", "It omits hours, bargaining, mobility and institutional wage floors."],
    controls: [c("mrp", "Marginal revenue product", "MRP", 5, 80, 1, 30, "Value of the marginal worker's product."), c("supplyIntercept", "Supply intercept", "a", 0, 30, 1, 5, "Base wage in the labour-supply schedule."), c("supplySlope", "Supply slope", "b", 0.02, 0.8, 0.02, 0.1, "Wage increase needed for one more worker.")], sensitivityKey: "mrp",
    calculate: (p) => { const employment = Math.max(0, (p.mrp - p.supplyIntercept) / (2 * p.supplySlope)); const wage = p.supplyIntercept + p.supplySlope * employment; const marginalExpenditure = p.supplyIntercept + 2 * p.supplySlope * employment; return { results: { employment: n(employment), wage: n(wage), marginalExpenditure: n(marginalExpenditure), wageGapToMrp: n(p.mrp - wage) }, labels: { employment: "Monopsony employment", wage: "Monopsony wage", marginalExpenditure: "Marginal expenditure", wageGapToMrp: "MRP − wage" }, primaryKey: "employment", interpretation: `The employer hires ${n(employment)} workers where marginal expenditure equals MRP, and pays a wage below MRP in this benchmark.`, equations: [{ label: "Labour supply", expression: `w(L) = ${p.supplyIntercept} + ${p.supplySlope}L` }, { label: "Hiring condition", expression: `${p.mrp} = ${p.supplyIntercept} + 2(${p.supplySlope})L` }, { label: "Result", expression: `L* = ${n(employment)}; w* = ${n(wage)}` }] }; },
  }),
  "public-goods": definition({
    slug: "public-goods", sourceId: "public_goods", formula: "π_i=e_i−c_i+(m/n)Σc_j", principle: "A contributor receives only a fraction of the public return, creating a free-rider incentive when m<n.",
    assumptions: ["Each player receives the same share of the public return.", "Contributions and the multiplier are known to all participants."], limitations: ["It does not predict social norms or repeated-game punishment.", "It does not value heterogeneous benefits."],
    controls: [c("endowment", "Endowment", "e", 1, 40, 1, 10, "Private endowment per player."), c("players", "Players", "n", 2, 12, 1, 4, "Number of equal participants."), c("multiplier", "Public multiplier", "m", 0.1, 4, 0.1, 1.6, "Total return per unit contributed."), c("contribution", "Contribution each", "c", 0, 40, 1, 10, "Equal contribution by every player.")], sensitivityKey: "contribution",
    calculate: (p) => { const total = p.players * p.contribution; const payoff = p.endowment - p.contribution + p.multiplier * total / p.players; const groupPayoff = p.players * payoff; return { results: { payoffEach: n(payoff), totalContribution: n(total), groupPayoff: n(groupPayoff), freeRiderIncentive: p.multiplier < p.players ? 1 : 0 }, labels: { payoffEach: "Payoff per player", totalContribution: "Total contribution", groupPayoff: "Group payoff", freeRiderIncentive: "Free-rider incentive" }, primaryKey: "payoffEach", interpretation: p.multiplier < p.players ? "Each individual captures less than the full return from a contribution, so the stated parameters contain a free-rider incentive." : "The stated multiplier removes the standard free-rider condition in this simple setup.", equations: [{ label: "Public account", expression: `Σc = ${p.players} × ${p.contribution} = ${n(total)}` }, { label: "Individual payoff", expression: `π_i = ${p.endowment} − ${p.contribution} + (${p.multiplier}/${p.players})(${n(total)}) = ${n(payoff)}` }] }; },
  }),
  "common-pool-resources": definition({
    slug: "common-pool-resources", sourceId: "common_pool_resources", formula: "S′=S+rS(1−S/K)−H", principle: "Harvest competes with biological stock growth; sustained pressure can deplete the stock.",
    assumptions: ["Growth follows the displayed logistic relationship.", "Harvest is observable and cannot make stock negative."], limitations: ["The model does not allocate harvest among individuals.", "Ecological parameters are teaching values, not field estimates."],
    controls: [c("stock", "Opening stock", "S", 1, 300, 1, 100, "Resource stock at the start of the period."), c("growthRate", "Growth rate", "r", 0, 1, 0.01, 0.3, "Logistic regeneration rate."), c("capacity", "Carrying capacity", "K", 20, 500, 5, 200, "Maximum stock supported by the environment."), c("harvest", "Total harvest", "H", 0, 250, 1, 40, "Units removed this period.")], sensitivityKey: "harvest",
    calculate: (p) => { const growth = p.growthRate * p.stock * (1 - p.stock / p.capacity); const next = Math.max(0, p.stock + growth - p.harvest); return { results: { nextStock: n(next), naturalGrowth: n(growth), harvest: n(p.harvest), exhausted: next === 0 ? 1 : 0 }, labels: { nextStock: "Next-period stock", naturalGrowth: "Natural growth", harvest: "Harvest", exhausted: "Exhausted" }, primaryKey: "nextStock", interpretation: next === 0 ? "The selected harvest exhausts the stock in this period." : `The stock changes from ${p.stock} to ${n(next)} after growth and harvest.`, equations: [{ label: "Natural growth", expression: `rS(1−S/K) = ${p.growthRate}×${p.stock}×(1−${p.stock}/${p.capacity}) = ${n(growth)}` }, { label: "Next stock", expression: `S′ = ${p.stock} + ${n(growth)} − ${p.harvest} = ${n(next)}` }] }; },
  }),
  "information-asymmetry": definition({
    slug: "information-asymmetry", sourceId: "information_asymmetry", formula: "E[v|signal]=Σp(type|signal)v_type", principle: "A signal changes value through posterior weights, not by making uncertainty disappear.",
    assumptions: ["The two posterior probabilities are mutually exclusive and exhaustive.", "Values conditional on type are known in the teaching example."], limitations: ["The model does not infer posterior beliefs from raw evidence.", "It does not establish causality from an information signal."],
    controls: [c("probabilityHigh", "High-type posterior", "p_H", 0, 1, 0.05, 0.7, "Posterior probability of the high-value type."), c("highValue", "High-type value", "v_H", 0, 200, 5, 100, "Value conditional on high type."), c("lowValue", "Low-type value", "v_L", 0, 200, 5, 40, "Value conditional on low type.")], sensitivityKey: "probabilityHigh",
    calculate: (p) => { const lowProbability = 1 - p.probabilityHigh; const expected = p.probabilityHigh * p.highValue + lowProbability * p.lowValue; return { results: { expectedValue: n(expected), highWeight: n(p.probabilityHigh), lowWeight: n(lowProbability), valueSpread: n(p.highValue - p.lowValue) }, labels: { expectedValue: "Posterior expected value", highWeight: "High-type posterior", lowWeight: "Low-type posterior", valueSpread: "Type-value spread" }, primaryKey: "expectedValue", interpretation: `The signal-weighted expected value is ${n(expected)} GCU; uncertainty remains because both types retain probability weight.`, equations: [{ label: "Posterior weights", expression: `p_H=${p.probabilityHigh}; p_L=1−p_H=${n(lowProbability)}` }, { label: "Expected value", expression: `E[v|s] = ${p.probabilityHigh}(${p.highValue}) + ${n(lowProbability)}(${p.lowValue}) = ${n(expected)}` }] }; },
  }),
  "adverse-selection": definition({
    slug: "adverse-selection", sourceId: "adverse_selection", formula: "P_pool=E[p_iL]+loading", principle: "A pooled premium reflects the risk mix; selection can change that mix after prices are set.",
    assumptions: ["Two risk types are privately known before coverage is chosen.", "The displayed premium has no administrative loading."], limitations: ["The model cannot predict which types actually enter a market.", "It omits regulation, underwriting and correlated risk."],
    controls: [c("lowRisk", "Low-risk probability", "p_L", 0, 1, 0.01, 0.1, "Probability of loss for low-risk people."), c("highRisk", "High-risk probability", "p_H", 0, 1, 0.01, 0.4, "Probability of loss for high-risk people."), c("lowRiskShare", "Low-risk share", "ω_L", 0, 1, 0.05, 0.5, "Share of low-risk people in the pool."), c("loss", "Loss if insured event occurs", "L", 10, 500, 10, 100, "Loss amount under either risk type.")], sensitivityKey: "lowRiskShare",
    calculate: (p) => { const averageRisk = p.lowRiskShare * p.lowRisk + (1 - p.lowRiskShare) * p.highRisk; const premium = averageRisk * p.loss; return { results: { fairPremium: n(premium), averageRisk: n(averageRisk), highRiskShare: n(1 - p.lowRiskShare), riskGap: n(p.highRisk - p.lowRisk) }, labels: { fairPremium: "Fair pooled premium", averageRisk: "Average loss probability", highRiskShare: "High-risk share", riskGap: "Risk-probability gap" }, primaryKey: "fairPremium", interpretation: `With the displayed mix, a zero-loading pooled premium is ${n(premium)} GCU per policy.`, equations: [{ label: "Average risk", expression: `p̄ = ${p.lowRiskShare}(${p.lowRisk}) + ${n(1 - p.lowRiskShare)}(${p.highRisk}) = ${n(averageRisk)}` }, { label: "Fair premium", expression: `P_pool = p̄L = ${n(averageRisk)}×${p.loss} = ${n(premium)}` }] }; },
  }),
  "moral-hazard": definition({
    slug: "moral-hazard", sourceId: "moral_hazard", formula: "Prevention value=(p_before−p_after)L−effort cost", principle: "When effort changes loss risk but cannot be observed directly, coverage can weaken prevention incentives.",
    assumptions: ["Effort changes only the stated loss probability.", "The loss and effort cost are known teaching values."], limitations: ["The model does not choose an optimal insurance contract.", "It omits risk aversion, monitoring and repeated relationships."],
    controls: [c("probabilityBefore", "Loss probability without effort", "p_0", 0, 1, 0.01, 0.4, "Loss probability before preventive effort."), c("probabilityAfter", "Loss probability with effort", "p_1", 0, 1, 0.01, 0.3, "Loss probability after preventive effort."), c("loss", "Loss", "L", 10, 500, 10, 100, "Loss amount avoided probabilistically."), c("effortCost", "Effort cost", "C_e", 0, 100, 1, 2, "Private cost of prevention.")], sensitivityKey: "effortCost",
    calculate: (p) => { const gross = (p.probabilityBefore - p.probabilityAfter) * p.loss; const net = gross - p.effortCost; return { results: { preventionNetValue: n(net), preventionGrossValue: n(gross), chooseEffort: net > 0 ? 1 : 0, probabilityReduction: n(p.probabilityBefore - p.probabilityAfter) }, labels: { preventionNetValue: "Net prevention value", preventionGrossValue: "Gross avoided loss", chooseEffort: "Effort justified", probabilityReduction: "Probability reduction" }, primaryKey: "preventionNetValue", interpretation: net > 0 ? "The stated prevention effort has a positive private net value." : "The stated prevention effort does not cover its private cost in this simple calculation.", equations: [{ label: "Avoided expected loss", expression: `(${p.probabilityBefore}−${p.probabilityAfter})×${p.loss} = ${n(gross)}` }, { label: "Net prevention value", expression: `${n(gross)}−${p.effortCost} = ${n(net)}` }] }; },
  }),
  signalling: definition({
    slug: "signalling", sourceId: "signalling", formula: "c_H(s)−c_H(0)<w_H−w_L<c_L(s)−c_L(0)", principle: "A signal can separate types only when it is sufficiently cheaper for the high type.",
    assumptions: ["Employers observe the signal but not the underlying type.", "Signal costs differ by type and wages reflect the stated gap."], limitations: ["The model does not determine equilibrium wages.", "It omits noisy signals and screening technology."],
    controls: [c("wageGap", "Wage gap", "w_H−w_L", 0, 60, 1, 20, "Wage advantage of the high type."), c("highCost", "High-type signal cost", "c_H", 0, 60, 1, 5, "Signal cost for high type."), c("lowCost", "Low-type signal cost", "c_L", 0, 60, 1, 25, "Signal cost for low type.")], sensitivityKey: "wageGap",
    calculate: (p) => { const separates = p.highCost < p.wageGap && p.wageGap < p.lowCost; const lowerSlack = p.wageGap - p.highCost; const upperSlack = p.lowCost - p.wageGap; return { results: { separatingSignalExists: separates ? 1 : 0, lowerConditionSlack: n(lowerSlack), upperConditionSlack: n(upperSlack), signalCostGap: n(p.lowCost - p.highCost) }, labels: { separatingSignalExists: "Separating signal exists", lowerConditionSlack: "Above high-cost bound", upperConditionSlack: "Below low-cost bound", signalCostGap: "Signal-cost gap" }, primaryKey: "signalCostGap", interpretation: separates ? "The wage gap lies between the high- and low-type signal costs, so a separating signal exists under the stated inequality." : "At least one separating-condition inequality fails in the displayed values.", equations: [{ label: "Separating test", expression: `${p.highCost} < ${p.wageGap} < ${p.lowCost}` }, { label: "Result", expression: `Separating signal = ${separates ? "true" : "false"}` }] }; },
  }),
  "keynesian-multiplier": definition({
    slug: "keynesian-multiplier", sourceId: "keynesian_multiplier", formula: "k=1/[1−c(1−t)+m]; ΔY=kΔG", principle: "Spending rounds create induced demand, while taxes and imports are leakages from those rounds.",
    assumptions: ["There is unused productive capacity in the short run.", "Consumption, tax and import propensities stay fixed over the displayed change."], limitations: ["It is not a forecast or a full macroeconomic model.", "It omits prices, interest rates, debt and expectations."],
    controls: [c("consumptionPropensity", "Consumption propensity", "c", 0, 0.95, 0.05, 0.75, "Fraction of disposable income spent."), c("taxRate", "Tax rate", "t", 0, 0.7, 0.05, 0.2, "Leakage through taxation."), c("importPropensity", "Import propensity", "m", 0, 0.7, 0.05, 0.1, "Leakage through imports."), c("spendingChange", "Government-spending change", "ΔG", -50, 80, 1, 10, "Initial fiscal demand change.")], sensitivityKey: "spendingChange",
    calculate: (p) => { const multiplier = 1 / (1 - p.consumptionPropensity * (1 - p.taxRate) + p.importPropensity); const output = multiplier * p.spendingChange; return { results: { multiplier: n(multiplier), outputChange: n(output), taxLeakage: n(p.consumptionPropensity * p.taxRate), importLeakage: n(p.importPropensity) }, labels: { multiplier: "Multiplier", outputChange: "Output change", taxLeakage: "Tax leakage", importLeakage: "Import leakage" }, primaryKey: "outputChange", interpretation: `The displayed leakages yield a multiplier of ${n(multiplier)}; a ${p.spendingChange} GCU demand change gives ${n(output)} GCU in the model.`, equations: [{ label: "Multiplier", expression: `k = 1/[1−${p.consumptionPropensity}(1−${p.taxRate})+${p.importPropensity}] = ${n(multiplier)}` }, { label: "Output response", expression: `ΔY = ${n(multiplier)}×${p.spendingChange} = ${n(output)}` }] }; },
  }),
  "monetary-policy": definition({
    slug: "monetary-policy", sourceId: "monetary_policy", formula: "i=r*+φπ(π−π*)+φy·ygap", principle: "A stated rule responds to the gap between inflation and target and to the output gap; it is not an unconditional optimum.",
    assumptions: ["The displayed rule is a policy approximation.", "Inflation and output-gap measures use a compatible period and definition."], limitations: ["The rule does not forecast policy decisions.", "It omits exchange rates, financial stability and discretionary judgement."],
    controls: [c("neutralRate", "Neutral real rate", "r*", -2, 8, 0.5, 1, "Rule intercept."), c("inflation", "Inflation", "π", -2, 15, 0.5, 4, "Current inflation reading."), c("targetInflation", "Inflation target", "π*", -2, 10, 0.5, 2, "Target inflation reading."), c("inflationResponse", "Inflation response", "φπ", 0, 3, 0.1, 0.5, "Rule response to inflation gap."), c("outputResponse", "Output-gap response", "φy", 0, 3, 0.1, 0.5, "Rule response to output gap."), c("outputGap", "Output gap", "ygap", -10, 10, 0.5, -1, "Output gap in percentage points.")], sensitivityKey: "inflation",
    calculate: (p) => { const inflationGap = p.inflation - p.targetInflation; const rate = p.neutralRate + p.inflationResponse * inflationGap + p.outputResponse * p.outputGap; return { results: { policyRate: n(rate), inflationGap: n(inflationGap), inflationContribution: n(p.inflationResponse * inflationGap), outputContribution: n(p.outputResponse * p.outputGap) }, labels: { policyRate: "Rule policy rate", inflationGap: "Inflation gap", inflationContribution: "Inflation contribution", outputContribution: "Output contribution" }, primaryKey: "policyRate", interpretation: `The stated rule returns ${n(rate)} percentage points, conditional on the supplied inflation and output-gap readings.`, equations: [{ label: "Rule", expression: `i = ${p.neutralRate} + ${p.inflationResponse}(${p.inflation}−${p.targetInflation}) + ${p.outputResponse}(${p.outputGap})` }, { label: "Current setting", expression: `i = ${n(rate)}` }] }; },
  }),
  "fiscal-policy": definition({
    slug: "fiscal-policy", sourceId: "fiscal_policy", formula: "ΔY=k_GΔG+k_TΔT; k_T=−c·k_G", principle: "A spending impulse and a tax change have distinct signs in the stated simple multiplier model.",
    assumptions: ["Prices and interest rates are fixed in the short-run teaching benchmark.", "The tax multiplier equals −c times the spending multiplier."], limitations: ["The model omits financing and debt dynamics.", "Multiplier values are not empirical estimates."],
    controls: [c("consumptionPropensity", "Consumption propensity", "c", 0, 0.95, 0.05, 0.75, "Used for the simple tax multiplier."), c("spendingMultiplier", "Spending multiplier", "k_G", 0, 4, 0.1, 1.5, "Output response per unit of ΔG."), c("spendingChange", "Spending change", "ΔG", -50, 80, 1, 10, "Government-spending change."), c("taxChange", "Tax change", "ΔT", -50, 80, 1, 4, "Tax increase; positive values reduce the result through k_T.")], sensitivityKey: "spendingChange",
    calculate: (p) => { const taxMultiplier = -p.consumptionPropensity * p.spendingMultiplier; const output = p.spendingMultiplier * p.spendingChange + taxMultiplier * p.taxChange; return { results: { outputChange: n(output), taxMultiplier: n(taxMultiplier), spendingContribution: n(p.spendingMultiplier * p.spendingChange), taxContribution: n(taxMultiplier * p.taxChange) }, labels: { outputChange: "Output change", taxMultiplier: "Tax multiplier", spendingContribution: "Spending contribution", taxContribution: "Tax contribution" }, primaryKey: "outputChange", interpretation: `The stated fiscal package changes output by ${n(output)} GCU in the short-run model.`, equations: [{ label: "Tax multiplier", expression: `k_T = −${p.consumptionPropensity}×${p.spendingMultiplier} = ${n(taxMultiplier)}` }, { label: "Fiscal response", expression: `ΔY = ${p.spendingMultiplier}(${p.spendingChange}) + ${n(taxMultiplier)}(${p.taxChange}) = ${n(output)}` }] }; },
  }),
  "public-debt": definition({
    slug: "public-debt", sourceId: "public_debt", formula: "d_t=((1+r)/(1+g))d_{t−1}−pb_t", principle: "Debt dynamics depend on the interest-growth differential and the primary balance using a compatible period.",
    assumptions: ["Debt, primary balance, interest and growth use compatible period definitions.", "The primary balance is a surplus when positive."], limitations: ["The accounting identity does not predict market access or default.", "It omits valuation effects, maturity and contingent liabilities."],
    controls: [c("previousDebt", "Previous debt ratio", "d_(t−1)", 0, 3, 0.01, 0.8, "Debt/GDP ratio in decimal form."), c("interestRate", "Interest rate", "r", -0.05, 0.25, 0.01, 0.06, "Compatible-period interest rate."), c("growthRate", "Growth rate", "g", -0.1, 0.25, 0.01, 0.03, "Compatible-period nominal growth rate."), c("primaryBalance", "Primary surplus", "pb", -0.2, 0.2, 0.01, 0.01, "Primary surplus/GDP; negative is a deficit.")], sensitivityKey: "primaryBalance",
    calculate: (p) => { const snowball = (1 + p.interestRate) / (1 + p.growthRate); const next = snowball * p.previousDebt - p.primaryBalance; return { results: { nextDebtRatio: n(next, 4), snowballFactor: n(snowball, 4), debtChange: n(next - p.previousDebt, 4), interestGrowthGap: n(p.interestRate - p.growthRate, 4) }, labels: { nextDebtRatio: "Next debt/GDP", snowballFactor: "Snowball factor", debtChange: "Debt-ratio change", interestGrowthGap: "r − g" }, primaryKey: "nextDebtRatio", interpretation: next > p.previousDebt ? "The displayed parameters raise the debt ratio in this one-period accounting result." : "The displayed parameters lower the debt ratio in this one-period accounting result.", equations: [{ label: "Snowball factor", expression: `(1+r)/(1+g) = (1+${p.interestRate})/(1+${p.growthRate}) = ${n(snowball, 4)}` }, { label: "Next debt", expression: `d_t = ${n(snowball, 4)}×${p.previousDebt}−${p.primaryBalance} = ${n(next, 4)}` }] }; },
  }),
  "business-cycle": definition({
    slug: "business-cycle", sourceId: "business_cycle", formula: "ygap=(Y−Yp)/Yp; Δu=−βΔygap", principle: "A gap is measured relative to estimated potential output; Okun's relationship maps a change in that gap into a stated unemployment change.",
    assumptions: ["Potential output is a benchmark estimate, not directly observed.", "The supplied Okun coefficient is stable over this small change."], limitations: ["The model cannot identify structural unemployment.", "It does not forecast a real business cycle."],
    controls: [c("actualOutput", "Actual output", "Y", 20, 200, 1, 98, "Current output index."), c("potentialOutput", "Potential output", "Yp", 20, 200, 1, 100, "Potential-output index."), c("okunBeta", "Okun coefficient", "β", 0, 2, 0.1, 0.4, "Unemployment response to a gap change."), c("gapChange", "Output-gap change", "Δygap", -15, 15, 0.5, 2, "Percentage-point gap change.")], sensitivityKey: "actualOutput",
    calculate: (p) => { const gap = (p.actualOutput - p.potentialOutput) / p.potentialOutput * 100; const unemploymentChange = -p.okunBeta * p.gapChange; return { results: { outputGap: n(gap), unemploymentChange: n(unemploymentChange), actualOutput: n(p.actualOutput), potentialOutput: n(p.potentialOutput) }, labels: { outputGap: "Output gap (%)", unemploymentChange: "Δ unemployment (pp)", actualOutput: "Actual output", potentialOutput: "Potential output" }, primaryKey: "outputGap", interpretation: gap < 0 ? "Actual output is below the stated potential-output benchmark." : gap > 0 ? "Actual output is above the stated potential-output benchmark." : "Actual output equals the stated potential benchmark.", equations: [{ label: "Output gap", expression: `ygap = (${p.actualOutput}−${p.potentialOutput})/${p.potentialOutput}×100 = ${n(gap)}%` }, { label: "Okun mapping", expression: `Δu = −${p.okunBeta}×${p.gapChange} = ${n(unemploymentChange)}pp` }] }; },
  }),
  "money-market": definition({
    slug: "money-market", sourceId: "money_market", formula: "M/P=kY−hi", principle: "With real balances fixed in the short run, the interest rate adjusts to clear stated money demand.",
    assumptions: ["The price level is predetermined in the short-run calculation.", "Money demand is linear in output and the interest rate."], limitations: ["The model omits banks, expectations and asset substitution.", "It does not forecast market interest rates."],
    controls: [c("realBalances", "Real balances", "M/P", 1, 300, 5, 100, "Nominal money divided by the price level."), c("incomeSensitivity", "Income sensitivity", "k", 0.05, 1.5, 0.05, 0.5, "Money-demand response to output."), c("output", "Output", "Y", 20, 500, 5, 240, "Income/output index."), c("interestSensitivity", "Interest sensitivity", "h", 1, 80, 1, 10, "Money-demand reduction per rate point.")], sensitivityKey: "realBalances",
    calculate: (p) => { const rate = (p.incomeSensitivity * p.output - p.realBalances) / p.interestSensitivity; const demand = p.incomeSensitivity * p.output - p.interestSensitivity * rate; return { results: { interestRate: n(rate), realBalances: n(p.realBalances), moneyDemand: n(demand), incomeComponent: n(p.incomeSensitivity * p.output) }, labels: { interestRate: "Clearing interest rate", realBalances: "Real balances", moneyDemand: "Money demand", incomeComponent: "Income money demand" }, primaryKey: "interestRate", interpretation: `At the stated real balances, the linear money-demand schedule clears at an interest rate of ${n(rate)}.`, equations: [{ label: "Clearing condition", expression: `${p.realBalances} = ${p.incomeSensitivity}(${p.output}) − ${p.interestSensitivity}i` }, { label: "Interest rate", expression: `i = (${n(p.incomeSensitivity * p.output)}−${p.realBalances})/${p.interestSensitivity} = ${n(rate)}` }] }; },
  }),
  "loanable-funds": definition({
    slug: "loanable-funds", sourceId: "loanable_funds", formula: "S(r)=I(r)+DEF", principle: "The clearing rate equates the saving schedule with investment plus the stated deficit demand for funds.",
    assumptions: ["This is a closed-economy teaching simplification.", "Saving rises and investment falls linearly with the rate."], limitations: ["The model omits bank balance sheets and international capital flows.", "It does not estimate an observed interest rate."],
    controls: [c("savingIntercept", "Saving intercept", "S_0", 0, 100, 1, 20, "Saving when the interest rate is zero."), c("savingSlope", "Saving slope", "s", 0.1, 10, 0.1, 2, "Saving response to the interest rate."), c("investmentIntercept", "Investment intercept", "I_0", 0, 160, 1, 80, "Investment when the interest rate is zero."), c("investmentSlope", "Investment slope", "i", 0.1, 10, 0.1, 3, "Investment reduction per rate point."), c("deficit", "Government deficit", "DEF", 0, 100, 1, 10, "Demand for loanable funds from the deficit.")], sensitivityKey: "deficit",
    calculate: (p) => { const rate = (p.investmentIntercept + p.deficit - p.savingIntercept) / (p.savingSlope + p.investmentSlope); const saving = p.savingIntercept + p.savingSlope * rate; const investment = p.investmentIntercept - p.investmentSlope * rate; return { results: { clearingRate: n(rate), saving: n(saving), investment: n(investment), deficit: n(p.deficit) }, labels: { clearingRate: "Clearing rate", saving: "Saving", investment: "Investment", deficit: "Deficit demand" }, primaryKey: "clearingRate", interpretation: `At ${n(rate)}%, saving equals investment plus the stated deficit in this closed-economy schedule.`, equations: [{ label: "Schedules", expression: `S=${p.savingIntercept}+${p.savingSlope}r; I=${p.investmentIntercept}−${p.investmentSlope}r` }, { label: "Clearing rate", expression: `r=(${p.investmentIntercept}+${p.deficit}−${p.savingIntercept})/(${p.savingSlope}+${p.investmentSlope})=${n(rate)}` }] }; },
  }),
  "bank-credit-creation": definition({
    slug: "bank-credit-creation", sourceId: "bank_credit_creation", formula: "ΔD=(1/rr)ΔR", principle: "The textbook deposit multiplier is an upper bound, conditional on no excess reserves, capital constraints or cash leakage.",
    assumptions: ["Banks hold only the stated required reserve ratio.", "There are no cash, capital or demand leakages."], limitations: ["Actual lending need not reach this ceiling.", "The model is not a bank balance-sheet simulation."],
    controls: [c("reserveRatio", "Required reserve ratio", "rr", 0.02, 1, 0.01, 0.1, "Required reserves as a decimal share."), c("reserveChange", "Reserve injection", "ΔR", -100, 200, 5, 10, "Change in reserves available to the banking system.")], sensitivityKey: "reserveRatio",
    calculate: (p) => { const multiplier = 1 / p.reserveRatio; const deposits = multiplier * p.reserveChange; return { results: { maxDepositChange: n(deposits), depositMultiplier: n(multiplier), reserveRatioPercent: n(p.reserveRatio * 100), reserveChange: n(p.reserveChange) }, labels: { maxDepositChange: "Maximum deposit change", depositMultiplier: "Textbook multiplier", reserveRatioPercent: "Reserve ratio (%)", reserveChange: "Reserve change" }, primaryKey: "maxDepositChange", interpretation: `The stated reserve ratio produces a textbook upper bound of ${n(deposits)} GCU in deposits; actual lending may be lower.`, equations: [{ label: "Multiplier", expression: `1/rr = 1/${p.reserveRatio} = ${n(multiplier)}` }, { label: "Deposit ceiling", expression: `ΔD = ${n(multiplier)}×${p.reserveChange} = ${n(deposits)}` }] }; },
  }),
  tariffs: definition({
    slug: "tariffs", sourceId: "tariffs", formula: "P_d=P_w(1+t); revenue=tP_wM", principle: "In a small-country partial-equilibrium benchmark, a tariff creates a domestic-price wedge and collects revenue on imports.",
    assumptions: ["The world price is fixed for the importing country.", "Imports are supplied as a stated quantity rather than solved endogenously."], limitations: ["The model does not calculate incidence, retaliation or general-equilibrium effects.", "Tariff revenue is not a welfare measure."],
    controls: [c("worldPrice", "World price", "P_w", 1, 100, 1, 10, "Price before the tariff wedge."), c("tariffRate", "Tariff rate", "t", 0, 1, 0.01, 0.2, "Ad valorem tariff rate as a decimal."), c("imports", "Imports", "M", 0, 500, 5, 50, "Imported units under the stated benchmark.")], sensitivityKey: "tariffRate",
    calculate: (p) => { const domesticPrice = p.worldPrice * (1 + p.tariffRate); const revenue = p.tariffRate * p.worldPrice * p.imports; return { results: { domesticPrice: n(domesticPrice), tariffRevenue: n(revenue), priceWedge: n(domesticPrice - p.worldPrice), imports: n(p.imports) }, labels: { domesticPrice: "Domestic price", tariffRevenue: "Tariff revenue", priceWedge: "Price wedge", imports: "Imports" }, primaryKey: "tariffRevenue", interpretation: `The selected tariff raises the domestic price from ${p.worldPrice} to ${n(domesticPrice)} and collects ${n(revenue)} GCU on stated imports.`, equations: [{ label: "Domestic price", expression: `P_d = ${p.worldPrice}(1+${p.tariffRate}) = ${n(domesticPrice)}` }, { label: "Revenue", expression: `tP_wM = ${p.tariffRate}×${p.worldPrice}×${p.imports} = ${n(revenue)}` }] }; },
  }),
};

export function getExtendedModelDefinition(slug: string) {
  return EXTENDED_MODEL_DEFINITIONS[slug as ExtendedModelSlug] ?? null;
}

/** Locates the browser-side calculator that backs a source model used in Model Practice. */
export function getExtendedModelDefinitionBySourceId(sourceId: string) {
  return Object.values(EXTENDED_MODEL_DEFINITIONS).find((item) => item.sourceId === sourceId) ?? null;
}

export function extendedModelSensitivity(definition: ExtendedModelDefinition, values: Values) {
  const parameter = definition.controls.find((control) => control.id === definition.sensitivityKey) ?? definition.controls[0];
  const steps = 6;
  return Array.from({ length: steps + 1 }, (_, index) => {
    const value = parameter.min + (parameter.max - parameter.min) * index / steps;
    const calculation = definition.calculate({ ...values, [parameter.id]: value });
    return { x: n(value), y: calculation.results[calculation.primaryKey] ?? 0 };
  });
}
