// Use a relative import so this deterministic engine can also be bundled into
// the protected Supabase Edge Function without relying on Next.js path aliases.
import { createInitialCommandCentreState } from "../command-centre/index.ts";
import type { Commodity, CommodityMarket, CountryTemplate, GlobalIndicators, ScenarioConfig, ScoringWeights, WorldCountryState } from "./types.ts";
import { FOUR_COUNTRY_TEMPLATES, TWELVE_COUNTRY_TEMPLATES, countryTemplateBySlug } from "./countries.ts";

export { BASE_COUNTRY_CONFIG, FOUR_COUNTRY_TEMPLATES, TWELVE_COUNTRY_TEMPLATES, countryTemplateBySlug } from "./countries.ts";

export const WORLD_SCORING_WEIGHTS: ScoringWeights = {
  domesticEconomicPerformance: 25,
  institutionalGovernance: 20,
  internationalEconomicPosition: 15,
  crisisResilience: 20,
  longTermDevelopment: 10,
  globalContribution: 10,
};

const market = (commodity: Commodity, price: number, elasticity: number, transport: number): CommodityMarket => ({ commodity, baselinePrice: price, globalPrice: price, totalSupply: 0, totalDemand: 0, priceElasticity: elasticity, transportCost: transport, storage: 20, supplyShockSensitivity: 1 });

export const DEFAULT_MARKETS: CommodityMarket[] = [
  market("energy", 100, 0.8, 6),
  market("food", 75, 0.65, 4),
  market("manufactured_goods", 120, 0.55, 8),
  market("technology_services", 145, 0.45, 2),
];

export const DEFAULT_COUNTRY_TEMPLATES: CountryTemplate[] = FOUR_COUNTRY_TEMPLATES;

export const DEFAULT_WORLD_SCENARIO: ScenarioConfig = {
  version: 1,
  type: "league_world",
  numberOfCountries: 4,
  numberOfRounds: 3,
  roundDurationSeconds: null,
  enabledAgreements: ["trade", "energy_supply", "technology_partnership"],
  enabledMarkets: ["energy", "food", "manufactured_goods", "technology_services"],
  scoringWeights: WORLD_SCORING_WEIGHTS,
  assumptions: ["All results are generated by deterministic rules.", "Countries begin within a 12% structural balance band.", "World clearing processes countries simultaneously and in a stable order."],
  countryTemplates: DEFAULT_COUNTRY_TEMPLATES,
  markets: DEFAULT_MARKETS,
  shocks: [
    { id: "global-energy-shock", title: "Global Energy Shock", description: "A global supply disruption raises energy costs.", scope: "global", triggerRound: 2, duration: 1, visibility: "public", affectedCountries: [], affectedCommodities: ["energy"], domesticEffects: { inflation: 1.4, growth: -0.75, reserves: -3 }, sectorEffects: { manufacturing: -5, energy: -4 }, worldEffects: { globalInflation: 0.8, globalGrowth: -0.45, commodityStress: 16 }, recoveryPath: 0.45 },
    { id: "global-capital-outflow", title: "Global Capital Outflow", description: "Global risk aversion raises financing pressure and reallocates capital.", scope: "financial", triggerRound: 3, duration: 1, visibility: "public", affectedCountries: [], affectedCommodities: [], domesticEffects: { inflation: 0.45, growth: -0.5, reserves: -6, capitalPressure: 10 }, sectorEffects: { technology: -7, manufacturing: -3 }, worldEffects: { financialStability: -13, globalGrowth: -0.25 }, recoveryPath: 0.35 },
  ],
};

export const TWELVE_COUNTRY_WORLD_SCENARIO: ScenarioConfig = {
  ...DEFAULT_WORLD_SCENARIO,
  version: 2,
  numberOfCountries: 12,
  numberOfRounds: 3,
  assumptions: [
    "All results are generated by deterministic rules.",
    "Every country begins inside the 96–104 structural power band.",
    "No country controls more than 15% of a commodity's opening supply.",
    "Fiscal deficits are permitted and create next-quarter debt and confidence effects.",
  ],
  countryTemplates: TWELVE_COUNTRY_TEMPLATES,
};

export const EMPTY_GLOBAL_INDICATORS: GlobalIndicators = { globalGrowth: 0, globalInflation: 0, tradeOpenness: 0, financialStability: 60, climateIndex: 50, commodityStress: 0, internationalCooperation: 50 };

/** Old four-country rows predate the detailed profile fields. Resolve them to
 * their maintained configuration so historic scenarios remain playable. */
export function resolveCountryTemplate(template: CountryTemplate): CountryTemplate {
  const fallback = countryTemplateBySlug(template.slug);
  if (!fallback) {
    if (!template.config?.macroBaseline) throw new Error(`Country template ${template.slug} is missing a complete profile.`);
    return template;
  }
  const supplied = template.config as Partial<typeof fallback.config>;
  return {
    ...fallback,
    id: template.id,
    slug: template.slug,
    name: template.name,
    specialisation: template.specialisation,
    balanceScore: template.balanceScore,
    config: {
      ...fallback.config,
      ...supplied,
      macroBaseline: { ...fallback.config.macroBaseline, ...supplied.macroBaseline },
      sectorShares: { ...fallback.config.sectorShares, ...supplied.sectorShares },
      commodityCapacity: { ...fallback.config.commodityCapacity, ...supplied.commodityCapacity },
      policySensitivities: { ...fallback.config.policySensitivities, ...supplied.policySensitivities },
      shockSensitivities: { ...fallback.config.shockSensitivities, ...supplied.shockSensitivities },
      visualIdentity: { ...fallback.config.visualIdentity, ...supplied.visualIdentity },
    },
  };
}

export function createCountryFromTemplate(template: CountryTemplate): WorldCountryState {
  template = resolveCountryTemplate(template);
  const domestic = createInitialCommandCentreState();
  const baseline = template.config.macroBaseline;
  domestic.macro.productivity = baseline.productivityIndex;
  domestic.macro.debt = baseline.governmentDebtPctGdp;
  domestic.macro.inflation = baseline.inflationRate;
  domestic.macro.unemployment = baseline.unemploymentRate;
  domestic.macro.approval = baseline.publicApproval;
  domestic.macro.inequality = baseline.inequalityIndex;
  domestic.macro.emissions = baseline.emissionsIndex;
  domestic.macro.growth = Number((1.4 + (baseline.realGdpIndex - 100) * 0.06).toFixed(1));
  domestic.resources.foreignReserves = baseline.foreignReservesIndex;
  domestic.resources.politicalCapital = baseline.politicalCapital;
  domestic.stakeholders.investors.confidence = baseline.investorConfidence;
  domestic.stakeholders.households.confidence = baseline.publicApproval;
  domestic.sectors.manufacturing.output_index = 60 + template.config.sectorShares.manufacturing * 1.15;
  domestic.sectors.technology.output_index = 60 + template.config.sectorShares.technology * 1.15;
  domestic.sectors.services.output_index = 60 + template.config.sectorShares.services * 1.15;
  domestic.sectors.energy.output_index = 60 + template.config.sectorShares.energy * 1.15;
  const capacity = template.config.commodityCapacity;
  return {
    countryId: template.id,
    countryName: template.name,
    templateId: template.id,
    templateConfig: structuredClone(template.config),
    domestic,
    resources: { fiscalCapacity: 100 + template.config.fiscalModifier, politicalCapital: baseline.politicalCapital, foreignReserves: baseline.foreignReservesIndex, administrativeCapacity: baseline.administrativeCapacity, landCapacity: baseline.landCapacity, energyCapacity: baseline.energyCapacity },
    external: {
      currencyIndex: baseline.currencyIndex,
      exchangePressure: 0,
      tradeBalance: 0,
      currentAccount: 0,
      capitalAccount: 0,
      investorConfidence: baseline.investorConfidence + template.config.capitalAttractionModifier,
      partnerTrust: 60,
      productionCapacity: {
        energy: 100 * capacity.energy,
        food: 100 * capacity.food,
        manufactured_goods: 100 * capacity.manufactured_goods,
        technology_services: 100 * capacity.technology_services,
      },
      domesticDemand: { energy: 96 + (baseline.populationIndex - 100) * 0.35, food: 94 + (baseline.populationIndex - 100) * 0.3, manufactured_goods: 98 + (baseline.realGdpIndex - 100) * 0.6, technology_services: 92 + (baseline.productivityIndex - 100) * 0.45 },
      commodityStocks: { energy: 20, food: 20, manufactured_goods: 20, technology_services: 20 },
    },
    activeAgreements: [],
    institutionalHistory: [],
  };
}
