// Use a relative import so this deterministic engine can also be bundled into
// the protected Supabase Edge Function without relying on Next.js path aliases.
import { createInitialCommandCentreState } from "../command-centre/index.ts";
import type { Commodity, CommodityMarket, CountryTemplate, GlobalIndicators, ScenarioConfig, ScoringWeights, WorldCountryState } from "./types.ts";

export const WORLD_SCORING_WEIGHTS: ScoringWeights = {
  domesticEconomicPerformance: 25,
  institutionalGovernance: 20,
  internationalEconomicPosition: 15,
  crisisResilience: 20,
  longTermDevelopment: 10,
  globalContribution: 10,
};

const market = (commodity: Commodity, price: number, elasticity: number, transport: number): CommodityMarket => ({ commodity, baselinePrice: price, globalPrice: price, totalSupply: 0, totalDemand: 0, priceElasticity: elasticity, transportCost: transport, storage: 20, supplyShockSensitivity: 1 });

export const DEFAULT_MARKETS: CommodityMarket[] = [
  market("energy", 100, 0.8, 6),
  market("food", 75, 0.65, 4),
  market("manufactured_goods", 120, 0.55, 8),
  market("technology_services", 145, 0.45, 2),
];

export const DEFAULT_COUNTRY_TEMPLATES: CountryTemplate[] = [
  { id: "techoria", slug: "techoria", name: "Techoria", specialisation: "Technology and R&D", config: { sectorAdvantages: { technology: 8 }, commodityAdvantages: { technology_services: 8 }, vulnerabilities: { interestRateSensitivity: 7, skilledLabourCostPressure: 5 }, productivityModifier: 8, fiscalModifier: 0, tradeModifier: 2, resourceModifier: 0, capitalAttractionModifier: 4 }, balanceScore: 104 },
  { id: "manufactura", slug: "manufactura", name: "Manufactura", specialisation: "Manufacturing and exports", config: { sectorAdvantages: { manufacturing: 9 }, commodityAdvantages: { manufactured_goods: 9 }, vulnerabilities: { importedEnergyDependency: 8, globalDemandSensitivity: 6 }, productivityModifier: 2, fiscalModifier: 0, tradeModifier: 7, resourceModifier: 0, capitalAttractionModifier: 0 }, balanceScore: 103 },
  { id: "greenovia", slug: "greenovia", name: "Greenovia", specialisation: "Green transition", config: { sectorAdvantages: { energy: 8 }, commodityAdvantages: { energy: 8 }, vulnerabilities: { shortRunInvestmentCost: 6, initialFiscalPressure: 5 }, productivityModifier: 3, fiscalModifier: -3, tradeModifier: 1, resourceModifier: 7, capitalAttractionModifier: 1 }, balanceScore: 102 },
  { id: "agritania", slug: "agritania", name: "Agritania", specialisation: "Agriculture and land resources", config: { sectorAdvantages: { services: 1 }, commodityAdvantages: { food: 9 }, vulnerabilities: { climateVulnerability: 7, productivityCeiling: 5 }, productivityModifier: -2, fiscalModifier: 1, tradeModifier: 4, resourceModifier: 8, capitalAttractionModifier: -1 }, balanceScore: 101 },
];

export const DEFAULT_WORLD_SCENARIO: ScenarioConfig = {
  version: 1,
  type: "league_world",
  numberOfCountries: 4,
  numberOfRounds: 3,
  roundDurationSeconds: null,
  enabledAgreements: ["trade", "energy_supply", "technology_partnership"],
  enabledMarkets: ["energy", "food", "manufactured_goods", "technology_services"],
  scoringWeights: WORLD_SCORING_WEIGHTS,
  assumptions: ["All results are generated by deterministic rules.", "Countries begin within a 12% structural balance band.", "World clearing processes countries simultaneously and in a stable order."],
  countryTemplates: DEFAULT_COUNTRY_TEMPLATES,
  markets: DEFAULT_MARKETS,
  shocks: [
    { id: "global-energy-shock", title: "Global Energy Shock", description: "A global supply disruption raises energy costs.", scope: "global", triggerRound: 2, duration: 1, visibility: "public", affectedCountries: [], affectedCommodities: ["energy"], domesticEffects: { inflation: 1.4, growth: -0.75, reserves: -3 }, sectorEffects: { manufacturing: -5, energy: -4 }, worldEffects: { globalInflation: 0.8, globalGrowth: -0.45, commodityStress: 16 }, recoveryPath: 0.45 },
    { id: "global-capital-outflow", title: "Global Capital Outflow", description: "Global risk aversion raises financing pressure and reallocates capital.", scope: "financial", triggerRound: 3, duration: 1, visibility: "public", affectedCountries: [], affectedCommodities: [], domesticEffects: { inflation: 0.45, growth: -0.5, reserves: -6, capitalPressure: 10 }, sectorEffects: { technology: -7, manufacturing: -3 }, worldEffects: { financialStability: -13, globalGrowth: -0.25 }, recoveryPath: 0.35 },
  ],
};

export const EMPTY_GLOBAL_INDICATORS: GlobalIndicators = { globalGrowth: 0, globalInflation: 0, tradeOpenness: 0, financialStability: 60, climateIndex: 50, commodityStress: 0, internationalCooperation: 50 };

export function createCountryFromTemplate(template: CountryTemplate): WorldCountryState {
  const domestic = createInitialCommandCentreState();
  domestic.macro.productivity += template.config.productivityModifier;
  domestic.macro.debt -= template.config.fiscalModifier;
  domestic.resources.foreignReserves += template.config.resourceModifier;
  domestic.sectors.technology.output_index += template.config.sectorAdvantages.technology ?? 0;
  domestic.sectors.manufacturing.output_index += template.config.sectorAdvantages.manufacturing ?? 0;
  domestic.sectors.energy.output_index += template.config.sectorAdvantages.energy ?? 0;
  const resource = template.config.resourceModifier;
  return {
    countryId: template.id,
    countryName: template.name,
    templateId: template.id,
    domestic,
    resources: { fiscalCapacity: 100 + template.config.fiscalModifier, politicalCapital: 100, foreignReserves: 100 + resource, administrativeCapacity: 100, landCapacity: 100 + resource, energyCapacity: 100 + resource },
    external: {
      currencyIndex: 100,
      exchangePressure: 0,
      tradeBalance: 0,
      currentAccount: 0,
      capitalAccount: 0,
      investorConfidence: 55 + template.config.capitalAttractionModifier,
      partnerTrust: 60,
      productionCapacity: {
        energy: 80 + resource + (template.config.commodityAdvantages?.energy ?? 0),
        food: 80 + resource + (template.config.commodityAdvantages?.food ?? 0),
        manufactured_goods: 80 + (template.config.sectorAdvantages.manufacturing ?? 0) + (template.config.commodityAdvantages?.manufactured_goods ?? 0),
        technology_services: 80 + (template.config.sectorAdvantages.technology ?? 0) + (template.config.commodityAdvantages?.technology_services ?? 0),
      },
      domesticDemand: { energy: 78, food: 76, manufactured_goods: 82, technology_services: 74 },
      commodityStocks: { energy: 20, food: 20, manufactured_goods: 20, technology_services: 20 },
    },
    activeAgreements: [],
    institutionalHistory: [],
  };
}
