import type { Commodity, CountryProfileConfig, CountryTemplate } from "./types.ts";
import { withBasePath } from "../../base-path.ts";

export const BASE_COUNTRY_CONFIG = {
  populationIndex: 100,
  realGdpIndex: 100,
  productivityIndex: 100,
  inflationRate: 3.5,
  unemploymentRate: 6,
  governmentDebtPctGdp: 65,
  fiscalBalancePctGdp: -2,
  publicApproval: 55,
  inequalityIndex: 0.34,
  emissionsIndex: 100,
  foreignReservesIndex: 100,
  institutionalCapacity: 100,
  politicalCapital: 100,
  administrativeCapacity: 100,
  landCapacity: 100,
  energyCapacity: 100,
  investorConfidence: 55,
  currencyIndex: 100,
} as const;

type CountryInput = {
  id: string;
  name: string;
  shortCode: string;
  category: string;
  tagline: string;
  description: string;
  primary: string;
  secondary: string;
  strengths: [string, string];
  vulnerabilities: [string, string];
  shares: CountryProfileConfig["sectorShares"];
  commodities: Record<Commodity, number>;
  advantages: CountryProfileConfig["sectorAdvantages"];
  vulnerabilityModifiers: Record<string, number>;
  policy: Record<string, number>;
  shocks: Record<string, number>;
  strategies: [string, string];
  macro: Partial<CountryProfileConfig["macroBaseline"]>;
  modifiers: Pick<CountryProfileConfig, "productivityModifier" | "fiscalModifier" | "tradeModifier" | "resourceModifier" | "capitalAttractionModifier">;
  colours: [string, string];
  symbol: string;
  balanceScore: number;
};

const commodityAdvantages = (capacity: Record<Commodity, number>) => Object.fromEntries(Object.entries(capacity).map(([key, value]) => [key, Math.round((value - 1) * 40)])) as Partial<Record<Commodity, number>>;

function country(input: CountryInput): CountryTemplate {
  const config: CountryProfileConfig = {
    version: 1,
    shortCode: input.shortCode,
    category: input.category,
    tagline: input.tagline,
    description: input.description,
    primarySpecialisation: input.primary,
    secondarySpecialisation: input.secondary,
    primaryStrength: input.strengths[0],
    secondaryStrength: input.strengths[1],
    primaryVulnerability: input.vulnerabilities[0],
    secondaryVulnerability: input.vulnerabilities[1],
    macroBaseline: { ...BASE_COUNTRY_CONFIG, ...input.macro },
    sectorShares: input.shares,
    commodityCapacity: input.commodities,
    sectorAdvantages: input.advantages,
    commodityAdvantages: commodityAdvantages(input.commodities),
    vulnerabilities: input.vulnerabilityModifiers,
    policySensitivities: input.policy,
    shockSensitivities: input.shocks,
    viableStrategies: input.strategies,
    visualIdentity: { primary: input.colours[0], secondary: input.colours[1], symbol: input.symbol, flag: withBasePath(`/league/flags/${input.id}.svg`), alt: `${input.name} abstract geometric flag` },
    configHash: `twelve-country-v1-${input.id}`,
    ...input.modifiers,
  };
  return { id: input.id, slug: input.id, name: input.name, specialisation: `${input.primary} · ${input.secondary}`, config, balanceScore: input.balanceScore };
}

/**
 * A symmetric twelve-country teaching world. No country has a total opening
 * advantage above the 96–104 power band; differences are pathways and risks.
 */
export const TWELVE_COUNTRY_TEMPLATES: CountryTemplate[] = [
  country({ id: "techoria", name: "Techoria", shortCode: "TEC", category: "Knowledge and Innovation", tagline: "Innovation powered by research, technology and skilled labour.", description: "A research-led economy whose technology exports can compound productivity, but whose skilled labour and investment respond sharply to financial conditions.", primary: "Research-led productivity", secondary: "Technology exports", strengths: ["Technology productivity +8%", "Research efficiency +7%"], vulnerabilities: ["Interest-rate sensitivity +7%", "Skilled-labour cost pressure +5%"], shares: { manufacturing: 18, technology: 30, services: 32, energy: 8, agriculture: 12 }, commodities: { energy: 0.8, food: 0.8, manufactured_goods: 0.95, technology_services: 1.25 }, advantages: { technology: 8 }, vulnerabilityModifiers: { interestRateSensitivity: 7, skilledLabourCostPressure: 5 }, policy: { researchEfficiency: 7, technologyPartnership: 6, highRateInvestmentDrag: 7 }, shocks: { financial: 6, technology: -4 }, strategies: ["Research-led productivity growth", "Technology exports and international partnerships"], macro: { productivityIndex: 105, inflationRate: 3.4, unemploymentRate: 5.8, foreignReservesIndex: 101, institutionalCapacity: 103, investorConfidence: 58 }, modifiers: { productivityModifier: 5, fiscalModifier: 0, tradeModifier: 2, resourceModifier: -1, capitalAttractionModifier: 3 }, colours: ["#4f46e5", "#a5b4fc"], symbol: "orbit", balanceScore: 102 }),
  country({ id: "meditoria", name: "Meditoria", shortCode: "MED", category: "Knowledge and Human Capital", tagline: "A service economy built around education, healthcare and human capital.", description: "Human capital and professional services are its durable route to growth, balanced by longer lags and a visible public-service fiscal commitment.", primary: "Human capital", secondary: "Professional services", strengths: ["Human-capital productivity +8%", "Healthcare and professional services +7%"], vulnerabilities: ["Public-service fiscal pressure +6%", "Long policy lag +5%"], shares: { manufacturing: 14, technology: 18, services: 43, energy: 8, agriculture: 17 }, commodities: { energy: 0.85, food: 0.95, manufactured_goods: 0.85, technology_services: 1.18 }, advantages: { services: 7, technology: 3 }, vulnerabilityModifiers: { publicServiceFiscalPressure: 6, longPolicyLag: 5 }, policy: { educationReturn: 8, publicServiceLag: 5, welfareApprovalSensitivity: 5 }, shocks: { fiscal: 5, labour: -3 }, strategies: ["Public education and long-run productivity", "Healthcare, professional services and biotechnology exports"], macro: { populationIndex: 101, productivityIndex: 103, unemploymentRate: 5.7, governmentDebtPctGdp: 67, institutionalCapacity: 102, energyCapacity: 98 }, modifiers: { productivityModifier: 3, fiscalModifier: -2, tradeModifier: 1, resourceModifier: -1, capitalAttractionModifier: 1 }, colours: ["#0f766e", "#99f6e4"], symbol: "column", balanceScore: 100 }),
  country({ id: "culturia", name: "Culturia", shortCode: "CUL", category: "Knowledge and Creative Services", tagline: "A creative and service economy shaped by tourism, culture and global demand.", description: "Culturia converts openness and creative capacity into service employment, while global confidence and exchange-rate changes transmit quickly through its economy.", primary: "Creative-service exports", secondary: "Digital media", strengths: ["Creative services exports +8%", "Service employment capacity +7%"], vulnerabilities: ["Consumer-confidence sensitivity +8%", "Exchange-rate sensitivity +5%"], shares: { manufacturing: 12, technology: 17, services: 49, energy: 7, agriculture: 15 }, commodities: { energy: 0.8, food: 0.9, manufactured_goods: 0.8, technology_services: 1.12 }, advantages: { services: 8, technology: 2 }, vulnerabilityModifiers: { consumerConfidenceSensitivity: 8, exchangeRateSensitivity: 5 }, policy: { marketOpening: 6, exchangeRateExportBoost: 5, demandShockEmployment: 7 }, shocks: { globalDemand: 8, currency: 5 }, strategies: ["Tourism and creative-service exports", "Digital media and creative technology"], macro: { realGdpIndex: 98, inflationRate: 3.6, unemploymentRate: 6.2, foreignReservesIndex: 98, institutionalCapacity: 99, investorConfidence: 54 }, modifiers: { productivityModifier: 1, fiscalModifier: -1, tradeModifier: 4, resourceModifier: -2, capitalAttractionModifier: 0 }, colours: ["#be185d", "#f9a8d4"], symbol: "wave", balanceScore: 98 }),
  country({ id: "manufactura", name: "Manufactura", shortCode: "MAN", category: "Production and Industry", tagline: "An export-oriented economy driven by manufacturing and industrial employment.", description: "Industrial scale and employment absorption support two upgrade paths, but imported energy and changes in global demand are central vulnerabilities.", primary: "Export manufacturing", secondary: "Automation upgrade", strengths: ["Manufacturing capacity +9%", "Employment absorption +7%"], vulnerabilities: ["Imported-energy dependency +8%", "Global-demand sensitivity +6%"], shares: { manufacturing: 34, technology: 16, services: 25, energy: 13, agriculture: 12 }, commodities: { energy: 0.9, food: 0.85, manufactured_goods: 1.25, technology_services: 0.95 }, advantages: { manufacturing: 9 }, vulnerabilityModifiers: { importedEnergyDependency: 8, globalDemandSensitivity: 6 }, policy: { infrastructureMultiplier: 7, technologyImportProductivity: 5, tariffInputCost: 5 }, shocks: { energy: 8, globalDemand: 6 }, strategies: ["Export manufacturing", "Automation and high-value manufacturing"], macro: { populationIndex: 103, realGdpIndex: 102, productivityIndex: 101, inflationRate: 3.7, unemploymentRate: 5.6, governmentDebtPctGdp: 66, energyCapacity: 102 }, modifiers: { productivityModifier: 1, fiscalModifier: -1, tradeModifier: 5, resourceModifier: 1, capitalAttractionModifier: 0 }, colours: ["#c2410c", "#fdba74"], symbol: "grid", balanceScore: 102 }),
  country({ id: "materia", name: "Materia", shortCode: "MAT", category: "Production and Resources", tagline: "A materials economy connecting natural resources with industrial processing.", description: "Materia can turn resource processing into higher-value industrial exports, but commodity volatility and environmental pressure punish an undiversified path.", primary: "Industrial materials", secondary: "Value-chain upgrading", strengths: ["Industrial-material output +8%", "Domestic input security +7%"], vulnerabilities: ["Environmental pressure +7%", "Commodity-price volatility +6%"], shares: { manufacturing: 28, technology: 13, services: 24, energy: 23, agriculture: 12 }, commodities: { energy: 1.1, food: 0.9, manufactured_goods: 1.15, technology_services: 0.85 }, advantages: { manufacturing: 6, energy: 4 }, vulnerabilityModifiers: { environmentalPressure: 7, commodityPriceVolatility: 6 }, policy: { processingUpgrade: 7, resourceDepletionCost: 6, commodityRevenueSensitivity: 6 }, shocks: { commodity: 6, climate: 4 }, strategies: ["Industrial-material exports", "Resource processing and value-chain upgrading"], macro: { realGdpIndex: 101, productivityIndex: 98, governmentDebtPctGdp: 63, foreignReservesIndex: 103, landCapacity: 103, energyCapacity: 104 }, modifiers: { productivityModifier: -2, fiscalModifier: 2, tradeModifier: 3, resourceModifier: 4, capitalAttractionModifier: 0 }, colours: ["#a16207", "#fde68a"], symbol: "facet", balanceScore: 101 }),
  country({ id: "agritania", name: "Agritania", shortCode: "AGR", category: "Production and Land Resources", tagline: "A land-rich economy specialising in food security and agricultural production.", description: "Agritania can pair food exports with agricultural technology, yet climate exposure and a productivity constraint keep its two development routes distinct.", primary: "Food security", secondary: "Agricultural technology", strengths: ["Food-production capacity +9%", "Land capacity +8%"], vulnerabilities: ["Climate vulnerability +8%", "Productivity constraint +5%"], shares: { manufacturing: 16, technology: 12, services: 26, energy: 10, agriculture: 36 }, commodities: { energy: 0.9, food: 1.3, manufactured_goods: 0.85, technology_services: 0.8 }, advantages: { services: 1 }, vulnerabilityModifiers: { climateVulnerability: 8, productivityConstraint: 5 }, policy: { agricultureInvestment: 8, technologyImportRelief: 5, landEnvironmentalCost: 5 }, shocks: { climate: 8, food: -4 }, strategies: ["Food security and agricultural exports", "Agricultural technology and productivity upgrading"], macro: { populationIndex: 98, realGdpIndex: 97, productivityIndex: 95, inflationRate: 3.8, unemploymentRate: 6.3, governmentDebtPctGdp: 64, landCapacity: 105, energyCapacity: 99 }, modifiers: { productivityModifier: -5, fiscalModifier: 1, tradeModifier: 3, resourceModifier: 4, capitalAttractionModifier: -2 }, colours: ["#4d7c0f", "#bef264"], symbol: "field", balanceScore: 97 }),
  country({ id: "greenovia", name: "Greenovia", shortCode: "GRN", category: "Energy and Sustainability", tagline: "A transition economy investing in renewable energy and environmental resilience.", description: "Its early green investments are costly, but renewable capacity and emissions efficiency offer a resilient long-run route and export potential.", primary: "Green transition", secondary: "Renewable technology exports", strengths: ["Renewable-energy capacity +9%", "Emissions efficiency +8%"], vulnerabilities: ["Initial investment cost +6%", "Short-run fiscal pressure +5%"], shares: { manufacturing: 20, technology: 19, services: 29, energy: 20, agriculture: 12 }, commodities: { energy: 1.15, food: 0.95, manufactured_goods: 1, technology_services: 1.05 }, advantages: { energy: 8, technology: 3 }, vulnerabilityModifiers: { initialInvestmentCost: 6, shortRunFiscalPressure: 5 }, policy: { greenInvestmentReturn: 8, energyShockResilience: 7, divestmentLongRunCost: 6 }, shocks: { energy: -5, climate: -4 }, strategies: ["Domestic green transition", "Renewable technology exports"], macro: { productivityIndex: 101, inflationRate: 3.3, governmentDebtPctGdp: 67, foreignReservesIndex: 99, institutionalCapacity: 104, energyCapacity: 104 }, modifiers: { productivityModifier: 1, fiscalModifier: -2, tradeModifier: 1, resourceModifier: 4, capitalAttractionModifier: 1 }, colours: ["#047857", "#6ee7b7"], symbol: "leaf", balanceScore: 101 }),
  country({ id: "energea", name: "Energea", shortCode: "ENG", category: "Energy and Strategic Supply", tagline: "A diversified energy producer balancing export revenues with economic transition.", description: "Energy exports offer fiscal capacity and a path to diversification, but price volatility and concentration make strategic reinvestment essential.", primary: "Energy exports", secondary: "Industrial diversification", strengths: ["Energy-production capacity +9%", "Energy-export revenue +7%"], vulnerabilities: ["Energy-price volatility +8%", "Diversification weakness +6%"], shares: { manufacturing: 22, technology: 13, services: 24, energy: 30, agriculture: 11 }, commodities: { energy: 1.3, food: 0.85, manufactured_goods: 1, technology_services: 0.85 }, advantages: { energy: 9 }, vulnerabilityModifiers: { energyPriceVolatility: 8, diversificationWeakness: 6 }, policy: { energyRevenue: 7, diversificationInvestment: 7, transitionExposure: 6 }, shocks: { energy: 8, climate: 5 }, strategies: ["Energy exports and fiscal accumulation", "Energy-funded industrial diversification"], macro: { realGdpIndex: 102, productivityIndex: 97, governmentDebtPctGdp: 62, foreignReservesIndex: 105, landCapacity: 101, energyCapacity: 105, investorConfidence: 56 }, modifiers: { productivityModifier: -3, fiscalModifier: 3, tradeModifier: 3, resourceModifier: 5, capitalAttractionModifier: 1 }, colours: ["#b45309", "#fcd34d"], symbol: "beam", balanceScore: 100 }),
  country({ id: "constructa", name: "Constructa", shortCode: "CON", category: "Infrastructure and Urban Development", tagline: "An infrastructure economy centred on construction, housing and urban productivity.", description: "Build-out investment can create immediate and delayed gains, yet debt sensitivity and a construction cycle require careful fiscal pacing.", primary: "Infrastructure-led growth", secondary: "Urban productivity", strengths: ["Infrastructure efficiency +8%", "Construction capacity +7%"], vulnerabilities: ["Debt sensitivity +7%", "Construction-cycle volatility +5%"], shares: { manufacturing: 30, technology: 12, services: 31, energy: 15, agriculture: 12 }, commodities: { energy: 1, food: 0.9, manufactured_goods: 1.2, technology_services: 0.85 }, advantages: { manufacturing: 6, services: 3 }, vulnerabilityModifiers: { debtSensitivity: 7, constructionCycleVolatility: 5 }, policy: { infrastructureEfficiency: 8, landConstraint: 5, housingConfidence: 5 }, shocks: { financial: 7, commodity: 3 }, strategies: ["Infrastructure-led growth", "Housing reform and urban productivity"], macro: { populationIndex: 104, realGdpIndex: 103, productivityIndex: 99, governmentDebtPctGdp: 68, fiscalBalancePctGdp: -2.3, institutionalCapacity: 100, landCapacity: 98 }, modifiers: { productivityModifier: -1, fiscalModifier: -3, tradeModifier: 2, resourceModifier: 0, capitalAttractionModifier: 0 }, colours: ["#0369a1", "#7dd3fc"], symbol: "arch", balanceScore: 99 }),
  country({ id: "financora", name: "Financora", shortCode: "FIN", category: "Finance and Services", tagline: "A financial and commercial-service economy integrated into global capital markets.", description: "Financora attracts capital and intermediates finance efficiently, but confidence reversals and contagion make its financial stability a live policy challenge.", primary: "International finance", secondary: "Productive long-term finance", strengths: ["Capital attraction +8%", "Financial intermediation +8%"], vulnerabilities: ["Capital-flow volatility +8%", "Financial-contagion risk +6%"], shares: { manufacturing: 12, technology: 19, services: 52, energy: 8, agriculture: 9 }, commodities: { energy: 0.85, food: 0.85, manufactured_goods: 0.8, technology_services: 1.15 }, advantages: { services: 8, technology: 4 }, vulnerabilityModifiers: { capitalFlowVolatility: 8, financialContagionRisk: 6 }, policy: { credibilityCapitalFlow: 8, currencySwapBenefit: 6, bailoutMoralHazard: 5 }, shocks: { financial: 8, currency: 5 }, strategies: ["International financial centre", "Domestic long-term finance and productive investment"], macro: { realGdpIndex: 99, productivityIndex: 104, inflationRate: 3.2, unemploymentRate: 5.9, governmentDebtPctGdp: 64, foreignReservesIndex: 104, investorConfidence: 59 }, modifiers: { productivityModifier: 4, fiscalModifier: 1, tradeModifier: 3, resourceModifier: 1, capitalAttractionModifier: 4 }, colours: ["#7e22ce", "#d8b4fe"], symbol: "node", balanceScore: 103 }),
  country({ id: "logistica", name: "Logistica", shortCode: "LOG", category: "Trade and Connectivity", tagline: "A logistics and trade hub connecting regional supply chains and markets.", description: "Low transport costs and reliable trade links create a connectivity path, while fuel costs and external demand can quickly alter its fortunes.", primary: "Global logistics", secondary: "Supply-chain integration", strengths: ["Transport efficiency +9%", "Trade connectivity +8%"], vulnerabilities: ["External-demand dependency +7%", "Fuel-cost sensitivity +5%"], shares: { manufacturing: 24, technology: 15, services: 44, energy: 9, agriculture: 8 }, commodities: { energy: 0.85, food: 0.9, manufactured_goods: 1.1, technology_services: 1 }, advantages: { services: 6, manufacturing: 3 }, vulnerabilityModifiers: { externalDemandDependency: 7, fuelCostSensitivity: 5 }, policy: { transportEfficiency: 9, tradeAgreementDelivery: 6, fuelCostPassThrough: 5 }, shocks: { trade: 7, energy: 5 }, strategies: ["Global logistics hub", "Regional supply-chain integration"], macro: { populationIndex: 97, realGdpIndex: 99, productivityIndex: 102, inflationRate: 3.6, unemploymentRate: 5.8, governmentDebtPctGdp: 63, foreignReservesIndex: 102 }, modifiers: { productivityModifier: 2, fiscalModifier: 2, tradeModifier: 5, resourceModifier: -1, capitalAttractionModifier: 1 }, colours: ["#075985", "#67e8f9"], symbol: "route", balanceScore: 101 }),
  country({ id: "centravia", name: "Centravia", shortCode: "CEN", category: "Diversified Domestic Market", tagline: "A balanced economy supported by a large domestic market and diversified production.", description: "Centravia absorbs shocks through a broad domestic market and diversified sectors, trading peak export specialisation for steadier policy choices.", primary: "Domestic-demand growth", secondary: "Diversified regional economy", strengths: ["Domestic-demand stability +8%", "Sector diversification +7%"], vulnerabilities: ["Export-specialisation limit +5%", "Welfare and public-service pressure +6%"], shares: { manufacturing: 22, technology: 18, services: 38, energy: 11, agriculture: 11 }, commodities: { energy: 0.95, food: 1.05, manufactured_goods: 1, technology_services: 0.95 }, advantages: { services: 4, manufacturing: 2, technology: 2 }, vulnerabilityModifiers: { exportSpecialisationLimit: 5, welfarePublicServicePressure: 6 }, policy: { domesticDemandSupport: 8, welfareResponse: 6, exportSpecialisationCap: 5 }, shocks: { globalDemand: -4, fiscal: 5 }, strategies: ["Domestic-demand-led growth", "Diversified regional economy"], macro: { populationIndex: 105, realGdpIndex: 103, productivityIndex: 100, inflationRate: 3.5, unemploymentRate: 5.5, governmentDebtPctGdp: 69, fiscalBalancePctGdp: -2.4, institutionalCapacity: 101, landCapacity: 102, energyCapacity: 101 }, modifiers: { productivityModifier: 0, fiscalModifier: -3, tradeModifier: 0, resourceModifier: 1, capitalAttractionModifier: 0 }, colours: ["#334155", "#cbd5e1"], symbol: "ring", balanceScore: 99 }),
];

export const FOUR_COUNTRY_TEMPLATES = TWELVE_COUNTRY_TEMPLATES.filter((template) => ["techoria", "manufactura", "greenovia", "agritania"].includes(template.id));

export const countryTemplateBySlug = (slug: string) => TWELVE_COUNTRY_TEMPLATES.find((template) => template.slug === slug) ?? null;
